-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_packetizer_Block_entry_fsm_state_fb_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of vdif_chain_packetizer_Block_entry_fsm_state_fb_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fsm_state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal next_state_assign_4_packet_fsm_1_fu_18_ap_ready : STD_LOGIC;
    signal next_state_assign_4_packet_fsm_1_fu_18_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal next_state_assign_3_packet_fsm_2_fu_23_ap_ready : STD_LOGIC;
    signal next_state_assign_3_packet_fsm_2_fu_23_ap_return : STD_LOGIC_VECTOR (1 downto 0);
    signal next_state_assign_2_packet_fsm_fu_29_ap_ready : STD_LOGIC;
    signal next_state_assign_2_packet_fsm_fu_29_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_packet_fsm_1 IS
    port (
        ap_ready : OUT STD_LOGIC;
        current_state : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component vdif_chain_packet_fsm_2 IS
    port (
        ap_ready : OUT STD_LOGIC;
        current_state : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (1 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component vdif_chain_packet_fsm IS
    port (
        ap_ready : OUT STD_LOGIC;
        current_state : IN STD_LOGIC_VECTOR (1 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;



begin
    next_state_assign_4_packet_fsm_1_fu_18 : component vdif_chain_packet_fsm_1
    port map (
        ap_ready => next_state_assign_4_packet_fsm_1_fu_18_ap_ready,
        current_state => fsm_state,
        ap_return => next_state_assign_4_packet_fsm_1_fu_18_ap_return,
        ap_rst => ap_rst);

    next_state_assign_3_packet_fsm_2_fu_23 : component vdif_chain_packet_fsm_2
    port map (
        ap_ready => next_state_assign_3_packet_fsm_2_fu_23_ap_ready,
        current_state => next_state_assign_4_packet_fsm_1_fu_18_ap_return,
        ap_return => next_state_assign_3_packet_fsm_2_fu_23_ap_return,
        ap_rst => ap_rst);

    next_state_assign_2_packet_fsm_fu_29 : component vdif_chain_packet_fsm
    port map (
        ap_ready => next_state_assign_2_packet_fsm_fu_29_ap_ready,
        current_state => next_state_assign_3_packet_fsm_2_fu_23_ap_return,
        ap_return => next_state_assign_2_packet_fsm_fu_29_ap_return,
        ap_rst => ap_rst);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                fsm_state <= next_state_assign_2_packet_fsm_fu_29_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

end behav;
