-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_header_generator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (29 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (23 downto 0);
    epoch_dout : IN STD_LOGIC_VECTOR (5 downto 0);
    epoch_empty_n : IN STD_LOGIC;
    epoch_read : OUT STD_LOGIC;
    epoch_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    epoch_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    station_id_empty_n : IN STD_LOGIC;
    station_id_read : OUT STD_LOGIC;
    station_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    thread_id_empty_n : IN STD_LOGIC;
    thread_id_read : OUT STD_LOGIC;
    thread_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_dout : IN STD_LOGIC_VECTOR (4 downto 0);
    bits_per_sample_empty_n : IN STD_LOGIC;
    bits_per_sample_read : OUT STD_LOGIC;
    bits_per_sample_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    complex_data_empty_n : IN STD_LOGIC;
    complex_data_read : OUT STD_LOGIC;
    complex_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    payload_words_empty_n : IN STD_LOGIC;
    payload_words_read : OUT STD_LOGIC;
    payload_words_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    header_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    header_ce0 : OUT STD_LOGIC;
    header_we0 : OUT STD_LOGIC;
    header_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    header_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    header_ce1 : OUT STD_LOGIC;
    header_we1 : OUT STD_LOGIC;
    header_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of vdif_chain_header_generator is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv32_1000000 : STD_LOGIC_VECTOR (31 downto 0) := "00000001000000000000000000000000";
    constant ap_const_lv32_ACABFEED : STD_LOGIC_VECTOR (31 downto 0) := "10101100101010111111111011101101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_FC000000 : STD_LOGIC_VECTOR (31 downto 0) := "11111100000000000000000000000000";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal epoch_blk_n : STD_LOGIC;
    signal station_id_blk_n : STD_LOGIC;
    signal thread_id_blk_n : STD_LOGIC;
    signal bits_per_sample_blk_n : STD_LOGIC;
    signal complex_data_blk_n : STD_LOGIC;
    signal payload_words_blk_n : STD_LOGIC;
    signal payload_words_1_reg_336 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal complex_data_1_reg_340 : STD_LOGIC_VECTOR (0 downto 0);
    signal bits_per_sample_1_reg_345 : STD_LOGIC_VECTOR (4 downto 0);
    signal thread_id_1_reg_350 : STD_LOGIC_VECTOR (9 downto 0);
    signal station_id_1_reg_355 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln_reg_360 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal header_we1_local : STD_LOGIC;
    signal header_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln21_fu_233_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal header_ce1_local : STD_LOGIC;
    signal header_address1_local : STD_LOGIC_VECTOR (2 downto 0);
    signal header_we0_local : STD_LOGIC;
    signal header_d0_local : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_fu_246_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal header_ce0_local : STD_LOGIC;
    signal header_address0_local : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln30_fu_282_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln37_fu_329_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_238_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln28_fu_261_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal frame_length_fu_264_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln31_fu_270_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln30_cast_fu_274_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal shl_ln3_fu_294_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln37_fu_301_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln37_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_311_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln37_1_fu_321_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_287_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                bits_per_sample_1_reg_345 <= bits_per_sample_dout;
                complex_data_1_reg_340 <= complex_data_dout;
                lshr_ln_reg_360 <= payload_words_dout(15 downto 1);
                payload_words_1_reg_336 <= payload_words_dout;
                station_id_1_reg_355 <= station_id_dout;
                thread_id_1_reg_350 <= thread_id_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln37_fu_305_p2 <= std_logic_vector(unsigned(zext_ln37_fu_301_p1) + unsigned(ap_const_lv32_FC000000));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, epoch_empty_n, station_id_empty_n, thread_id_empty_n, bits_per_sample_empty_n, complex_data_empty_n, payload_words_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (payload_words_empty_n = ap_const_logic_0) or (complex_data_empty_n = ap_const_logic_0) or (bits_per_sample_empty_n = ap_const_logic_0) or (thread_id_empty_n = ap_const_logic_0) or (station_id_empty_n = ap_const_logic_0) or (epoch_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= payload_words_1_reg_336;

    bits_per_sample_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bits_per_sample_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bits_per_sample_blk_n <= bits_per_sample_empty_n;
        else 
            bits_per_sample_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bits_per_sample_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            bits_per_sample_read <= ap_const_logic_1;
        else 
            bits_per_sample_read <= ap_const_logic_0;
        end if; 
    end process;


    complex_data_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, complex_data_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            complex_data_blk_n <= complex_data_empty_n;
        else 
            complex_data_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    complex_data_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            complex_data_read <= ap_const_logic_1;
        else 
            complex_data_read <= ap_const_logic_0;
        end if; 
    end process;


    epoch_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, epoch_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            epoch_blk_n <= epoch_empty_n;
        else 
            epoch_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    epoch_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            epoch_read <= ap_const_logic_1;
        else 
            epoch_read <= ap_const_logic_0;
        end if; 
    end process;

    frame_length_fu_264_p2 <= std_logic_vector(unsigned(zext_ln28_fu_261_p1) + unsigned(ap_const_lv16_4));
    header_address0 <= header_address0_local;

    header_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            header_address0_local <= ap_const_lv64_7(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            header_address0_local <= ap_const_lv64_5(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            header_address0_local <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            header_address0_local <= ap_const_lv64_1(3 - 1 downto 0);
        else 
            header_address0_local <= "XXX";
        end if; 
    end process;

    header_address1 <= header_address1_local;

    header_address1_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            header_address1_local <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            header_address1_local <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            header_address1_local <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            header_address1_local <= ap_const_lv64_0(3 - 1 downto 0);
        else 
            header_address1_local <= "XXX";
        end if; 
    end process;

    header_ce0 <= header_ce0_local;

    header_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            header_ce0_local <= ap_const_logic_1;
        else 
            header_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    header_ce1 <= header_ce1_local;

    header_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            header_ce1_local <= ap_const_logic_1;
        else 
            header_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    header_d0 <= header_d0_local;

    header_d0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, zext_ln24_fu_246_p1, or_ln37_fu_329_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            header_d0_local <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            header_d0_local <= ap_const_lv32_ACABFEED;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            header_d0_local <= or_ln37_fu_329_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            header_d0_local <= zext_ln24_fu_246_p1;
        else 
            header_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    header_d1 <= header_d1_local;

    header_d1_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, zext_ln21_fu_233_p1, zext_ln30_fu_282_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            header_d1_local <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            header_d1_local <= ap_const_lv32_1000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            header_d1_local <= zext_ln30_fu_282_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            header_d1_local <= zext_ln21_fu_233_p1;
        else 
            header_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    header_we0 <= header_we0_local;

    header_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            header_we0_local <= ap_const_logic_1;
        else 
            header_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    header_we1 <= header_we1_local;

    header_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)))) then 
            header_we1_local <= ap_const_logic_1;
        else 
            header_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln37_1_fu_321_p4 <= ((tmp_1_fu_311_p4 & thread_id_1_reg_350) & station_id_1_reg_355);
    or_ln37_fu_329_p2 <= (shl_ln_fu_287_p3 or or_ln37_1_fu_321_p4);

    payload_words_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, payload_words_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            payload_words_blk_n <= payload_words_empty_n;
        else 
            payload_words_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    payload_words_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            payload_words_read <= ap_const_logic_1;
        else 
            payload_words_read <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln3_fu_294_p3 <= (bits_per_sample_1_reg_345 & ap_const_lv26_0);
    shl_ln_fu_287_p3 <= (complex_data_1_reg_340 & ap_const_lv31_0);

    station_id_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, station_id_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            station_id_blk_n <= station_id_empty_n;
        else 
            station_id_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    station_id_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            station_id_read <= ap_const_logic_1;
        else 
            station_id_read <= ap_const_logic_0;
        end if; 
    end process;


    thread_id_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, thread_id_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            thread_id_blk_n <= thread_id_empty_n;
        else 
            thread_id_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    thread_id_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            thread_id_read <= ap_const_logic_1;
        else 
            thread_id_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_311_p4 <= add_ln37_fu_305_p2(31 downto 26);
    tmp_fu_238_p3 <= (epoch_dout & p_read1);
    zext_ln21_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read),32));
    zext_ln24_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_238_p3),32));
    zext_ln28_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_360),16));
    zext_ln30_cast_fu_274_p3 <= (ap_const_lv1_1 & zext_ln31_fu_270_p1);
    zext_ln30_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln30_cast_fu_274_p3),32));
    zext_ln31_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(frame_length_fu_264_p2),29));
    zext_ln37_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_294_p3),32));
end behav;
