-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_packet_fsm_1 is
port (
    ap_ready : OUT STD_LOGIC;
    current_state : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of vdif_chain_packet_fsm_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal next_state_write_assign_fu_24_p6 : STD_LOGIC_VECTOR (1 downto 0);
    signal next_state_write_assign_fu_24_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal next_state_write_assign_fu_24_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal next_state_write_assign_fu_24_p3 : STD_LOGIC_VECTOR (1 downto 0);

    component vdif_chain_sparsemux_5_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    sparsemux_5_2_1_1_1_U48 : component vdif_chain_sparsemux_5_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_1,
        din1 => ap_const_lv1_1,
        def => ap_const_lv1_0,
        sel => next_state_write_assign_fu_24_p6,
        dout => next_state_write_assign_fu_24_p7);




    ap_ready <= ap_const_logic_1;
    ap_return <= next_state_write_assign_fu_24_p7;
    next_state_write_assign_fu_24_p6 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_state),2));
end behav;
