-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_entry_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    return_r : OUT STD_LOGIC_VECTOR (15 downto 0);
    epoch_dout : IN STD_LOGIC_VECTOR (5 downto 0);
    epoch_empty_n : IN STD_LOGIC;
    epoch_read : OUT STD_LOGIC;
    epoch_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    epoch_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    epoch_c_din : OUT STD_LOGIC_VECTOR (5 downto 0);
    epoch_c_full_n : IN STD_LOGIC;
    epoch_c_write : OUT STD_LOGIC;
    epoch_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    epoch_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    station_id_empty_n : IN STD_LOGIC;
    station_id_read : OUT STD_LOGIC;
    station_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    station_id_c_full_n : IN STD_LOGIC;
    station_id_c_write : OUT STD_LOGIC;
    station_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    thread_id_empty_n : IN STD_LOGIC;
    thread_id_read : OUT STD_LOGIC;
    thread_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    thread_id_c_full_n : IN STD_LOGIC;
    thread_id_c_write : OUT STD_LOGIC;
    thread_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_dout : IN STD_LOGIC_VECTOR (4 downto 0);
    bits_per_sample_empty_n : IN STD_LOGIC;
    bits_per_sample_read : OUT STD_LOGIC;
    bits_per_sample_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_c_din : OUT STD_LOGIC_VECTOR (4 downto 0);
    bits_per_sample_c_full_n : IN STD_LOGIC;
    bits_per_sample_c_write : OUT STD_LOGIC;
    bits_per_sample_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    complex_data_empty_n : IN STD_LOGIC;
    complex_data_read : OUT STD_LOGIC;
    complex_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    complex_data_c_full_n : IN STD_LOGIC;
    complex_data_c_write : OUT STD_LOGIC;
    complex_data_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    payload_words_empty_n : IN STD_LOGIC;
    payload_words_read : OUT STD_LOGIC;
    payload_words_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_c1_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    payload_words_c1_full_n : IN STD_LOGIC;
    payload_words_c1_write : OUT STD_LOGIC;
    payload_words_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of vdif_chain_entry_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal epoch_blk_n : STD_LOGIC;
    signal epoch_c_blk_n : STD_LOGIC;
    signal station_id_blk_n : STD_LOGIC;
    signal station_id_c_blk_n : STD_LOGIC;
    signal thread_id_blk_n : STD_LOGIC;
    signal thread_id_c_blk_n : STD_LOGIC;
    signal bits_per_sample_blk_n : STD_LOGIC;
    signal bits_per_sample_c_blk_n : STD_LOGIC;
    signal complex_data_blk_n : STD_LOGIC;
    signal complex_data_c_blk_n : STD_LOGIC;
    signal payload_words_blk_n : STD_LOGIC;
    signal payload_words_c1_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal return_r_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    return_r_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                return_r_preg <= ap_const_lv16_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                    return_r_preg <= payload_words_dout;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, epoch_empty_n, epoch_c_full_n, station_id_empty_n, station_id_c_full_n, thread_id_empty_n, thread_id_c_full_n, bits_per_sample_empty_n, bits_per_sample_c_full_n, complex_data_empty_n, complex_data_c_full_n, payload_words_empty_n, payload_words_c1_full_n)
    begin
                ap_block_state1 <= ((payload_words_c1_full_n = ap_const_logic_0) or (payload_words_empty_n = ap_const_logic_0) or (complex_data_c_full_n = ap_const_logic_0) or (complex_data_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (bits_per_sample_c_full_n = ap_const_logic_0) or (bits_per_sample_empty_n = ap_const_logic_0) or (thread_id_c_full_n = ap_const_logic_0) or (thread_id_empty_n = ap_const_logic_0) or (station_id_c_full_n = ap_const_logic_0) or (station_id_empty_n = ap_const_logic_0) or (epoch_c_full_n = ap_const_logic_0) or (epoch_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bits_per_sample_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bits_per_sample_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bits_per_sample_blk_n <= bits_per_sample_empty_n;
        else 
            bits_per_sample_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bits_per_sample_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bits_per_sample_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bits_per_sample_c_blk_n <= bits_per_sample_c_full_n;
        else 
            bits_per_sample_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bits_per_sample_c_din <= bits_per_sample_dout;

    bits_per_sample_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            bits_per_sample_c_write <= ap_const_logic_1;
        else 
            bits_per_sample_c_write <= ap_const_logic_0;
        end if; 
    end process;


    bits_per_sample_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            bits_per_sample_read <= ap_const_logic_1;
        else 
            bits_per_sample_read <= ap_const_logic_0;
        end if; 
    end process;


    complex_data_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, complex_data_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            complex_data_blk_n <= complex_data_empty_n;
        else 
            complex_data_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    complex_data_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, complex_data_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            complex_data_c_blk_n <= complex_data_c_full_n;
        else 
            complex_data_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    complex_data_c_din <= complex_data_dout;

    complex_data_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            complex_data_c_write <= ap_const_logic_1;
        else 
            complex_data_c_write <= ap_const_logic_0;
        end if; 
    end process;


    complex_data_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            complex_data_read <= ap_const_logic_1;
        else 
            complex_data_read <= ap_const_logic_0;
        end if; 
    end process;


    epoch_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, epoch_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            epoch_blk_n <= epoch_empty_n;
        else 
            epoch_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    epoch_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, epoch_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            epoch_c_blk_n <= epoch_c_full_n;
        else 
            epoch_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    epoch_c_din <= epoch_dout;

    epoch_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            epoch_c_write <= ap_const_logic_1;
        else 
            epoch_c_write <= ap_const_logic_0;
        end if; 
    end process;


    epoch_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            epoch_read <= ap_const_logic_1;
        else 
            epoch_read <= ap_const_logic_0;
        end if; 
    end process;


    payload_words_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, payload_words_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            payload_words_blk_n <= payload_words_empty_n;
        else 
            payload_words_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    payload_words_c1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, payload_words_c1_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            payload_words_c1_blk_n <= payload_words_c1_full_n;
        else 
            payload_words_c1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    payload_words_c1_din <= payload_words_dout;

    payload_words_c1_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            payload_words_c1_write <= ap_const_logic_1;
        else 
            payload_words_c1_write <= ap_const_logic_0;
        end if; 
    end process;


    payload_words_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            payload_words_read <= ap_const_logic_1;
        else 
            payload_words_read <= ap_const_logic_0;
        end if; 
    end process;


    return_r_assign_proc : process(ap_CS_fsm_state1, payload_words_dout, ap_block_state1, return_r_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            return_r <= payload_words_dout;
        else 
            return_r <= return_r_preg;
        end if; 
    end process;


    station_id_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, station_id_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            station_id_blk_n <= station_id_empty_n;
        else 
            station_id_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    station_id_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, station_id_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            station_id_c_blk_n <= station_id_c_full_n;
        else 
            station_id_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    station_id_c_din <= station_id_dout;

    station_id_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            station_id_c_write <= ap_const_logic_1;
        else 
            station_id_c_write <= ap_const_logic_0;
        end if; 
    end process;


    station_id_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            station_id_read <= ap_const_logic_1;
        else 
            station_id_read <= ap_const_logic_0;
        end if; 
    end process;


    thread_id_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, thread_id_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            thread_id_blk_n <= thread_id_empty_n;
        else 
            thread_id_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    thread_id_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, thread_id_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            thread_id_c_blk_n <= thread_id_c_full_n;
        else 
            thread_id_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    thread_id_c_din <= thread_id_dout;

    thread_id_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            thread_id_c_write <= ap_const_logic_1;
        else 
            thread_id_c_write <= ap_const_logic_0;
        end if; 
    end process;


    thread_id_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            thread_id_read <= ap_const_logic_1;
        else 
            thread_id_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
