-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_Loop_VITIS_LOOP_71_1_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    payload_words : IN STD_LOGIC_VECTOR (15 downto 0);
    adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    adc_in_TVALID : IN STD_LOGIC;
    adc_in_TREADY : OUT STD_LOGIC;
    bits_per_sample : IN STD_LOGIC_VECTOR (4 downto 0);
    packetizer_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    packetizer_in_full_n : IN STD_LOGIC;
    packetizer_in_write : OUT STD_LOGIC;
    packetizer_in_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
    packetizer_in_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
    bits_per_sample_c_din : OUT STD_LOGIC_VECTOR (4 downto 0);
    bits_per_sample_c_full_n : IN STD_LOGIC;
    bits_per_sample_c_write : OUT STD_LOGIC;
    bits_per_sample_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bits_per_sample_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    payload_words_c_full_n : IN STD_LOGIC;
    payload_words_c_write : OUT STD_LOGIC;
    payload_words_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    payload_words_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of vdif_chain_Loop_VITIS_LOOP_71_1_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal packetizer_in_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal bits_per_sample_c_blk_n : STD_LOGIC;
    signal payload_words_c_blk_n : STD_LOGIC;
    signal bits_per_sample_read_reg_166 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal payload_words_read_reg_171 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_sample_packer_fu_127_ap_start : STD_LOGIC;
    signal grp_sample_packer_fu_127_ap_done : STD_LOGIC;
    signal grp_sample_packer_fu_127_ap_idle : STD_LOGIC;
    signal grp_sample_packer_fu_127_ap_ready : STD_LOGIC;
    signal grp_sample_packer_fu_127_adc_in_TREADY : STD_LOGIC;
    signal grp_sample_packer_fu_127_packed_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sample_packer_fu_127_packed_stream_write : STD_LOGIC;
    signal grp_sample_packer_fu_127_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln71_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal packed_stream_full_n : STD_LOGIC;
    signal packed_stream_write : STD_LOGIC;
    signal i_fu_78 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal i_11_fu_148_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal packed_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal packed_stream_empty_n : STD_LOGIC;
    signal packed_stream_read : STD_LOGIC;
    signal ap_block_state4 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_adc_in_U_apdone_blk : STD_LOGIC;
    signal adc_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal adc_in_TVALID_int_regslice : STD_LOGIC;
    signal adc_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_adc_in_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_sample_packer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        adc_in_TVALID : IN STD_LOGIC;
        adc_in_TREADY : OUT STD_LOGIC;
        packed_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        packed_stream_full_n : IN STD_LOGIC;
        packed_stream_write : OUT STD_LOGIC;
        bits_per_sample : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component vdif_chain_fifo_w32_d2048_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vdif_chain_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_sample_packer_fu_127 : component vdif_chain_sample_packer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sample_packer_fu_127_ap_start,
        ap_done => grp_sample_packer_fu_127_ap_done,
        ap_idle => grp_sample_packer_fu_127_ap_idle,
        ap_ready => grp_sample_packer_fu_127_ap_ready,
        adc_in_TDATA => adc_in_TDATA_int_regslice,
        adc_in_TVALID => adc_in_TVALID_int_regslice,
        adc_in_TREADY => grp_sample_packer_fu_127_adc_in_TREADY,
        packed_stream_din => grp_sample_packer_fu_127_packed_stream_din,
        packed_stream_full_n => packed_stream_full_n,
        packed_stream_write => grp_sample_packer_fu_127_packed_stream_write,
        bits_per_sample => bits_per_sample_read_reg_166);

    packed_stream_fifo_U : component vdif_chain_fifo_w32_d2048_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_sample_packer_fu_127_packed_stream_din,
        if_full_n => packed_stream_full_n,
        if_write => packed_stream_write,
        if_dout => packed_stream_dout,
        if_empty_n => packed_stream_empty_n,
        if_read => packed_stream_read);

    regslice_both_adc_in_U : component vdif_chain_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => adc_in_TDATA,
        vld_in => adc_in_TVALID,
        ack_in => regslice_both_adc_in_U_ack_in,
        data_out => adc_in_TDATA_int_regslice,
        vld_out => adc_in_TVALID_int_regslice,
        ack_out => adc_in_TREADY_int_regslice,
        apdone_blk => regslice_both_adc_in_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln71_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_sample_packer_fu_127_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sample_packer_fu_127_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln71_fu_143_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_sample_packer_fu_127_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sample_packer_fu_127_ap_ready = ap_const_logic_1)) then 
                    grp_sample_packer_fu_127_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_78 <= ap_const_lv16_0;
            elsif (((icmp_ln71_fu_143_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_78 <= i_11_fu_148_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                bits_per_sample_read_reg_166 <= bits_per_sample;
                payload_words_read_reg_171 <= payload_words;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_block_state1, grp_sample_packer_fu_127_ap_done, ap_CS_fsm_state2, icmp_ln71_fu_143_p2, ap_CS_fsm_state3, ap_block_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln71_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_sample_packer_fu_127_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    adc_in_TREADY <= regslice_both_adc_in_U_ack_in;

    adc_in_TREADY_int_regslice_assign_proc : process(grp_sample_packer_fu_127_adc_in_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            adc_in_TREADY_int_regslice <= grp_sample_packer_fu_127_adc_in_TREADY;
        else 
            adc_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_sample_packer_fu_127_ap_done)
    begin
        if ((grp_sample_packer_fu_127_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, bits_per_sample_c_full_n, payload_words_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (payload_words_c_full_n = ap_const_logic_0) or (bits_per_sample_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state4_assign_proc : process(packetizer_in_full_n, packed_stream_empty_n)
    begin
                ap_block_state4 <= ((packetizer_in_full_n = ap_const_logic_0) or (packed_stream_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln71_fu_143_p2)
    begin
        if (((icmp_ln71_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln71_fu_143_p2)
    begin
        if (((icmp_ln71_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bits_per_sample_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bits_per_sample_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bits_per_sample_c_blk_n <= bits_per_sample_c_full_n;
        else 
            bits_per_sample_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bits_per_sample_c_din <= bits_per_sample;

    bits_per_sample_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bits_per_sample_c_write <= ap_const_logic_1;
        else 
            bits_per_sample_c_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_sample_packer_fu_127_ap_start <= grp_sample_packer_fu_127_ap_start_reg;
    i_11_fu_148_p2 <= std_logic_vector(unsigned(i_fu_78) + unsigned(ap_const_lv16_1));
    icmp_ln71_fu_143_p2 <= "1" when (i_fu_78 = payload_words_read_reg_171) else "0";

    packed_stream_read_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            packed_stream_read <= ap_const_logic_1;
        else 
            packed_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    packed_stream_write_assign_proc : process(grp_sample_packer_fu_127_packed_stream_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            packed_stream_write <= grp_sample_packer_fu_127_packed_stream_write;
        else 
            packed_stream_write <= ap_const_logic_0;
        end if; 
    end process;


    packetizer_in_blk_n_assign_proc : process(packetizer_in_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            packetizer_in_blk_n <= packetizer_in_full_n;
        else 
            packetizer_in_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    packetizer_in_din <= packed_stream_dout;

    packetizer_in_write_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            packetizer_in_write <= ap_const_logic_1;
        else 
            packetizer_in_write <= ap_const_logic_0;
        end if; 
    end process;


    payload_words_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, payload_words_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            payload_words_c_blk_n <= payload_words_c_full_n;
        else 
            payload_words_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    payload_words_c_din <= payload_words;

    payload_words_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            payload_words_c_write <= ap_const_logic_1;
        else 
            payload_words_c_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
