-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    header_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    header_ce0 : OUT STD_LOGIC;
    header_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    fifo_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifo_empty_n : IN STD_LOGIC;
    fifo_read : OUT STD_LOGIC;
    fifo_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
    fifo_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
    p_read : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_read_1_reg_79 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_write_header_fu_50_ap_done : STD_LOGIC;
    signal grp_write_header_fu_50_ap_start : STD_LOGIC;
    signal grp_write_header_fu_50_ap_idle : STD_LOGIC;
    signal grp_write_header_fu_50_ap_ready : STD_LOGIC;
    signal grp_write_header_fu_50_out_stream_TREADY : STD_LOGIC;
    signal grp_write_header_fu_50_header_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_header_fu_50_header_ce0 : STD_LOGIC;
    signal grp_write_header_fu_50_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_header_fu_50_out_stream_TVALID : STD_LOGIC;
    signal grp_write_header_fu_50_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_header_fu_50_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_header_fu_50_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_payload_fu_64_ap_start : STD_LOGIC;
    signal grp_write_payload_fu_64_ap_done : STD_LOGIC;
    signal grp_write_payload_fu_64_ap_idle : STD_LOGIC;
    signal grp_write_payload_fu_64_ap_ready : STD_LOGIC;
    signal grp_write_payload_fu_64_fifo_read : STD_LOGIC;
    signal grp_write_payload_fu_64_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_payload_fu_64_out_stream_TVALID : STD_LOGIC;
    signal grp_write_payload_fu_64_out_stream_TREADY : STD_LOGIC;
    signal grp_write_payload_fu_64_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_payload_fu_64_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_payload_fu_64_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_header_fu_50_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call5 : BOOLEAN;
    signal out_stream_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_stream_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_stream_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_payload_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_write_header IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        header_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        header_ce0 : OUT STD_LOGIC;
        header_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component vdif_chain_write_payload IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fifo_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fifo_empty_n : IN STD_LOGIC;
        fifo_read : OUT STD_LOGIC;
        fifo_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
        fifo_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        payload_words : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component vdif_chain_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_write_header_fu_50 : component vdif_chain_write_header
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_header_fu_50_ap_start,
        ap_done => grp_write_header_fu_50_ap_done,
        ap_idle => grp_write_header_fu_50_ap_idle,
        ap_ready => grp_write_header_fu_50_ap_ready,
        out_stream_TREADY => grp_write_header_fu_50_out_stream_TREADY,
        header_address0 => grp_write_header_fu_50_header_address0,
        header_ce0 => grp_write_header_fu_50_header_ce0,
        header_q0 => header_q0,
        out_stream_TDATA => grp_write_header_fu_50_out_stream_TDATA,
        out_stream_TVALID => grp_write_header_fu_50_out_stream_TVALID,
        out_stream_TKEEP => grp_write_header_fu_50_out_stream_TKEEP,
        out_stream_TSTRB => grp_write_header_fu_50_out_stream_TSTRB,
        out_stream_TLAST => grp_write_header_fu_50_out_stream_TLAST);

    grp_write_payload_fu_64 : component vdif_chain_write_payload
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_payload_fu_64_ap_start,
        ap_done => grp_write_payload_fu_64_ap_done,
        ap_idle => grp_write_payload_fu_64_ap_idle,
        ap_ready => grp_write_payload_fu_64_ap_ready,
        fifo_dout => fifo_dout,
        fifo_empty_n => fifo_empty_n,
        fifo_read => grp_write_payload_fu_64_fifo_read,
        fifo_num_data_valid => ap_const_lv14_0,
        fifo_fifo_cap => ap_const_lv14_0,
        out_stream_TDATA => grp_write_payload_fu_64_out_stream_TDATA,
        out_stream_TVALID => grp_write_payload_fu_64_out_stream_TVALID,
        out_stream_TREADY => grp_write_payload_fu_64_out_stream_TREADY,
        out_stream_TKEEP => grp_write_payload_fu_64_out_stream_TKEEP,
        out_stream_TSTRB => grp_write_payload_fu_64_out_stream_TSTRB,
        out_stream_TLAST => grp_write_payload_fu_64_out_stream_TLAST,
        payload_words => p_read_1_reg_79);

    regslice_both_out_stream_V_data_V_U : component vdif_chain_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component vdif_chain_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => out_stream_TKEEP_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component vdif_chain_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => out_stream_TSTRB_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component vdif_chain_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => out_stream_TLAST_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_write_header_fu_50_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_header_fu_50_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call5) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_write_header_fu_50_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_header_fu_50_ap_ready = ap_const_logic_1)) then 
                    grp_write_header_fu_50_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_write_payload_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_payload_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_write_payload_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_payload_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_write_payload_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    out_stream_TDATA_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                out_stream_TDATA_reg <= grp_write_payload_fu_64_out_stream_TDATA;
            elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                out_stream_TDATA_reg <= grp_write_header_fu_50_out_stream_TDATA;
            end if; 
        end if;
    end process;

    out_stream_TKEEP_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                out_stream_TKEEP_reg <= grp_write_payload_fu_64_out_stream_TKEEP;
            elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                out_stream_TKEEP_reg <= grp_write_header_fu_50_out_stream_TKEEP;
            end if; 
        end if;
    end process;

    out_stream_TLAST_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                out_stream_TLAST_reg <= grp_write_payload_fu_64_out_stream_TLAST;
            elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                out_stream_TLAST_reg <= grp_write_header_fu_50_out_stream_TLAST;
            end if; 
        end if;
    end process;

    out_stream_TSTRB_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                out_stream_TSTRB_reg <= grp_write_payload_fu_64_out_stream_TSTRB;
            elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                out_stream_TSTRB_reg <= grp_write_header_fu_50_out_stream_TSTRB;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_write_header_fu_50_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                p_read_1_reg_79 <= p_read;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_write_header_fu_50_ap_done, grp_write_payload_fu_64_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_write_header_fu_50_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_write_payload_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_write_header_fu_50_ap_done)
    begin
        if ((grp_write_header_fu_50_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_write_payload_fu_64_ap_done)
    begin
        if ((grp_write_payload_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call5_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call5 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    fifo_read <= grp_write_payload_fu_64_fifo_read;
    grp_write_header_fu_50_ap_start <= grp_write_header_fu_50_ap_start_reg;
    grp_write_header_fu_50_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_write_payload_fu_64_ap_start <= grp_write_payload_fu_64_ap_start_reg;
    grp_write_payload_fu_64_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state4);
    header_address0 <= grp_write_header_fu_50_header_address0;
    header_ce0 <= grp_write_header_fu_50_header_ce0;

    out_stream_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_write_header_fu_50_out_stream_TDATA, grp_write_header_fu_50_out_stream_TVALID, grp_write_payload_fu_64_out_stream_TDATA, grp_write_payload_fu_64_out_stream_TVALID, out_stream_TDATA_reg, ap_CS_fsm_state4)
    begin
        if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_stream_TDATA_int_regslice <= grp_write_payload_fu_64_out_stream_TDATA;
        elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TDATA_int_regslice <= grp_write_header_fu_50_out_stream_TDATA;
        else 
            out_stream_TDATA_int_regslice <= out_stream_TDATA_reg;
        end if; 
    end process;


    out_stream_TKEEP_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_write_header_fu_50_out_stream_TVALID, grp_write_header_fu_50_out_stream_TKEEP, grp_write_payload_fu_64_out_stream_TVALID, grp_write_payload_fu_64_out_stream_TKEEP, out_stream_TKEEP_reg, ap_CS_fsm_state4)
    begin
        if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_stream_TKEEP_int_regslice <= grp_write_payload_fu_64_out_stream_TKEEP;
        elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TKEEP_int_regslice <= grp_write_header_fu_50_out_stream_TKEEP;
        else 
            out_stream_TKEEP_int_regslice <= out_stream_TKEEP_reg;
        end if; 
    end process;


    out_stream_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_write_header_fu_50_out_stream_TVALID, grp_write_header_fu_50_out_stream_TLAST, grp_write_payload_fu_64_out_stream_TVALID, grp_write_payload_fu_64_out_stream_TLAST, out_stream_TLAST_reg, ap_CS_fsm_state4)
    begin
        if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_stream_TLAST_int_regslice <= grp_write_payload_fu_64_out_stream_TLAST;
        elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TLAST_int_regslice <= grp_write_header_fu_50_out_stream_TLAST;
        else 
            out_stream_TLAST_int_regslice <= out_stream_TLAST_reg;
        end if; 
    end process;


    out_stream_TSTRB_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_write_header_fu_50_out_stream_TVALID, grp_write_header_fu_50_out_stream_TSTRB, grp_write_payload_fu_64_out_stream_TVALID, grp_write_payload_fu_64_out_stream_TSTRB, out_stream_TSTRB_reg, ap_CS_fsm_state4)
    begin
        if (((grp_write_payload_fu_64_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_stream_TSTRB_int_regslice <= grp_write_payload_fu_64_out_stream_TSTRB;
        elsif (((grp_write_header_fu_50_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TSTRB_int_regslice <= grp_write_header_fu_50_out_stream_TSTRB;
        else 
            out_stream_TSTRB_int_regslice <= out_stream_TSTRB_reg;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state2, grp_write_header_fu_50_out_stream_TVALID, grp_write_payload_fu_64_out_stream_TVALID, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_stream_TVALID_int_regslice <= grp_write_payload_fu_64_out_stream_TVALID;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_stream_TVALID_int_regslice <= grp_write_header_fu_50_out_stream_TVALID;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
