-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain is
port (
    adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    epoch : IN STD_LOGIC_VECTOR (5 downto 0);
    station_id : IN STD_LOGIC_VECTOR (15 downto 0);
    thread_id : IN STD_LOGIC_VECTOR (9 downto 0);
    bits_per_sample : IN STD_LOGIC_VECTOR (4 downto 0);
    complex_data : IN STD_LOGIC_VECTOR (0 downto 0);
    pps : IN STD_LOGIC_VECTOR (0 downto 0);
    payload_words : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    adc_in_TVALID : IN STD_LOGIC;
    adc_in_TREADY : OUT STD_LOGIC;
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of vdif_chain is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "vdif_chain_vdif_chain,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12t-cpg238-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.406000,HLS_SYN_LAT=589807,HLS_SYN_TPT=589808,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=2859,HLS_SYN_LUT=3230,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal entry_proc7_U0_ap_start : STD_LOGIC;
    signal entry_proc7_U0_ap_done : STD_LOGIC;
    signal entry_proc7_U0_ap_continue : STD_LOGIC;
    signal entry_proc7_U0_ap_idle : STD_LOGIC;
    signal entry_proc7_U0_ap_ready : STD_LOGIC;
    signal entry_proc7_U0_start_out : STD_LOGIC;
    signal entry_proc7_U0_start_write : STD_LOGIC;
    signal entry_proc7_U0_epoch_c_din : STD_LOGIC_VECTOR (5 downto 0);
    signal entry_proc7_U0_epoch_c_write : STD_LOGIC;
    signal entry_proc7_U0_station_id_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc7_U0_station_id_c_write : STD_LOGIC;
    signal entry_proc7_U0_thread_id_c_din : STD_LOGIC_VECTOR (9 downto 0);
    signal entry_proc7_U0_thread_id_c_write : STD_LOGIC;
    signal entry_proc7_U0_complex_data_c_din : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc7_U0_complex_data_c_write : STD_LOGIC;
    signal entry_proc7_U0_pps_c_din : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc7_U0_pps_c_write : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_ap_start : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_ap_done : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_adc_in_TREADY : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_write : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_din : STD_LOGIC_VECTOR (4 downto 0);
    signal Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_write : STD_LOGIC;
    signal Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_write : STD_LOGIC;
    signal packetizer_U0_packetizer_in_read : STD_LOGIC;
    signal packetizer_U0_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal packetizer_U0_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal packetizer_U0_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal packetizer_U0_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal packetizer_U0_epoch_read : STD_LOGIC;
    signal packetizer_U0_station_id_read : STD_LOGIC;
    signal packetizer_U0_thread_id_read : STD_LOGIC;
    signal packetizer_U0_bits_per_sample_read : STD_LOGIC;
    signal packetizer_U0_complex_data_read : STD_LOGIC;
    signal packetizer_U0_pps_read : STD_LOGIC;
    signal packetizer_U0_payload_words_read : STD_LOGIC;
    signal packetizer_U0_ap_start : STD_LOGIC;
    signal packetizer_U0_ap_done : STD_LOGIC;
    signal packetizer_U0_out_stream_TVALID : STD_LOGIC;
    signal packetizer_U0_ap_ready : STD_LOGIC;
    signal packetizer_U0_ap_idle : STD_LOGIC;
    signal packetizer_U0_ap_continue : STD_LOGIC;
    signal epoch_c_full_n : STD_LOGIC;
    signal epoch_c_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal epoch_c_empty_n : STD_LOGIC;
    signal epoch_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal epoch_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal station_id_c_full_n : STD_LOGIC;
    signal station_id_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal station_id_c_empty_n : STD_LOGIC;
    signal station_id_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal station_id_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal thread_id_c_full_n : STD_LOGIC;
    signal thread_id_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal thread_id_c_empty_n : STD_LOGIC;
    signal thread_id_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal thread_id_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal complex_data_c_full_n : STD_LOGIC;
    signal complex_data_c_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal complex_data_c_empty_n : STD_LOGIC;
    signal complex_data_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal complex_data_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pps_c_full_n : STD_LOGIC;
    signal pps_c_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal pps_c_empty_n : STD_LOGIC;
    signal pps_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pps_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal packetizer_in_full_n : STD_LOGIC;
    signal packetizer_in_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal packetizer_in_empty_n : STD_LOGIC;
    signal packetizer_in_num_data_valid : STD_LOGIC_VECTOR (11 downto 0);
    signal packetizer_in_fifo_cap : STD_LOGIC_VECTOR (11 downto 0);
    signal bits_per_sample_c_full_n : STD_LOGIC;
    signal bits_per_sample_c_dout : STD_LOGIC_VECTOR (4 downto 0);
    signal bits_per_sample_c_empty_n : STD_LOGIC;
    signal bits_per_sample_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal bits_per_sample_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal payload_words_c_full_n : STD_LOGIC;
    signal payload_words_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal payload_words_c_empty_n : STD_LOGIC;
    signal payload_words_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal payload_words_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc7_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc7_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready : STD_LOGIC;
    signal start_for_packetizer_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_packetizer_U0_full_n : STD_LOGIC;
    signal start_for_packetizer_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_packetizer_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_entry_proc7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        epoch : IN STD_LOGIC_VECTOR (5 downto 0);
        epoch_c_din : OUT STD_LOGIC_VECTOR (5 downto 0);
        epoch_c_full_n : IN STD_LOGIC;
        epoch_c_write : OUT STD_LOGIC;
        epoch_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        epoch_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id : IN STD_LOGIC_VECTOR (15 downto 0);
        station_id_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        station_id_c_full_n : IN STD_LOGIC;
        station_id_c_write : OUT STD_LOGIC;
        station_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id : IN STD_LOGIC_VECTOR (9 downto 0);
        thread_id_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        thread_id_c_full_n : IN STD_LOGIC;
        thread_id_c_write : OUT STD_LOGIC;
        thread_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data : IN STD_LOGIC_VECTOR (0 downto 0);
        complex_data_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        complex_data_c_full_n : IN STD_LOGIC;
        complex_data_c_write : OUT STD_LOGIC;
        complex_data_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        pps : IN STD_LOGIC_VECTOR (0 downto 0);
        pps_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        pps_c_full_n : IN STD_LOGIC;
        pps_c_write : OUT STD_LOGIC;
        pps_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        pps_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_Loop_VITIS_LOOP_71_1_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        payload_words : IN STD_LOGIC_VECTOR (15 downto 0);
        adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        adc_in_TVALID : IN STD_LOGIC;
        adc_in_TREADY : OUT STD_LOGIC;
        bits_per_sample : IN STD_LOGIC_VECTOR (4 downto 0);
        packetizer_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        packetizer_in_full_n : IN STD_LOGIC;
        packetizer_in_write : OUT STD_LOGIC;
        packetizer_in_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
        packetizer_in_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
        bits_per_sample_c_din : OUT STD_LOGIC_VECTOR (4 downto 0);
        bits_per_sample_c_full_n : IN STD_LOGIC;
        bits_per_sample_c_write : OUT STD_LOGIC;
        bits_per_sample_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        payload_words_c_full_n : IN STD_LOGIC;
        payload_words_c_write : OUT STD_LOGIC;
        payload_words_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_packetizer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        packetizer_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        packetizer_in_empty_n : IN STD_LOGIC;
        packetizer_in_read : OUT STD_LOGIC;
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        epoch_dout : IN STD_LOGIC_VECTOR (5 downto 0);
        epoch_empty_n : IN STD_LOGIC;
        epoch_read : OUT STD_LOGIC;
        station_id_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        station_id_empty_n : IN STD_LOGIC;
        station_id_read : OUT STD_LOGIC;
        thread_id_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        thread_id_empty_n : IN STD_LOGIC;
        thread_id_read : OUT STD_LOGIC;
        bits_per_sample_dout : IN STD_LOGIC_VECTOR (4 downto 0);
        bits_per_sample_empty_n : IN STD_LOGIC;
        bits_per_sample_read : OUT STD_LOGIC;
        complex_data_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        complex_data_empty_n : IN STD_LOGIC;
        complex_data_read : OUT STD_LOGIC;
        pps_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        pps_empty_n : IN STD_LOGIC;
        pps_read : OUT STD_LOGIC;
        payload_words_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        payload_words_empty_n : IN STD_LOGIC;
        payload_words_read : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component vdif_chain_fifo_w6_d3_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (5 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w16_d3_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w10_d3_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (9 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w1_d3_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w32_d2048_A_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component vdif_chain_fifo_w5_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (4 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w16_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_start_for_packetizer_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc7_U0 : component vdif_chain_entry_proc7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc7_U0_ap_start,
        start_full_n => start_for_packetizer_U0_full_n,
        ap_done => entry_proc7_U0_ap_done,
        ap_continue => entry_proc7_U0_ap_continue,
        ap_idle => entry_proc7_U0_ap_idle,
        ap_ready => entry_proc7_U0_ap_ready,
        start_out => entry_proc7_U0_start_out,
        start_write => entry_proc7_U0_start_write,
        epoch => epoch,
        epoch_c_din => entry_proc7_U0_epoch_c_din,
        epoch_c_full_n => epoch_c_full_n,
        epoch_c_write => entry_proc7_U0_epoch_c_write,
        epoch_c_num_data_valid => epoch_c_num_data_valid,
        epoch_c_fifo_cap => epoch_c_fifo_cap,
        station_id => station_id,
        station_id_c_din => entry_proc7_U0_station_id_c_din,
        station_id_c_full_n => station_id_c_full_n,
        station_id_c_write => entry_proc7_U0_station_id_c_write,
        station_id_c_num_data_valid => station_id_c_num_data_valid,
        station_id_c_fifo_cap => station_id_c_fifo_cap,
        thread_id => thread_id,
        thread_id_c_din => entry_proc7_U0_thread_id_c_din,
        thread_id_c_full_n => thread_id_c_full_n,
        thread_id_c_write => entry_proc7_U0_thread_id_c_write,
        thread_id_c_num_data_valid => thread_id_c_num_data_valid,
        thread_id_c_fifo_cap => thread_id_c_fifo_cap,
        complex_data => complex_data,
        complex_data_c_din => entry_proc7_U0_complex_data_c_din,
        complex_data_c_full_n => complex_data_c_full_n,
        complex_data_c_write => entry_proc7_U0_complex_data_c_write,
        complex_data_c_num_data_valid => complex_data_c_num_data_valid,
        complex_data_c_fifo_cap => complex_data_c_fifo_cap,
        pps => pps,
        pps_c_din => entry_proc7_U0_pps_c_din,
        pps_c_full_n => pps_c_full_n,
        pps_c_write => entry_proc7_U0_pps_c_write,
        pps_c_num_data_valid => pps_c_num_data_valid,
        pps_c_fifo_cap => pps_c_fifo_cap);

    Loop_VITIS_LOOP_71_1_proc_U0 : component vdif_chain_Loop_VITIS_LOOP_71_1_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_VITIS_LOOP_71_1_proc_U0_ap_start,
        ap_done => Loop_VITIS_LOOP_71_1_proc_U0_ap_done,
        ap_continue => Loop_VITIS_LOOP_71_1_proc_U0_ap_continue,
        ap_idle => Loop_VITIS_LOOP_71_1_proc_U0_ap_idle,
        ap_ready => Loop_VITIS_LOOP_71_1_proc_U0_ap_ready,
        payload_words => payload_words,
        adc_in_TDATA => adc_in_TDATA,
        adc_in_TVALID => adc_in_TVALID,
        adc_in_TREADY => Loop_VITIS_LOOP_71_1_proc_U0_adc_in_TREADY,
        bits_per_sample => bits_per_sample,
        packetizer_in_din => Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_din,
        packetizer_in_full_n => packetizer_in_full_n,
        packetizer_in_write => Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_write,
        packetizer_in_num_data_valid => packetizer_in_num_data_valid,
        packetizer_in_fifo_cap => packetizer_in_fifo_cap,
        bits_per_sample_c_din => Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_din,
        bits_per_sample_c_full_n => bits_per_sample_c_full_n,
        bits_per_sample_c_write => Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_write,
        bits_per_sample_c_num_data_valid => bits_per_sample_c_num_data_valid,
        bits_per_sample_c_fifo_cap => bits_per_sample_c_fifo_cap,
        payload_words_c_din => Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_din,
        payload_words_c_full_n => payload_words_c_full_n,
        payload_words_c_write => Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_write,
        payload_words_c_num_data_valid => payload_words_c_num_data_valid,
        payload_words_c_fifo_cap => payload_words_c_fifo_cap);

    packetizer_U0 : component vdif_chain_packetizer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        packetizer_in_dout => packetizer_in_dout,
        packetizer_in_empty_n => packetizer_in_empty_n,
        packetizer_in_read => packetizer_U0_packetizer_in_read,
        out_stream_TDATA => packetizer_U0_out_stream_TDATA,
        out_stream_TKEEP => packetizer_U0_out_stream_TKEEP,
        out_stream_TSTRB => packetizer_U0_out_stream_TSTRB,
        out_stream_TLAST => packetizer_U0_out_stream_TLAST,
        epoch_dout => epoch_c_dout,
        epoch_empty_n => epoch_c_empty_n,
        epoch_read => packetizer_U0_epoch_read,
        station_id_dout => station_id_c_dout,
        station_id_empty_n => station_id_c_empty_n,
        station_id_read => packetizer_U0_station_id_read,
        thread_id_dout => thread_id_c_dout,
        thread_id_empty_n => thread_id_c_empty_n,
        thread_id_read => packetizer_U0_thread_id_read,
        bits_per_sample_dout => bits_per_sample_c_dout,
        bits_per_sample_empty_n => bits_per_sample_c_empty_n,
        bits_per_sample_read => packetizer_U0_bits_per_sample_read,
        complex_data_dout => complex_data_c_dout,
        complex_data_empty_n => complex_data_c_empty_n,
        complex_data_read => packetizer_U0_complex_data_read,
        pps_dout => pps_c_dout,
        pps_empty_n => pps_c_empty_n,
        pps_read => packetizer_U0_pps_read,
        payload_words_dout => payload_words_c_dout,
        payload_words_empty_n => payload_words_c_empty_n,
        payload_words_read => packetizer_U0_payload_words_read,
        ap_start => packetizer_U0_ap_start,
        ap_done => packetizer_U0_ap_done,
        out_stream_TVALID => packetizer_U0_out_stream_TVALID,
        out_stream_TREADY => out_stream_TREADY,
        ap_ready => packetizer_U0_ap_ready,
        ap_idle => packetizer_U0_ap_idle,
        ap_continue => packetizer_U0_ap_continue);

    epoch_c_U : component vdif_chain_fifo_w6_d3_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc7_U0_epoch_c_din,
        if_full_n => epoch_c_full_n,
        if_write => entry_proc7_U0_epoch_c_write,
        if_dout => epoch_c_dout,
        if_empty_n => epoch_c_empty_n,
        if_read => packetizer_U0_epoch_read,
        if_num_data_valid => epoch_c_num_data_valid,
        if_fifo_cap => epoch_c_fifo_cap);

    station_id_c_U : component vdif_chain_fifo_w16_d3_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc7_U0_station_id_c_din,
        if_full_n => station_id_c_full_n,
        if_write => entry_proc7_U0_station_id_c_write,
        if_dout => station_id_c_dout,
        if_empty_n => station_id_c_empty_n,
        if_read => packetizer_U0_station_id_read,
        if_num_data_valid => station_id_c_num_data_valid,
        if_fifo_cap => station_id_c_fifo_cap);

    thread_id_c_U : component vdif_chain_fifo_w10_d3_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc7_U0_thread_id_c_din,
        if_full_n => thread_id_c_full_n,
        if_write => entry_proc7_U0_thread_id_c_write,
        if_dout => thread_id_c_dout,
        if_empty_n => thread_id_c_empty_n,
        if_read => packetizer_U0_thread_id_read,
        if_num_data_valid => thread_id_c_num_data_valid,
        if_fifo_cap => thread_id_c_fifo_cap);

    complex_data_c_U : component vdif_chain_fifo_w1_d3_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc7_U0_complex_data_c_din,
        if_full_n => complex_data_c_full_n,
        if_write => entry_proc7_U0_complex_data_c_write,
        if_dout => complex_data_c_dout,
        if_empty_n => complex_data_c_empty_n,
        if_read => packetizer_U0_complex_data_read,
        if_num_data_valid => complex_data_c_num_data_valid,
        if_fifo_cap => complex_data_c_fifo_cap);

    pps_c_U : component vdif_chain_fifo_w1_d3_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc7_U0_pps_c_din,
        if_full_n => pps_c_full_n,
        if_write => entry_proc7_U0_pps_c_write,
        if_dout => pps_c_dout,
        if_empty_n => pps_c_empty_n,
        if_read => packetizer_U0_pps_read,
        if_num_data_valid => pps_c_num_data_valid,
        if_fifo_cap => pps_c_fifo_cap);

    packetizer_in_U : component vdif_chain_fifo_w32_d2048_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_din,
        if_full_n => packetizer_in_full_n,
        if_write => Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_write,
        if_dout => packetizer_in_dout,
        if_empty_n => packetizer_in_empty_n,
        if_read => packetizer_U0_packetizer_in_read,
        if_num_data_valid => packetizer_in_num_data_valid,
        if_fifo_cap => packetizer_in_fifo_cap);

    bits_per_sample_c_U : component vdif_chain_fifo_w5_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_din,
        if_full_n => bits_per_sample_c_full_n,
        if_write => Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_write,
        if_dout => bits_per_sample_c_dout,
        if_empty_n => bits_per_sample_c_empty_n,
        if_read => packetizer_U0_bits_per_sample_read,
        if_num_data_valid => bits_per_sample_c_num_data_valid,
        if_fifo_cap => bits_per_sample_c_fifo_cap);

    payload_words_c_U : component vdif_chain_fifo_w16_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_din,
        if_full_n => payload_words_c_full_n,
        if_write => Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_write,
        if_dout => payload_words_c_dout,
        if_empty_n => payload_words_c_empty_n,
        if_read => packetizer_U0_payload_words_read,
        if_num_data_valid => payload_words_c_num_data_valid,
        if_fifo_cap => payload_words_c_fifo_cap);

    start_for_packetizer_U0_U : component vdif_chain_start_for_packetizer_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_packetizer_U0_din,
        if_full_n => start_for_packetizer_U0_full_n,
        if_write => entry_proc7_U0_start_write,
        if_dout => start_for_packetizer_U0_dout,
        if_empty_n => start_for_packetizer_U0_empty_n,
        if_read => packetizer_U0_ap_ready);





    ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc7_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc7_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc7_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc7_U0_ap_ready <= ap_sync_entry_proc7_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    Loop_VITIS_LOOP_71_1_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_VITIS_LOOP_71_1_proc_U0_ap_start <= ((ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    adc_in_TREADY <= Loop_VITIS_LOOP_71_1_proc_U0_adc_in_TREADY;
    ap_done <= packetizer_U0_ap_done;
    ap_idle <= (packetizer_U0_ap_idle and entry_proc7_U0_ap_idle and Loop_VITIS_LOOP_71_1_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= (ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready or Loop_VITIS_LOOP_71_1_proc_U0_ap_ready);
    ap_sync_entry_proc7_U0_ap_ready <= (entry_proc7_U0_ap_ready or ap_sync_reg_entry_proc7_U0_ap_ready);
    ap_sync_ready <= (ap_sync_entry_proc7_U0_ap_ready and ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready);
    entry_proc7_U0_ap_continue <= ap_const_logic_1;
    entry_proc7_U0_ap_start <= ((ap_sync_reg_entry_proc7_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    out_stream_TDATA <= packetizer_U0_out_stream_TDATA;
    out_stream_TKEEP <= packetizer_U0_out_stream_TKEEP;
    out_stream_TLAST <= packetizer_U0_out_stream_TLAST;
    out_stream_TSTRB <= packetizer_U0_out_stream_TSTRB;
    out_stream_TVALID <= packetizer_U0_out_stream_TVALID;
    packetizer_U0_ap_continue <= ap_const_logic_1;
    packetizer_U0_ap_start <= start_for_packetizer_U0_empty_n;
    start_for_packetizer_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
