-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_entry_proc7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    epoch : IN STD_LOGIC_VECTOR (5 downto 0);
    epoch_c_din : OUT STD_LOGIC_VECTOR (5 downto 0);
    epoch_c_full_n : IN STD_LOGIC;
    epoch_c_write : OUT STD_LOGIC;
    epoch_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    epoch_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id : IN STD_LOGIC_VECTOR (15 downto 0);
    station_id_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    station_id_c_full_n : IN STD_LOGIC;
    station_id_c_write : OUT STD_LOGIC;
    station_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    station_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id : IN STD_LOGIC_VECTOR (9 downto 0);
    thread_id_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    thread_id_c_full_n : IN STD_LOGIC;
    thread_id_c_write : OUT STD_LOGIC;
    thread_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    thread_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data : IN STD_LOGIC_VECTOR (0 downto 0);
    complex_data_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    complex_data_c_full_n : IN STD_LOGIC;
    complex_data_c_write : OUT STD_LOGIC;
    complex_data_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    complex_data_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    pps : IN STD_LOGIC_VECTOR (0 downto 0);
    pps_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    pps_c_full_n : IN STD_LOGIC;
    pps_c_write : OUT STD_LOGIC;
    pps_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    pps_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of vdif_chain_entry_proc7 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal epoch_c_blk_n : STD_LOGIC;
    signal station_id_c_blk_n : STD_LOGIC;
    signal thread_id_c_blk_n : STD_LOGIC;
    signal complex_data_c_blk_n : STD_LOGIC;
    signal pps_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, epoch_c_full_n, station_id_c_full_n, thread_id_c_full_n, complex_data_c_full_n, pps_c_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (pps_c_full_n = ap_const_logic_0) or (complex_data_c_full_n = ap_const_logic_0) or (thread_id_c_full_n = ap_const_logic_0) or (station_id_c_full_n = ap_const_logic_0) or (epoch_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    complex_data_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, complex_data_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            complex_data_c_blk_n <= complex_data_c_full_n;
        else 
            complex_data_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    complex_data_c_din <= complex_data;

    complex_data_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            complex_data_c_write <= ap_const_logic_1;
        else 
            complex_data_c_write <= ap_const_logic_0;
        end if; 
    end process;


    epoch_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, epoch_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            epoch_c_blk_n <= epoch_c_full_n;
        else 
            epoch_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    epoch_c_din <= epoch;

    epoch_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            epoch_c_write <= ap_const_logic_1;
        else 
            epoch_c_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    pps_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pps_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pps_c_blk_n <= pps_c_full_n;
        else 
            pps_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pps_c_din <= pps;

    pps_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pps_c_write <= ap_const_logic_1;
        else 
            pps_c_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    station_id_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, station_id_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            station_id_c_blk_n <= station_id_c_full_n;
        else 
            station_id_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    station_id_c_din <= station_id;

    station_id_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            station_id_c_write <= ap_const_logic_1;
        else 
            station_id_c_write <= ap_const_logic_0;
        end if; 
    end process;


    thread_id_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, thread_id_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            thread_id_c_blk_n <= thread_id_c_full_n;
        else 
            thread_id_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    thread_id_c_din <= thread_id;

    thread_id_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            thread_id_c_write <= ap_const_logic_1;
        else 
            thread_id_c_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
