-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_packetizer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    packetizer_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    packetizer_in_empty_n : IN STD_LOGIC;
    packetizer_in_read : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    epoch_dout : IN STD_LOGIC_VECTOR (5 downto 0);
    epoch_empty_n : IN STD_LOGIC;
    epoch_read : OUT STD_LOGIC;
    station_id_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    station_id_empty_n : IN STD_LOGIC;
    station_id_read : OUT STD_LOGIC;
    thread_id_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    thread_id_empty_n : IN STD_LOGIC;
    thread_id_read : OUT STD_LOGIC;
    bits_per_sample_dout : IN STD_LOGIC_VECTOR (4 downto 0);
    bits_per_sample_empty_n : IN STD_LOGIC;
    bits_per_sample_read : OUT STD_LOGIC;
    complex_data_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    complex_data_empty_n : IN STD_LOGIC;
    complex_data_read : OUT STD_LOGIC;
    pps_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    pps_empty_n : IN STD_LOGIC;
    pps_read : OUT STD_LOGIC;
    payload_words_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    payload_words_empty_n : IN STD_LOGIC;
    payload_words_read : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of vdif_chain_packetizer is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal header_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal header_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_return_r : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_epoch_read : STD_LOGIC;
    signal entry_proc_U0_epoch_c_din : STD_LOGIC_VECTOR (5 downto 0);
    signal entry_proc_U0_epoch_c_write : STD_LOGIC;
    signal entry_proc_U0_station_id_read : STD_LOGIC;
    signal entry_proc_U0_station_id_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_station_id_c_write : STD_LOGIC;
    signal entry_proc_U0_thread_id_read : STD_LOGIC;
    signal entry_proc_U0_thread_id_c_din : STD_LOGIC_VECTOR (9 downto 0);
    signal entry_proc_U0_thread_id_c_write : STD_LOGIC;
    signal entry_proc_U0_bits_per_sample_read : STD_LOGIC;
    signal entry_proc_U0_bits_per_sample_c_din : STD_LOGIC_VECTOR (4 downto 0);
    signal entry_proc_U0_bits_per_sample_c_write : STD_LOGIC;
    signal entry_proc_U0_complex_data_read : STD_LOGIC;
    signal entry_proc_U0_complex_data_c_din : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_complex_data_c_write : STD_LOGIC;
    signal entry_proc_U0_payload_words_read : STD_LOGIC;
    signal entry_proc_U0_payload_words_c1_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_payload_words_c1_write : STD_LOGIC;
    signal p_channel_full_n : STD_LOGIC;
    signal timestamp_engine_U0_ap_start : STD_LOGIC;
    signal timestamp_engine_U0_ap_done : STD_LOGIC;
    signal timestamp_engine_U0_ap_continue : STD_LOGIC;
    signal timestamp_engine_U0_ap_idle : STD_LOGIC;
    signal timestamp_engine_U0_ap_ready : STD_LOGIC;
    signal timestamp_engine_U0_pps_read : STD_LOGIC;
    signal timestamp_engine_U0_ap_return_0 : STD_LOGIC_VECTOR (29 downto 0);
    signal timestamp_engine_U0_ap_return_1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_channel_done_frame_no : STD_LOGIC;
    signal frame_no_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_frame_no : STD_LOGIC := '0';
    signal ap_sync_channel_write_frame_no : STD_LOGIC;
    signal packetizer_Block_entry_fsm_state_fb_proc_U0_ap_start : STD_LOGIC;
    signal packetizer_Block_entry_fsm_state_fb_proc_U0_ap_done : STD_LOGIC;
    signal packetizer_Block_entry_fsm_state_fb_proc_U0_ap_continue : STD_LOGIC;
    signal packetizer_Block_entry_fsm_state_fb_proc_U0_ap_idle : STD_LOGIC;
    signal packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal header_generator_U0_ap_start : STD_LOGIC;
    signal header_generator_U0_ap_done : STD_LOGIC;
    signal header_generator_U0_ap_continue : STD_LOGIC;
    signal header_generator_U0_ap_idle : STD_LOGIC;
    signal header_generator_U0_ap_ready : STD_LOGIC;
    signal header_generator_U0_epoch_read : STD_LOGIC;
    signal header_generator_U0_station_id_read : STD_LOGIC;
    signal header_generator_U0_thread_id_read : STD_LOGIC;
    signal header_generator_U0_bits_per_sample_read : STD_LOGIC;
    signal header_generator_U0_complex_data_read : STD_LOGIC;
    signal header_generator_U0_payload_words_read : STD_LOGIC;
    signal header_generator_U0_header_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal header_generator_U0_header_ce0 : STD_LOGIC;
    signal header_generator_U0_header_we0 : STD_LOGIC;
    signal header_generator_U0_header_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal header_generator_U0_header_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal header_generator_U0_header_ce1 : STD_LOGIC;
    signal header_generator_U0_header_we1 : STD_LOGIC;
    signal header_generator_U0_header_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal header_generator_U0_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_payload_words_c_channel : STD_LOGIC;
    signal payload_words_c_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_payload_words_c_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_payload_words_c_channel : STD_LOGIC;
    signal ap_channel_done_header : STD_LOGIC;
    signal header_generator_U0_header_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_header : STD_LOGIC := '0';
    signal ap_sync_channel_write_header : STD_LOGIC;
    signal read_payload_U0_ap_start : STD_LOGIC;
    signal read_payload_U0_ap_done : STD_LOGIC;
    signal read_payload_U0_ap_continue : STD_LOGIC;
    signal read_payload_U0_ap_idle : STD_LOGIC;
    signal read_payload_U0_ap_ready : STD_LOGIC;
    signal read_payload_U0_packetizer_in_read : STD_LOGIC;
    signal read_payload_U0_fifo_din : STD_LOGIC_VECTOR (31 downto 0);
    signal read_payload_U0_fifo_write : STD_LOGIC;
    signal read_payload_U0_fifo_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal read_payload_U0_fifo_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_start : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_done : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_continue : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_idle : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_ce0 : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TVALID : STD_LOGIC;
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_fifo_read : STD_LOGIC;
    signal header_i_full_n : STD_LOGIC;
    signal header_t_empty_n : STD_LOGIC;
    signal p_channel_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal p_channel_empty_n : STD_LOGIC;
    signal p_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal p_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal epoch_c_full_n : STD_LOGIC;
    signal epoch_c_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal epoch_c_empty_n : STD_LOGIC;
    signal epoch_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal epoch_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal station_id_c_full_n : STD_LOGIC;
    signal station_id_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal station_id_c_empty_n : STD_LOGIC;
    signal station_id_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal station_id_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal thread_id_c_full_n : STD_LOGIC;
    signal thread_id_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal thread_id_c_empty_n : STD_LOGIC;
    signal thread_id_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal thread_id_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal bits_per_sample_c_full_n : STD_LOGIC;
    signal bits_per_sample_c_dout : STD_LOGIC_VECTOR (4 downto 0);
    signal bits_per_sample_c_empty_n : STD_LOGIC;
    signal bits_per_sample_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal bits_per_sample_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal complex_data_c_full_n : STD_LOGIC;
    signal complex_data_c_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal complex_data_c_empty_n : STD_LOGIC;
    signal complex_data_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal complex_data_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal payload_words_c1_full_n : STD_LOGIC;
    signal payload_words_c1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal payload_words_c1_empty_n : STD_LOGIC;
    signal payload_words_c1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal payload_words_c1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal seconds_from_epoch_full_n : STD_LOGIC;
    signal seconds_from_epoch_dout : STD_LOGIC_VECTOR (29 downto 0);
    signal seconds_from_epoch_empty_n : STD_LOGIC;
    signal seconds_from_epoch_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal seconds_from_epoch_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal frame_no_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal frame_no_empty_n : STD_LOGIC;
    signal frame_no_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal frame_no_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal payload_words_c_channel_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal payload_words_c_channel_empty_n : STD_LOGIC;
    signal payload_words_c_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal payload_words_c_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal fifo_full_n : STD_LOGIC;
    signal fifo_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal fifo_empty_n : STD_LOGIC;
    signal fifo_num_data_valid : STD_LOGIC_VECTOR (13 downto 0);
    signal fifo_fifo_cap : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_timestamp_engine_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_timestamp_engine_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        return_r : OUT STD_LOGIC_VECTOR (15 downto 0);
        epoch_dout : IN STD_LOGIC_VECTOR (5 downto 0);
        epoch_empty_n : IN STD_LOGIC;
        epoch_read : OUT STD_LOGIC;
        epoch_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        epoch_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        epoch_c_din : OUT STD_LOGIC_VECTOR (5 downto 0);
        epoch_c_full_n : IN STD_LOGIC;
        epoch_c_write : OUT STD_LOGIC;
        epoch_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        epoch_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        station_id_empty_n : IN STD_LOGIC;
        station_id_read : OUT STD_LOGIC;
        station_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        station_id_c_full_n : IN STD_LOGIC;
        station_id_c_write : OUT STD_LOGIC;
        station_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        thread_id_empty_n : IN STD_LOGIC;
        thread_id_read : OUT STD_LOGIC;
        thread_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        thread_id_c_full_n : IN STD_LOGIC;
        thread_id_c_write : OUT STD_LOGIC;
        thread_id_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_dout : IN STD_LOGIC_VECTOR (4 downto 0);
        bits_per_sample_empty_n : IN STD_LOGIC;
        bits_per_sample_read : OUT STD_LOGIC;
        bits_per_sample_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_c_din : OUT STD_LOGIC_VECTOR (4 downto 0);
        bits_per_sample_c_full_n : IN STD_LOGIC;
        bits_per_sample_c_write : OUT STD_LOGIC;
        bits_per_sample_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        complex_data_empty_n : IN STD_LOGIC;
        complex_data_read : OUT STD_LOGIC;
        complex_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        complex_data_c_full_n : IN STD_LOGIC;
        complex_data_c_write : OUT STD_LOGIC;
        complex_data_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        payload_words_empty_n : IN STD_LOGIC;
        payload_words_read : OUT STD_LOGIC;
        payload_words_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_c1_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        payload_words_c1_full_n : IN STD_LOGIC;
        payload_words_c1_write : OUT STD_LOGIC;
        payload_words_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_timestamp_engine IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pps_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        pps_empty_n : IN STD_LOGIC;
        pps_read : OUT STD_LOGIC;
        pps_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        pps_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component vdif_chain_packetizer_Block_entry_fsm_state_fb_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;


    component vdif_chain_header_generator IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (29 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (23 downto 0);
        epoch_dout : IN STD_LOGIC_VECTOR (5 downto 0);
        epoch_empty_n : IN STD_LOGIC;
        epoch_read : OUT STD_LOGIC;
        epoch_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        epoch_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        station_id_empty_n : IN STD_LOGIC;
        station_id_read : OUT STD_LOGIC;
        station_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        station_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        thread_id_empty_n : IN STD_LOGIC;
        thread_id_read : OUT STD_LOGIC;
        thread_id_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        thread_id_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_dout : IN STD_LOGIC_VECTOR (4 downto 0);
        bits_per_sample_empty_n : IN STD_LOGIC;
        bits_per_sample_read : OUT STD_LOGIC;
        bits_per_sample_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bits_per_sample_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        complex_data_empty_n : IN STD_LOGIC;
        complex_data_read : OUT STD_LOGIC;
        complex_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        complex_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        payload_words_empty_n : IN STD_LOGIC;
        payload_words_read : OUT STD_LOGIC;
        payload_words_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        payload_words_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        header_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        header_ce0 : OUT STD_LOGIC;
        header_we0 : OUT STD_LOGIC;
        header_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        header_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        header_ce1 : OUT STD_LOGIC;
        header_we1 : OUT STD_LOGIC;
        header_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component vdif_chain_read_payload IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        packetizer_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        packetizer_in_empty_n : IN STD_LOGIC;
        packetizer_in_read : OUT STD_LOGIC;
        packetizer_in_num_data_valid : IN STD_LOGIC_VECTOR (11 downto 0);
        packetizer_in_fifo_cap : IN STD_LOGIC_VECTOR (11 downto 0);
        fifo_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fifo_full_n : IN STD_LOGIC;
        fifo_write : OUT STD_LOGIC;
        fifo_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        fifo_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        payload_words : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        header_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        header_ce0 : OUT STD_LOGIC;
        header_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        fifo_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fifo_empty_n : IN STD_LOGIC;
        fifo_read : OUT STD_LOGIC;
        fifo_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
        fifo_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
        p_read : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component vdif_chain_packetizer_header_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        i_ce1 : IN STD_LOGIC;
        i_we1 : IN STD_LOGIC;
        i_d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        t_address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        t_ce1 : IN STD_LOGIC;
        t_we1 : IN STD_LOGIC;
        t_d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component vdif_chain_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w6_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (5 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w16_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w10_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (9 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w5_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (4 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w1_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w30_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (29 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (29 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w24_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component vdif_chain_fifo_w32_d8192_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (13 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    header_U : component vdif_chain_packetizer_header_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => header_generator_U0_header_address0,
        i_ce0 => header_generator_U0_header_ce0,
        i_we0 => header_generator_U0_header_we0,
        i_d0 => header_generator_U0_header_d0,
        i_q0 => header_i_q0,
        i_address1 => header_generator_U0_header_address1,
        i_ce1 => header_generator_U0_header_ce1,
        i_we1 => header_generator_U0_header_we1,
        i_d1 => header_generator_U0_header_d1,
        t_address0 => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_address0,
        t_ce0 => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => header_t_q0,
        t_address1 => ap_const_lv3_0,
        t_ce1 => ap_const_logic_0,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv32_0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => header_i_full_n,
        i_write => ap_channel_done_header,
        t_empty_n => header_t_empty_n,
        t_read => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready);

    entry_proc_U0 : component vdif_chain_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc_U0_ap_start,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        return_r => entry_proc_U0_return_r,
        epoch_dout => epoch_dout,
        epoch_empty_n => epoch_empty_n,
        epoch_read => entry_proc_U0_epoch_read,
        epoch_num_data_valid => ap_const_lv3_0,
        epoch_fifo_cap => ap_const_lv3_0,
        epoch_c_din => entry_proc_U0_epoch_c_din,
        epoch_c_full_n => epoch_c_full_n,
        epoch_c_write => entry_proc_U0_epoch_c_write,
        epoch_c_num_data_valid => epoch_c_num_data_valid,
        epoch_c_fifo_cap => epoch_c_fifo_cap,
        station_id_dout => station_id_dout,
        station_id_empty_n => station_id_empty_n,
        station_id_read => entry_proc_U0_station_id_read,
        station_id_num_data_valid => ap_const_lv3_0,
        station_id_fifo_cap => ap_const_lv3_0,
        station_id_c_din => entry_proc_U0_station_id_c_din,
        station_id_c_full_n => station_id_c_full_n,
        station_id_c_write => entry_proc_U0_station_id_c_write,
        station_id_c_num_data_valid => station_id_c_num_data_valid,
        station_id_c_fifo_cap => station_id_c_fifo_cap,
        thread_id_dout => thread_id_dout,
        thread_id_empty_n => thread_id_empty_n,
        thread_id_read => entry_proc_U0_thread_id_read,
        thread_id_num_data_valid => ap_const_lv3_0,
        thread_id_fifo_cap => ap_const_lv3_0,
        thread_id_c_din => entry_proc_U0_thread_id_c_din,
        thread_id_c_full_n => thread_id_c_full_n,
        thread_id_c_write => entry_proc_U0_thread_id_c_write,
        thread_id_c_num_data_valid => thread_id_c_num_data_valid,
        thread_id_c_fifo_cap => thread_id_c_fifo_cap,
        bits_per_sample_dout => bits_per_sample_dout,
        bits_per_sample_empty_n => bits_per_sample_empty_n,
        bits_per_sample_read => entry_proc_U0_bits_per_sample_read,
        bits_per_sample_num_data_valid => ap_const_lv3_0,
        bits_per_sample_fifo_cap => ap_const_lv3_0,
        bits_per_sample_c_din => entry_proc_U0_bits_per_sample_c_din,
        bits_per_sample_c_full_n => bits_per_sample_c_full_n,
        bits_per_sample_c_write => entry_proc_U0_bits_per_sample_c_write,
        bits_per_sample_c_num_data_valid => bits_per_sample_c_num_data_valid,
        bits_per_sample_c_fifo_cap => bits_per_sample_c_fifo_cap,
        complex_data_dout => complex_data_dout,
        complex_data_empty_n => complex_data_empty_n,
        complex_data_read => entry_proc_U0_complex_data_read,
        complex_data_num_data_valid => ap_const_lv3_0,
        complex_data_fifo_cap => ap_const_lv3_0,
        complex_data_c_din => entry_proc_U0_complex_data_c_din,
        complex_data_c_full_n => complex_data_c_full_n,
        complex_data_c_write => entry_proc_U0_complex_data_c_write,
        complex_data_c_num_data_valid => complex_data_c_num_data_valid,
        complex_data_c_fifo_cap => complex_data_c_fifo_cap,
        payload_words_dout => payload_words_dout,
        payload_words_empty_n => payload_words_empty_n,
        payload_words_read => entry_proc_U0_payload_words_read,
        payload_words_num_data_valid => ap_const_lv3_0,
        payload_words_fifo_cap => ap_const_lv3_0,
        payload_words_c1_din => entry_proc_U0_payload_words_c1_din,
        payload_words_c1_full_n => payload_words_c1_full_n,
        payload_words_c1_write => entry_proc_U0_payload_words_c1_write,
        payload_words_c1_num_data_valid => payload_words_c1_num_data_valid,
        payload_words_c1_fifo_cap => payload_words_c1_fifo_cap);

    timestamp_engine_U0 : component vdif_chain_timestamp_engine
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => timestamp_engine_U0_ap_start,
        ap_done => timestamp_engine_U0_ap_done,
        ap_continue => timestamp_engine_U0_ap_continue,
        ap_idle => timestamp_engine_U0_ap_idle,
        ap_ready => timestamp_engine_U0_ap_ready,
        pps_dout => pps_dout,
        pps_empty_n => pps_empty_n,
        pps_read => timestamp_engine_U0_pps_read,
        pps_num_data_valid => ap_const_lv3_0,
        pps_fifo_cap => ap_const_lv3_0,
        ap_return_0 => timestamp_engine_U0_ap_return_0,
        ap_return_1 => timestamp_engine_U0_ap_return_1);

    packetizer_Block_entry_fsm_state_fb_proc_U0 : component vdif_chain_packetizer_Block_entry_fsm_state_fb_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => packetizer_Block_entry_fsm_state_fb_proc_U0_ap_start,
        ap_done => packetizer_Block_entry_fsm_state_fb_proc_U0_ap_done,
        ap_continue => packetizer_Block_entry_fsm_state_fb_proc_U0_ap_continue,
        ap_idle => packetizer_Block_entry_fsm_state_fb_proc_U0_ap_idle,
        ap_ready => packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready);

    header_generator_U0 : component vdif_chain_header_generator
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => header_generator_U0_ap_start,
        ap_done => header_generator_U0_ap_done,
        ap_continue => header_generator_U0_ap_continue,
        ap_idle => header_generator_U0_ap_idle,
        ap_ready => header_generator_U0_ap_ready,
        p_read => seconds_from_epoch_dout,
        p_read1 => frame_no_dout,
        epoch_dout => epoch_c_dout,
        epoch_empty_n => epoch_c_empty_n,
        epoch_read => header_generator_U0_epoch_read,
        epoch_num_data_valid => epoch_c_num_data_valid,
        epoch_fifo_cap => epoch_c_fifo_cap,
        station_id_dout => station_id_c_dout,
        station_id_empty_n => station_id_c_empty_n,
        station_id_read => header_generator_U0_station_id_read,
        station_id_num_data_valid => station_id_c_num_data_valid,
        station_id_fifo_cap => station_id_c_fifo_cap,
        thread_id_dout => thread_id_c_dout,
        thread_id_empty_n => thread_id_c_empty_n,
        thread_id_read => header_generator_U0_thread_id_read,
        thread_id_num_data_valid => thread_id_c_num_data_valid,
        thread_id_fifo_cap => thread_id_c_fifo_cap,
        bits_per_sample_dout => bits_per_sample_c_dout,
        bits_per_sample_empty_n => bits_per_sample_c_empty_n,
        bits_per_sample_read => header_generator_U0_bits_per_sample_read,
        bits_per_sample_num_data_valid => bits_per_sample_c_num_data_valid,
        bits_per_sample_fifo_cap => bits_per_sample_c_fifo_cap,
        complex_data_dout => complex_data_c_dout,
        complex_data_empty_n => complex_data_c_empty_n,
        complex_data_read => header_generator_U0_complex_data_read,
        complex_data_num_data_valid => complex_data_c_num_data_valid,
        complex_data_fifo_cap => complex_data_c_fifo_cap,
        payload_words_dout => payload_words_c1_dout,
        payload_words_empty_n => payload_words_c1_empty_n,
        payload_words_read => header_generator_U0_payload_words_read,
        payload_words_num_data_valid => payload_words_c1_num_data_valid,
        payload_words_fifo_cap => payload_words_c1_fifo_cap,
        header_address0 => header_generator_U0_header_address0,
        header_ce0 => header_generator_U0_header_ce0,
        header_we0 => header_generator_U0_header_we0,
        header_d0 => header_generator_U0_header_d0,
        header_address1 => header_generator_U0_header_address1,
        header_ce1 => header_generator_U0_header_ce1,
        header_we1 => header_generator_U0_header_we1,
        header_d1 => header_generator_U0_header_d1,
        ap_return => header_generator_U0_ap_return);

    read_payload_U0 : component vdif_chain_read_payload
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_payload_U0_ap_start,
        ap_done => read_payload_U0_ap_done,
        ap_continue => read_payload_U0_ap_continue,
        ap_idle => read_payload_U0_ap_idle,
        ap_ready => read_payload_U0_ap_ready,
        packetizer_in_dout => packetizer_in_dout,
        packetizer_in_empty_n => packetizer_in_empty_n,
        packetizer_in_read => read_payload_U0_packetizer_in_read,
        packetizer_in_num_data_valid => ap_const_lv12_0,
        packetizer_in_fifo_cap => ap_const_lv12_0,
        fifo_din => read_payload_U0_fifo_din,
        fifo_full_n => fifo_full_n,
        fifo_write => read_payload_U0_fifo_write,
        fifo_num_data_valid => read_payload_U0_fifo_num_data_valid,
        fifo_fifo_cap => read_payload_U0_fifo_fifo_cap,
        payload_words => p_channel_dout);

    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0 : component vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_start,
        ap_done => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_done,
        ap_continue => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_continue,
        ap_idle => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_idle,
        ap_ready => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready,
        header_address0 => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_address0,
        header_ce0 => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_ce0,
        header_q0 => header_t_q0,
        out_stream_TDATA => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TDATA,
        out_stream_TVALID => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TVALID,
        out_stream_TREADY => out_stream_TREADY,
        out_stream_TKEEP => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TKEEP,
        out_stream_TSTRB => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TSTRB,
        out_stream_TLAST => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TLAST,
        fifo_dout => fifo_dout,
        fifo_empty_n => fifo_empty_n,
        fifo_read => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_fifo_read,
        fifo_num_data_valid => fifo_num_data_valid,
        fifo_fifo_cap => fifo_fifo_cap,
        p_read => payload_words_c_channel_dout);

    p_channel_U : component vdif_chain_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_return_r,
        if_full_n => p_channel_full_n,
        if_write => entry_proc_U0_ap_done,
        if_dout => p_channel_dout,
        if_empty_n => p_channel_empty_n,
        if_read => read_payload_U0_ap_ready,
        if_num_data_valid => p_channel_num_data_valid,
        if_fifo_cap => p_channel_fifo_cap);

    epoch_c_U : component vdif_chain_fifo_w6_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_epoch_c_din,
        if_full_n => epoch_c_full_n,
        if_write => entry_proc_U0_epoch_c_write,
        if_dout => epoch_c_dout,
        if_empty_n => epoch_c_empty_n,
        if_read => header_generator_U0_epoch_read,
        if_num_data_valid => epoch_c_num_data_valid,
        if_fifo_cap => epoch_c_fifo_cap);

    station_id_c_U : component vdif_chain_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_station_id_c_din,
        if_full_n => station_id_c_full_n,
        if_write => entry_proc_U0_station_id_c_write,
        if_dout => station_id_c_dout,
        if_empty_n => station_id_c_empty_n,
        if_read => header_generator_U0_station_id_read,
        if_num_data_valid => station_id_c_num_data_valid,
        if_fifo_cap => station_id_c_fifo_cap);

    thread_id_c_U : component vdif_chain_fifo_w10_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_thread_id_c_din,
        if_full_n => thread_id_c_full_n,
        if_write => entry_proc_U0_thread_id_c_write,
        if_dout => thread_id_c_dout,
        if_empty_n => thread_id_c_empty_n,
        if_read => header_generator_U0_thread_id_read,
        if_num_data_valid => thread_id_c_num_data_valid,
        if_fifo_cap => thread_id_c_fifo_cap);

    bits_per_sample_c_U : component vdif_chain_fifo_w5_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_bits_per_sample_c_din,
        if_full_n => bits_per_sample_c_full_n,
        if_write => entry_proc_U0_bits_per_sample_c_write,
        if_dout => bits_per_sample_c_dout,
        if_empty_n => bits_per_sample_c_empty_n,
        if_read => header_generator_U0_bits_per_sample_read,
        if_num_data_valid => bits_per_sample_c_num_data_valid,
        if_fifo_cap => bits_per_sample_c_fifo_cap);

    complex_data_c_U : component vdif_chain_fifo_w1_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_complex_data_c_din,
        if_full_n => complex_data_c_full_n,
        if_write => entry_proc_U0_complex_data_c_write,
        if_dout => complex_data_c_dout,
        if_empty_n => complex_data_c_empty_n,
        if_read => header_generator_U0_complex_data_read,
        if_num_data_valid => complex_data_c_num_data_valid,
        if_fifo_cap => complex_data_c_fifo_cap);

    payload_words_c1_U : component vdif_chain_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_payload_words_c1_din,
        if_full_n => payload_words_c1_full_n,
        if_write => entry_proc_U0_payload_words_c1_write,
        if_dout => payload_words_c1_dout,
        if_empty_n => payload_words_c1_empty_n,
        if_read => header_generator_U0_payload_words_read,
        if_num_data_valid => payload_words_c1_num_data_valid,
        if_fifo_cap => payload_words_c1_fifo_cap);

    seconds_from_epoch_U : component vdif_chain_fifo_w30_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => timestamp_engine_U0_ap_return_0,
        if_full_n => seconds_from_epoch_full_n,
        if_write => ap_channel_done_frame_no,
        if_dout => seconds_from_epoch_dout,
        if_empty_n => seconds_from_epoch_empty_n,
        if_read => header_generator_U0_ap_ready,
        if_num_data_valid => seconds_from_epoch_num_data_valid,
        if_fifo_cap => seconds_from_epoch_fifo_cap);

    frame_no_U : component vdif_chain_fifo_w24_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => timestamp_engine_U0_ap_return_1,
        if_full_n => frame_no_full_n,
        if_write => ap_channel_done_frame_no,
        if_dout => frame_no_dout,
        if_empty_n => frame_no_empty_n,
        if_read => header_generator_U0_ap_ready,
        if_num_data_valid => frame_no_num_data_valid,
        if_fifo_cap => frame_no_fifo_cap);

    payload_words_c_channel_U : component vdif_chain_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => header_generator_U0_ap_return,
        if_full_n => payload_words_c_channel_full_n,
        if_write => ap_channel_done_payload_words_c_channel,
        if_dout => payload_words_c_channel_dout,
        if_empty_n => payload_words_c_channel_empty_n,
        if_read => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready,
        if_num_data_valid => payload_words_c_channel_num_data_valid,
        if_fifo_cap => payload_words_c_channel_fifo_cap);

    fifo_U : component vdif_chain_fifo_w32_d8192_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_payload_U0_fifo_din,
        if_full_n => fifo_full_n,
        if_write => read_payload_U0_fifo_write,
        if_dout => fifo_dout,
        if_empty_n => fifo_empty_n,
        if_read => packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_fifo_read,
        if_num_data_valid => fifo_num_data_valid,
        if_fifo_cap => fifo_fifo_cap);





    ap_sync_reg_channel_write_frame_no_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_frame_no <= ap_const_logic_0;
            else
                if (((timestamp_engine_U0_ap_done and timestamp_engine_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_frame_no <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_frame_no <= ap_sync_channel_write_frame_no;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_header_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_header <= ap_const_logic_0;
            else
                if (((header_generator_U0_ap_done and header_generator_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_header <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_header <= ap_sync_channel_write_header;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_payload_words_c_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_payload_words_c_channel <= ap_const_logic_0;
            else
                if (((header_generator_U0_ap_done and header_generator_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_payload_words_c_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_payload_words_c_channel <= ap_sync_channel_write_payload_words_c_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_timestamp_engine_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_timestamp_engine_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_timestamp_engine_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_timestamp_engine_U0_ap_ready <= ap_sync_timestamp_engine_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_frame_no <= (timestamp_engine_U0_ap_done and (ap_sync_reg_channel_write_frame_no xor ap_const_logic_1));
    ap_channel_done_header <= (header_generator_U0_ap_done and (ap_sync_reg_channel_write_header xor ap_const_logic_1));
    ap_channel_done_payload_words_c_channel <= (header_generator_U0_ap_done and (ap_sync_reg_channel_write_payload_words_c_channel xor ap_const_logic_1));
    ap_done <= ap_sync_done;
    ap_idle <= (timestamp_engine_U0_ap_idle and read_payload_U0_ap_idle and packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_idle and packetizer_Block_entry_fsm_state_fb_proc_U0_ap_idle and header_generator_U0_ap_idle and (payload_words_c_channel_empty_n xor ap_const_logic_1) and (seconds_from_epoch_empty_n xor ap_const_logic_1) and (p_channel_empty_n xor ap_const_logic_1) and entry_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_channel_write_frame_no <= ((frame_no_full_n and ap_channel_done_frame_no) or ap_sync_reg_channel_write_frame_no);
    ap_sync_channel_write_header <= ((header_generator_U0_header_full_n and ap_channel_done_header) or ap_sync_reg_channel_write_header);
    ap_sync_channel_write_payload_words_c_channel <= ((payload_words_c_channel_full_n and ap_channel_done_payload_words_c_channel) or ap_sync_reg_channel_write_payload_words_c_channel);
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_done <= (packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_done and packetizer_Block_entry_fsm_state_fb_proc_U0_ap_done);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= (packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready or ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_timestamp_engine_U0_ap_ready and ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    ap_sync_timestamp_engine_U0_ap_ready <= (timestamp_engine_U0_ap_ready or ap_sync_reg_timestamp_engine_U0_ap_ready);
    bits_per_sample_read <= entry_proc_U0_bits_per_sample_read;
    complex_data_read <= entry_proc_U0_complex_data_read;
    entry_proc_U0_ap_continue <= p_channel_full_n;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    epoch_read <= entry_proc_U0_epoch_read;
    header_generator_U0_ap_continue <= ap_sync_channel_write_header;
    header_generator_U0_ap_start <= seconds_from_epoch_empty_n;
    header_generator_U0_header_full_n <= header_i_full_n;
    out_stream_TDATA <= packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TDATA;
    out_stream_TKEEP <= packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TKEEP;
    out_stream_TLAST <= packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TLAST;
    out_stream_TSTRB <= packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TSTRB;
    out_stream_TVALID <= packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TVALID;
    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_continue <= ap_sync_continue;
    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_start <= ((ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_continue <= ap_sync_continue;
    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_start <= payload_words_c_channel_empty_n;
    packetizer_in_read <= read_payload_U0_packetizer_in_read;
    payload_words_read <= entry_proc_U0_payload_words_read;
    pps_read <= timestamp_engine_U0_pps_read;
    read_payload_U0_ap_continue <= ap_const_logic_1;
    read_payload_U0_ap_start <= p_channel_empty_n;
    read_payload_U0_fifo_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(fifo_fifo_cap),14))),32));
    read_payload_U0_fifo_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(fifo_num_data_valid),14))),32));
    station_id_read <= entry_proc_U0_station_id_read;
    thread_id_read <= entry_proc_U0_thread_id_read;
    timestamp_engine_U0_ap_continue <= ap_sync_channel_write_frame_no;
    timestamp_engine_U0_ap_start <= ((ap_sync_reg_timestamp_engine_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
end behav;
