-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_sample_packer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    adc_in_TVALID : IN STD_LOGIC;
    adc_in_TREADY : OUT STD_LOGIC;
    packed_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    packed_stream_full_n : IN STD_LOGIC;
    packed_stream_write : OUT STD_LOGIC;
    bits_per_sample : IN STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of vdif_chain_sample_packer is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal packed_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_idle : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_ready : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out_ap_vld : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_idle : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_ready : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out_ap_vld : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_idle : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_ready : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out_ap_vld : STD_LOGIC;
    signal grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state3 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_sample_packer_Pipeline_VITIS_LOOP_47_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        adc_in_TVALID : IN STD_LOGIC;
        adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        adc_in_TREADY : OUT STD_LOGIC;
        word_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        word_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component vdif_chain_sample_packer_Pipeline_VITIS_LOOP_34_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        adc_in_TVALID : IN STD_LOGIC;
        adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        adc_in_TREADY : OUT STD_LOGIC;
        word_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        word_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component vdif_chain_sample_packer_Pipeline_VITIS_LOOP_21_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        adc_in_TVALID : IN STD_LOGIC;
        adc_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        adc_in_TREADY : OUT STD_LOGIC;
        word_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        word_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67 : component vdif_chain_sample_packer_Pipeline_VITIS_LOOP_47_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start,
        ap_done => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done,
        ap_idle => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_idle,
        ap_ready => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_ready,
        adc_in_TVALID => adc_in_TVALID,
        adc_in_TDATA => adc_in_TDATA,
        adc_in_TREADY => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY,
        word_4_out => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out,
        word_4_out_ap_vld => grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out_ap_vld);

    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74 : component vdif_chain_sample_packer_Pipeline_VITIS_LOOP_34_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start,
        ap_done => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done,
        ap_idle => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_idle,
        ap_ready => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_ready,
        adc_in_TVALID => adc_in_TVALID,
        adc_in_TDATA => adc_in_TDATA,
        adc_in_TREADY => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY,
        word_2_out => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out,
        word_2_out_ap_vld => grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out_ap_vld);

    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81 : component vdif_chain_sample_packer_Pipeline_VITIS_LOOP_21_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start,
        ap_done => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done,
        ap_idle => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_idle,
        ap_ready => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_ready,
        adc_in_TVALID => adc_in_TVALID,
        adc_in_TDATA => adc_in_TDATA,
        adc_in_TREADY => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY,
        word_out => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out,
        word_out_ap_vld => grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (bits_per_sample = ap_const_lv5_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_ready = ap_const_logic_1)) then 
                    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (bits_per_sample = ap_const_lv5_4) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (bits_per_sample = ap_const_lv5_8) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_ready = ap_const_logic_1)) then 
                    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, bits_per_sample, ap_CS_fsm_state3, ap_CS_fsm_state2, ap_block_state3, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not((bits_per_sample = ap_const_lv5_8)) and not((bits_per_sample = ap_const_lv5_4)) and not((bits_per_sample = ap_const_lv5_2)) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((bits_per_sample = ap_const_lv5_2) or ((bits_per_sample = ap_const_lv5_8) or (bits_per_sample = ap_const_lv5_4))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done) and ((bits_per_sample = ap_const_lv5_2) or ((bits_per_sample = ap_const_lv5_8) or (bits_per_sample = ap_const_lv5_4))))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    adc_in_TREADY_assign_proc : process(bits_per_sample, grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY, grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY, grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((bits_per_sample = ap_const_lv5_2)) then 
                adc_in_TREADY <= grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY;
            elsif ((bits_per_sample = ap_const_lv5_4)) then 
                adc_in_TREADY <= grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY;
            elsif ((bits_per_sample = ap_const_lv5_8)) then 
                adc_in_TREADY <= grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY;
            else 
                adc_in_TREADY <= ap_const_logic_0;
            end if;
        else 
            adc_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(bits_per_sample, grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done, grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done, grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done)
    begin
                ap_block_state2_on_subcall_done <= (((grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done = ap_const_logic_0) and (bits_per_sample = ap_const_lv5_2)) or ((grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done = ap_const_logic_0) and (bits_per_sample = ap_const_lv5_4)) or ((grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done = ap_const_logic_0) and (bits_per_sample = ap_const_lv5_8)));
    end process;


    ap_block_state3_assign_proc : process(packed_stream_full_n, bits_per_sample)
    begin
                ap_block_state3 <= (((bits_per_sample = ap_const_lv5_8) and (packed_stream_full_n = ap_const_logic_0)) or ((bits_per_sample = ap_const_lv5_4) and (packed_stream_full_n = ap_const_logic_0)) or ((bits_per_sample = ap_const_lv5_2) and (packed_stream_full_n = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_block_state3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start <= grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg;
    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start <= grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg;
    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start <= grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg;

    packed_stream_blk_n_assign_proc : process(packed_stream_full_n, bits_per_sample, ap_CS_fsm_state3)
    begin
        if ((((bits_per_sample = ap_const_lv5_8) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((bits_per_sample = ap_const_lv5_4) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((bits_per_sample = ap_const_lv5_2) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            packed_stream_blk_n <= packed_stream_full_n;
        else 
            packed_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    packed_stream_din_assign_proc : process(bits_per_sample, ap_CS_fsm_state3, grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out, grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out, grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out, ap_block_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then
            if ((bits_per_sample = ap_const_lv5_2)) then 
                packed_stream_din <= grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out;
            elsif ((bits_per_sample = ap_const_lv5_4)) then 
                packed_stream_din <= grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out;
            elsif ((bits_per_sample = ap_const_lv5_8)) then 
                packed_stream_din <= grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out;
            else 
                packed_stream_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            packed_stream_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    packed_stream_write_assign_proc : process(bits_per_sample, ap_CS_fsm_state3, ap_block_state3)
    begin
        if ((((bits_per_sample = ap_const_lv5_8) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3)) or ((bits_per_sample = ap_const_lv5_4) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3)) or ((bits_per_sample = ap_const_lv5_2) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3)))) then 
            packed_stream_write <= ap_const_logic_1;
        else 
            packed_stream_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
