-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vdif_chain_write_payload is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fifo_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifo_empty_n : IN STD_LOGIC;
    fifo_read : OUT STD_LOGIC;
    fifo_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
    fifo_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    payload_words : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of vdif_chain_write_payload is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln22_fu_65_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln22_reg_77 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_idle : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_ready : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_fifo_read : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TREADY : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID : STD_LOGIC;
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal out_stream_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_stream_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_stream_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln22_fu_61_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vdif_chain_write_payload_Pipeline_VITIS_LOOP_16_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fifo_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fifo_empty_n : IN STD_LOGIC;
        fifo_read : OUT STD_LOGIC;
        fifo_num_data_valid : IN STD_LOGIC_VECTOR (13 downto 0);
        fifo_fifo_cap : IN STD_LOGIC_VECTOR (13 downto 0);
        out_stream_TREADY : IN STD_LOGIC;
        payload_words : IN STD_LOGIC_VECTOR (15 downto 0);
        add_ln22 : IN STD_LOGIC_VECTOR (16 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44 : component vdif_chain_write_payload_Pipeline_VITIS_LOOP_16_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start,
        ap_done => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done,
        ap_idle => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_idle,
        ap_ready => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_ready,
        fifo_dout => fifo_dout,
        fifo_empty_n => fifo_empty_n,
        fifo_read => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_fifo_read,
        fifo_num_data_valid => ap_const_lv14_0,
        fifo_fifo_cap => ap_const_lv14_0,
        out_stream_TREADY => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TREADY,
        payload_words => payload_words,
        add_ln22 => add_ln22_reg_77,
        out_stream_TDATA => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA,
        out_stream_TVALID => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID,
        out_stream_TKEEP => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP,
        out_stream_TSTRB => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB,
        out_stream_TLAST => grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_ready = ap_const_logic_1)) then 
                    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln22_reg_77 <= add_ln22_fu_65_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                out_stream_TDATA_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA;
                out_stream_TKEEP_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP;
                out_stream_TLAST_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST;
                out_stream_TSTRB_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln22_fu_65_p2 <= std_logic_vector(unsigned(zext_ln22_fu_61_p1) + unsigned(ap_const_lv17_1FFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done)
    begin
        if ((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    fifo_read <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_fifo_read;
    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg;
    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TREADY <= (out_stream_TREADY and ap_CS_fsm_state2);

    out_stream_TDATA_assign_proc : process(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA, grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID, ap_CS_fsm_state2, out_stream_TDATA_reg)
    begin
        if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TDATA <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA;
        else 
            out_stream_TDATA <= out_stream_TDATA_reg;
        end if; 
    end process;


    out_stream_TKEEP_assign_proc : process(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID, grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP, ap_CS_fsm_state2, out_stream_TKEEP_reg)
    begin
        if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TKEEP <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP;
        else 
            out_stream_TKEEP <= out_stream_TKEEP_reg;
        end if; 
    end process;


    out_stream_TLAST_assign_proc : process(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID, grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST, ap_CS_fsm_state2, out_stream_TLAST_reg)
    begin
        if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TLAST <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST;
        else 
            out_stream_TLAST <= out_stream_TLAST_reg;
        end if; 
    end process;


    out_stream_TSTRB_assign_proc : process(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID, grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB, ap_CS_fsm_state2, out_stream_TSTRB_reg)
    begin
        if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_stream_TSTRB <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB;
        else 
            out_stream_TSTRB <= out_stream_TSTRB_reg;
        end if; 
    end process;

    out_stream_TVALID <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID;
    zext_ln22_fu_61_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(payload_words),17));
end behav;
