

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "15", "50", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64"],
		"CDFG" : "vdif_chain",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1028", "EstimateLatencyMax" : "1507306",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "1", "Name" : "entry_proc7_U0"},
			{"ID" : "2", "Name" : "Loop_VITIS_LOOP_79_1_proc_U0"}],
		"OutputProcess" : [
			{"ID" : "15", "Name" : "packetizer_U0"},
			{"ID" : "50", "Name" : "axis_bram_writer_U0"}],
		"Port" : [
			{"Name" : "adc_in", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "Loop_VITIS_LOOP_79_1_proc_U0", "Port" : "adc_in"}]},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "out_stream_V_data_V"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "out_stream_V_keep_V"}]},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "out_stream_V_strb_V"}]},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "out_stream_V_last_V"}]},
			{"Name" : "epoch", "Type" : "None", "Direction" : "I"},
			{"Name" : "station_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "thread_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "bits_per_sample", "Type" : "None", "Direction" : "I"},
			{"Name" : "complex_data", "Type" : "None", "Direction" : "I"},
			{"Name" : "pps", "Type" : "None", "Direction" : "I"},
			{"Name" : "payload_words", "Type" : "None", "Direction" : "I"},
			{"Name" : "second_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "second_counter"}]},
			{"Name" : "frame_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "frame_counter"}]},
			{"Name" : "fsm_state", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "packetizer_U0", "Port" : "fsm_state"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc7_U0", "Parent" : "0",
		"CDFG" : "entry_proc7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "epoch", "Type" : "None", "Direction" : "I"},
			{"Name" : "epoch_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","17"], "DependentChan" : "53", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "epoch_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "station_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "station_id_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","17"], "DependentChan" : "54", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "station_id_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "thread_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "thread_id_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","17"], "DependentChan" : "55", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "thread_id_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "complex_data", "Type" : "None", "Direction" : "I"},
			{"Name" : "complex_data_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","17"], "DependentChan" : "56", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "complex_data_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "pps", "Type" : "None", "Direction" : "I"},
			{"Name" : "pps_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","18"], "DependentChan" : "57", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "pps_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0", "Parent" : "0", "Child" : ["3", "13", "14"],
		"CDFG" : "Loop_VITIS_LOOP_79_1_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1507306",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "payload_words", "Type" : "None", "Direction" : "I"},
			{"Name" : "adc_in", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_sample_packer_fu_147", "Port" : "adc_in", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "bits_per_sample", "Type" : "None", "Direction" : "I"},
			{"Name" : "packetizer_in", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","27"], "DependentChan" : "58", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "packetizer_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "bram_stream", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["50"], "DependentChan" : "59", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "bram_stream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "bits_per_sample_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","17"], "DependentChan" : "60", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "bits_per_sample_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "payload_words_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["50"], "DependentChan" : "61", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "payload_words_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "payload_words_c1", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["15","17"], "DependentChan" : "62", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "payload_words_c1_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_79_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147", "Parent" : "2", "Child" : ["4", "7", "10"],
		"CDFG" : "sample_packer",
		"Protocol" : "ap_ctrl_none",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "20",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "adc_in", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67", "Port" : "adc_in", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "7", "SubInstance" : "grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74", "Port" : "adc_in", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "10", "SubInstance" : "grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81", "Port" : "adc_in", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "packed_stream", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "packed_stream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "bits_per_sample", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "4", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67", "Parent" : "3", "Child" : ["5", "6"],
		"CDFG" : "sample_packer_Pipeline_VITIS_LOOP_47_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "adc_in", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "adc_in_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "word_4_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_47_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "5", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67.partset_32ns_32ns_8ns_5ns_32_1_1_U11", "Parent" : "4"},
	{"ID" : "6", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67.flow_control_loop_pipe_sequential_init_U", "Parent" : "4"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74", "Parent" : "3", "Child" : ["8", "9"],
		"CDFG" : "sample_packer_Pipeline_VITIS_LOOP_34_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "adc_in", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "adc_in_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "word_2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_34_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "8", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74.partset_32ns_32ns_4ns_5ns_32_1_1_U15", "Parent" : "7"},
	{"ID" : "9", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74.flow_control_loop_pipe_sequential_init_U", "Parent" : "7"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81", "Parent" : "3", "Child" : ["11", "12"],
		"CDFG" : "sample_packer_Pipeline_VITIS_LOOP_21_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "adc_in", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "adc_in_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "word_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_21_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "11", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81.partset_32ns_32ns_2ns_5ns_32_1_1_U19", "Parent" : "10"},
	{"ID" : "12", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.grp_sample_packer_fu_147.grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81.flow_control_loop_pipe_sequential_init_U", "Parent" : "10"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.packed_stream_fifo_U", "Parent" : "2"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_79_1_proc_U0.regslice_both_adc_in_U", "Parent" : "2"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.packetizer_U0", "Parent" : "0", "Child" : ["16", "17", "18", "19", "26", "27", "29", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49"],
		"CDFG" : "packetizer",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1027", "EstimateLatencyMax" : "65558",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "1",
		"StartFifo" : "start_for_packetizer_U0_U",
		"InputProcess" : [
			{"ID" : "17", "Name" : "entry_proc_U0"},
			{"ID" : "18", "Name" : "timestamp_engine_U0"},
			{"ID" : "19", "Name" : "packetizer_Block_entry_fsm_state_fb_proc_U0"}],
		"OutputProcess" : [
			{"ID" : "19", "Name" : "packetizer_Block_entry_fsm_state_fb_proc_U0"},
			{"ID" : "29", "Name" : "packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0"}],
		"Port" : [
			{"Name" : "packetizer_in", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "58", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "read_payload_U0", "Port" : "packetizer_in"}]},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0", "Port" : "out_stream_V_data_V"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0", "Port" : "out_stream_V_keep_V"}]},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0", "Port" : "out_stream_V_strb_V"}]},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0", "Port" : "out_stream_V_last_V"}]},
			{"Name" : "epoch", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "53", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "entry_proc_U0", "Port" : "epoch"}]},
			{"Name" : "station_id", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "54", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "entry_proc_U0", "Port" : "station_id"}]},
			{"Name" : "thread_id", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "55", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "entry_proc_U0", "Port" : "thread_id"}]},
			{"Name" : "bits_per_sample", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "60", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "entry_proc_U0", "Port" : "bits_per_sample"}]},
			{"Name" : "complex_data", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "56", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "entry_proc_U0", "Port" : "complex_data"}]},
			{"Name" : "pps", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "57", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "timestamp_engine_U0", "Port" : "pps"}]},
			{"Name" : "payload_words", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "62", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "entry_proc_U0", "Port" : "payload_words"}]},
			{"Name" : "second_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "timestamp_engine_U0", "Port" : "second_counter"}]},
			{"Name" : "frame_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "timestamp_engine_U0", "Port" : "frame_counter"}]},
			{"Name" : "fsm_state", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "packetizer_Block_entry_fsm_state_fb_proc_U0", "Port" : "fsm_state"}]}]},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.header_U", "Parent" : "15"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.entry_proc_U0", "Parent" : "15",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "return_r", "Type" : "None", "Direction" : "O", "DependentProc" : ["27"], "DependentChan" : "39", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "epoch", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "53", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "epoch_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "epoch_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["26"], "DependentChan" : "40", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "epoch_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "station_id", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "54", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "station_id_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "station_id_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["26"], "DependentChan" : "41", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "station_id_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "thread_id", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "55", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "thread_id_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "thread_id_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["26"], "DependentChan" : "42", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "thread_id_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "bits_per_sample", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "60", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "bits_per_sample_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "bits_per_sample_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["26"], "DependentChan" : "43", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "bits_per_sample_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "complex_data", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "56", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "complex_data_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "complex_data_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["26"], "DependentChan" : "44", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "complex_data_c_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "payload_words", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "62", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "payload_words_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "payload_words_c1", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["26"], "DependentChan" : "45", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "payload_words_c1_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.timestamp_engine_U0", "Parent" : "15",
		"CDFG" : "timestamp_engine",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "pps", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["1"], "DependentChan" : "57", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "pps_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "second_counter", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "frame_counter", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0", "Parent" : "15", "Child" : ["20", "22", "24"],
		"CDFG" : "packetizer_Block_entry_fsm_state_fb_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "fsm_state", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0.next_state_assign_4_packet_fsm_1_fu_18", "Parent" : "19", "Child" : ["21"],
		"CDFG" : "packet_fsm_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "current_state", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "21", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0.next_state_assign_4_packet_fsm_1_fu_18.sparsemux_5_2_1_1_1_U50", "Parent" : "20"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0.next_state_assign_3_packet_fsm_2_fu_23", "Parent" : "19", "Child" : ["23"],
		"CDFG" : "packet_fsm_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "current_state", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "23", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0.next_state_assign_3_packet_fsm_2_fu_23.sparsemux_5_2_2_1_1_U53", "Parent" : "22"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0.next_state_assign_2_packet_fsm_fu_29", "Parent" : "19", "Child" : ["25"],
		"CDFG" : "packet_fsm",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "current_state", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "25", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_fsm_state_fb_proc_U0.next_state_assign_2_packet_fsm_fu_29.sparsemux_7_2_1_1_1_U56", "Parent" : "24"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.header_generator_U0", "Parent" : "15",
		"CDFG" : "header_generator",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "3",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["18"], "DependentChan" : "46", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I", "DependentProc" : ["18"], "DependentChan" : "47", "DependentChanDepth" : "2", "DependentChanType" : "1"},
			{"Name" : "epoch", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "40", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "epoch_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "station_id", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "41", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "station_id_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "thread_id", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "42", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "thread_id_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "bits_per_sample", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "43", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "bits_per_sample_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "complex_data", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "44", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "complex_data_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "payload_words", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "45", "DependentChanDepth" : "3", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "payload_words_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "header", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["29"], "DependentChan" : "16"}]},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.read_payload_U0", "Parent" : "15", "Child" : ["28"],
		"CDFG" : "read_payload",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1026", "EstimateLatencyMax" : "65537",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "packetizer_in", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "58", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "packetizer_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "fifo", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["29"], "DependentChan" : "49", "DependentChanDepth" : "8192", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "payload_words", "Type" : "None", "Direction" : "I", "DependentProc" : ["17"], "DependentChan" : "39", "DependentChanDepth" : "2", "DependentChanType" : "1"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_11_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.read_payload_U0.flow_control_loop_pipe_U", "Parent" : "27"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0", "Parent" : "15", "Child" : ["30", "32", "35", "36", "37", "38"],
		"CDFG" : "packetizer_Block_entry_out_stream_V_data_V_wr_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "17", "EstimateLatencyMax" : "65552",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "header", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["26"], "DependentChan" : "16",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_write_header_fu_50", "Port" : "header", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_write_header_fu_50", "Port" : "out_stream_V_data_V", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "32", "SubInstance" : "grp_write_payload_fu_64", "Port" : "out_stream_V_data_V", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_write_header_fu_50", "Port" : "out_stream_V_keep_V", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "32", "SubInstance" : "grp_write_payload_fu_64", "Port" : "out_stream_V_keep_V", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_write_header_fu_50", "Port" : "out_stream_V_strb_V", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "32", "SubInstance" : "grp_write_payload_fu_64", "Port" : "out_stream_V_strb_V", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_write_header_fu_50", "Port" : "out_stream_V_last_V", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "32", "SubInstance" : "grp_write_payload_fu_64", "Port" : "out_stream_V_last_V", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "fifo", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["27"], "DependentChan" : "49", "DependentChanDepth" : "8192", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "32", "SubInstance" : "grp_write_payload_fu_64", "Port" : "fifo", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_read", "Type" : "None", "Direction" : "I", "DependentProc" : ["26"], "DependentChan" : "48", "DependentChanDepth" : "2", "DependentChanType" : "1"}]},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.grp_write_header_fu_50", "Parent" : "29", "Child" : ["31"],
		"CDFG" : "write_header",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "header", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"BlockSignal" : [
					{"Name" : "out_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_15_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "31", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.grp_write_header_fu_50.flow_control_loop_pipe_sequential_init_U", "Parent" : "30"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.grp_write_payload_fu_64", "Parent" : "29", "Child" : ["33"],
		"CDFG" : "write_payload",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3", "EstimateLatencyMax" : "65538",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "fifo", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "33", "SubInstance" : "grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44", "Port" : "fifo", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "33", "SubInstance" : "grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44", "Port" : "out_stream_V_data_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "33", "SubInstance" : "grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44", "Port" : "out_stream_V_keep_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "33", "SubInstance" : "grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44", "Port" : "out_stream_V_strb_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"SubConnect" : [
					{"ID" : "33", "SubInstance" : "grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44", "Port" : "out_stream_V_last_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "payload_words", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "33", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.grp_write_payload_fu_64.grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44", "Parent" : "32", "Child" : ["34"],
		"CDFG" : "write_payload_Pipeline_VITIS_LOOP_16_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "65537",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "payload_words", "Type" : "None", "Direction" : "I"},
			{"Name" : "fifo", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "add_ln22", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"BlockSignal" : [
					{"Name" : "out_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_16_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "34", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.grp_write_payload_fu_64.grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44.flow_control_loop_pipe_sequential_init_U", "Parent" : "33"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.regslice_both_out_stream_V_data_V_U", "Parent" : "29"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.regslice_both_out_stream_V_keep_V_U", "Parent" : "29"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.regslice_both_out_stream_V_strb_V_U", "Parent" : "29"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0.regslice_both_out_stream_V_last_V_U", "Parent" : "29"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.p_channel_U", "Parent" : "15"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.epoch_c_U", "Parent" : "15"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.station_id_c_U", "Parent" : "15"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.thread_id_c_U", "Parent" : "15"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.bits_per_sample_c_U", "Parent" : "15"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.complex_data_c_U", "Parent" : "15"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.payload_words_c1_U", "Parent" : "15"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.seconds_from_epoch_U", "Parent" : "15"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.frame_no_U", "Parent" : "15"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.payload_words_c_channel_U", "Parent" : "15"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.packetizer_U0.fifo_U", "Parent" : "15"},
	{"ID" : "50", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.axis_bram_writer_U0", "Parent" : "0", "Child" : ["51"],
		"CDFG" : "axis_bram_writer",
		"Protocol" : "ap_ctrl_none",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "65539",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "2",
		"StartFifo" : "start_for_axis_bram_writer_U0_U",
		"Port" : [
			{"Name" : "bram_stream", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "59", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "grp_axis_bram_writer_Pipeline_VITIS_LOOP_15_1_fu_36", "Port" : "bram_stream", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "payload_words_0_0_0", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["2"], "DependentChan" : "61", "DependentChanDepth" : "2", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "payload_words_0_0_0_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.axis_bram_writer_U0.grp_axis_bram_writer_Pipeline_VITIS_LOOP_15_1_fu_36", "Parent" : "50", "Child" : ["52"],
		"CDFG" : "axis_bram_writer_Pipeline_VITIS_LOOP_15_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "65537",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "payload_words", "Type" : "None", "Direction" : "I"},
			{"Name" : "bram_stream", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "bram_stream_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_15_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.axis_bram_writer_U0.grp_axis_bram_writer_Pipeline_VITIS_LOOP_15_1_fu_36.flow_control_loop_pipe_sequential_init_U", "Parent" : "51"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.epoch_c_U", "Parent" : "0"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.station_id_c_U", "Parent" : "0"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.thread_id_c_U", "Parent" : "0"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.complex_data_c_U", "Parent" : "0"},
	{"ID" : "57", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pps_c_U", "Parent" : "0"},
	{"ID" : "58", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.packetizer_in_U", "Parent" : "0"},
	{"ID" : "59", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bram_stream_U", "Parent" : "0"},
	{"ID" : "60", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bits_per_sample_c_U", "Parent" : "0"},
	{"ID" : "61", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.payload_words_c_U", "Parent" : "0"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.payload_words_c1_U", "Parent" : "0"},
	{"ID" : "63", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_packetizer_U0_U", "Parent" : "0"},
	{"ID" : "64", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_axis_bram_writer_U0_U", "Parent" : "0"}]}
