// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_packet_fsm (
        ap_ready,
        current_state,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [1:0] current_state;
output  [0:0] ap_return;
input   ap_rst;

wire   [0:0] trunc_ln18_fu_20_p1;
wire   [0:0] next_state_write_assign_fu_24_p9;
wire   [1:0] next_state_write_assign_fu_24_p1;
wire   [1:0] next_state_write_assign_fu_24_p3;
wire  signed [1:0] next_state_write_assign_fu_24_p5;

(* dissolve_hierarchy = "yes" *) vdif_chain_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U54(
    .din0(trunc_ln18_fu_20_p1),
    .din1(trunc_ln18_fu_20_p1),
    .din2(1'd0),
    .def(1'd0),
    .sel(current_state),
    .dout(next_state_write_assign_fu_24_p9)
);

assign ap_ready = 1'b1;

assign trunc_ln18_fu_20_p1 = current_state[0:0];

assign ap_return = next_state_write_assign_fu_24_p9;

endmodule //vdif_chain_packet_fsm
