// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_packetizer (
        ap_clk,
        ap_rst,
        packetizer_in_dout,
        packetizer_in_empty_n,
        packetizer_in_read,
        out_stream_TDATA,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        epoch_dout,
        epoch_empty_n,
        epoch_read,
        station_id_dout,
        station_id_empty_n,
        station_id_read,
        thread_id_dout,
        thread_id_empty_n,
        thread_id_read,
        bits_per_sample_dout,
        bits_per_sample_empty_n,
        bits_per_sample_read,
        complex_data_dout,
        complex_data_empty_n,
        complex_data_read,
        pps_dout,
        pps_empty_n,
        pps_read,
        payload_words_dout,
        payload_words_empty_n,
        payload_words_read,
        ap_start,
        ap_done,
        out_stream_TVALID,
        out_stream_TREADY,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [31:0] packetizer_in_dout;
input   packetizer_in_empty_n;
output   packetizer_in_read;
output  [31:0] out_stream_TDATA;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input  [5:0] epoch_dout;
input   epoch_empty_n;
output   epoch_read;
input  [15:0] station_id_dout;
input   station_id_empty_n;
output   station_id_read;
input  [9:0] thread_id_dout;
input   thread_id_empty_n;
output   thread_id_read;
input  [4:0] bits_per_sample_dout;
input   bits_per_sample_empty_n;
output   bits_per_sample_read;
input  [0:0] complex_data_dout;
input   complex_data_empty_n;
output   complex_data_read;
input  [0:0] pps_dout;
input   pps_empty_n;
output   pps_read;
input  [15:0] payload_words_dout;
input   payload_words_empty_n;
output   payload_words_read;
input   ap_start;
output   ap_done;
output   out_stream_TVALID;
input   out_stream_TREADY;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [31:0] header_i_q0;
wire   [31:0] header_t_q0;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [15:0] entry_proc_U0_return_r;
wire    entry_proc_U0_epoch_read;
wire   [5:0] entry_proc_U0_epoch_c_din;
wire    entry_proc_U0_epoch_c_write;
wire    entry_proc_U0_station_id_read;
wire   [15:0] entry_proc_U0_station_id_c_din;
wire    entry_proc_U0_station_id_c_write;
wire    entry_proc_U0_thread_id_read;
wire   [9:0] entry_proc_U0_thread_id_c_din;
wire    entry_proc_U0_thread_id_c_write;
wire    entry_proc_U0_bits_per_sample_read;
wire   [4:0] entry_proc_U0_bits_per_sample_c_din;
wire    entry_proc_U0_bits_per_sample_c_write;
wire    entry_proc_U0_complex_data_read;
wire   [0:0] entry_proc_U0_complex_data_c_din;
wire    entry_proc_U0_complex_data_c_write;
wire    entry_proc_U0_payload_words_read;
wire   [15:0] entry_proc_U0_payload_words_c1_din;
wire    entry_proc_U0_payload_words_c1_write;
wire    p_channel_full_n;
wire    timestamp_engine_U0_ap_start;
wire    timestamp_engine_U0_ap_done;
wire    timestamp_engine_U0_ap_continue;
wire    timestamp_engine_U0_ap_idle;
wire    timestamp_engine_U0_ap_ready;
wire    timestamp_engine_U0_pps_read;
wire   [29:0] timestamp_engine_U0_ap_return_0;
wire   [23:0] timestamp_engine_U0_ap_return_1;
wire    ap_channel_done_frame_no;
wire    frame_no_full_n;
reg    ap_sync_reg_channel_write_frame_no;
wire    ap_sync_channel_write_frame_no;
wire    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_start;
wire    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_done;
wire    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_continue;
wire    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_idle;
wire    packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready;
wire    ap_sync_continue;
wire    header_generator_U0_ap_start;
wire    header_generator_U0_ap_done;
wire    header_generator_U0_ap_continue;
wire    header_generator_U0_ap_idle;
wire    header_generator_U0_ap_ready;
wire    header_generator_U0_epoch_read;
wire    header_generator_U0_station_id_read;
wire    header_generator_U0_thread_id_read;
wire    header_generator_U0_bits_per_sample_read;
wire    header_generator_U0_complex_data_read;
wire    header_generator_U0_payload_words_read;
wire   [2:0] header_generator_U0_header_address0;
wire    header_generator_U0_header_ce0;
wire    header_generator_U0_header_we0;
wire   [31:0] header_generator_U0_header_d0;
wire   [2:0] header_generator_U0_header_address1;
wire    header_generator_U0_header_ce1;
wire    header_generator_U0_header_we1;
wire   [31:0] header_generator_U0_header_d1;
wire   [15:0] header_generator_U0_ap_return;
wire    ap_channel_done_payload_words_c_channel;
wire    payload_words_c_channel_full_n;
reg    ap_sync_reg_channel_write_payload_words_c_channel;
wire    ap_sync_channel_write_payload_words_c_channel;
wire    ap_channel_done_header;
wire    header_generator_U0_header_full_n;
reg    ap_sync_reg_channel_write_header;
wire    ap_sync_channel_write_header;
wire    read_payload_U0_ap_start;
wire    read_payload_U0_ap_done;
wire    read_payload_U0_ap_continue;
wire    read_payload_U0_ap_idle;
wire    read_payload_U0_ap_ready;
wire    read_payload_U0_packetizer_in_read;
wire   [31:0] read_payload_U0_fifo_din;
wire    read_payload_U0_fifo_write;
wire   [31:0] read_payload_U0_fifo_num_data_valid;
wire   [31:0] read_payload_U0_fifo_fifo_cap;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_start;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_done;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_continue;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_idle;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready;
wire   [2:0] packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_address0;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_ce0;
wire   [31:0] packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TDATA;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TVALID;
wire   [3:0] packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TKEEP;
wire   [3:0] packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TSTRB;
wire   [0:0] packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TLAST;
wire    packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_fifo_read;
wire    header_i_full_n;
wire    header_t_empty_n;
wire   [15:0] p_channel_dout;
wire    p_channel_empty_n;
wire   [2:0] p_channel_num_data_valid;
wire   [2:0] p_channel_fifo_cap;
wire    epoch_c_full_n;
wire   [5:0] epoch_c_dout;
wire    epoch_c_empty_n;
wire   [2:0] epoch_c_num_data_valid;
wire   [2:0] epoch_c_fifo_cap;
wire    station_id_c_full_n;
wire   [15:0] station_id_c_dout;
wire    station_id_c_empty_n;
wire   [2:0] station_id_c_num_data_valid;
wire   [2:0] station_id_c_fifo_cap;
wire    thread_id_c_full_n;
wire   [9:0] thread_id_c_dout;
wire    thread_id_c_empty_n;
wire   [2:0] thread_id_c_num_data_valid;
wire   [2:0] thread_id_c_fifo_cap;
wire    bits_per_sample_c_full_n;
wire   [4:0] bits_per_sample_c_dout;
wire    bits_per_sample_c_empty_n;
wire   [2:0] bits_per_sample_c_num_data_valid;
wire   [2:0] bits_per_sample_c_fifo_cap;
wire    complex_data_c_full_n;
wire   [0:0] complex_data_c_dout;
wire    complex_data_c_empty_n;
wire   [2:0] complex_data_c_num_data_valid;
wire   [2:0] complex_data_c_fifo_cap;
wire    payload_words_c1_full_n;
wire   [15:0] payload_words_c1_dout;
wire    payload_words_c1_empty_n;
wire   [2:0] payload_words_c1_num_data_valid;
wire   [2:0] payload_words_c1_fifo_cap;
wire    seconds_from_epoch_full_n;
wire   [29:0] seconds_from_epoch_dout;
wire    seconds_from_epoch_empty_n;
wire   [2:0] seconds_from_epoch_num_data_valid;
wire   [2:0] seconds_from_epoch_fifo_cap;
wire   [23:0] frame_no_dout;
wire    frame_no_empty_n;
wire   [2:0] frame_no_num_data_valid;
wire   [2:0] frame_no_fifo_cap;
wire   [15:0] payload_words_c_channel_dout;
wire    payload_words_c_channel_empty_n;
wire   [2:0] payload_words_c_channel_num_data_valid;
wire   [2:0] payload_words_c_channel_fifo_cap;
wire    fifo_full_n;
wire   [31:0] fifo_dout;
wire    fifo_empty_n;
wire   [13:0] fifo_num_data_valid;
wire   [13:0] fifo_fifo_cap;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_timestamp_engine_U0_ap_ready;
wire    ap_sync_timestamp_engine_U0_ap_ready;
reg    ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready;
wire    ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_frame_no = 1'b0;
#0 ap_sync_reg_channel_write_payload_words_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_header = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_timestamp_engine_U0_ap_ready = 1'b0;
#0 ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready = 1'b0;
end

vdif_chain_packetizer_header_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
header_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(header_generator_U0_header_address0),
    .i_ce0(header_generator_U0_header_ce0),
    .i_we0(header_generator_U0_header_we0),
    .i_d0(header_generator_U0_header_d0),
    .i_q0(header_i_q0),
    .i_address1(header_generator_U0_header_address1),
    .i_ce1(header_generator_U0_header_ce1),
    .i_we1(header_generator_U0_header_we1),
    .i_d1(header_generator_U0_header_d1),
    .t_address0(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_address0),
    .t_ce0(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(header_t_q0),
    .t_address1(3'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(32'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(header_i_full_n),
    .i_write(ap_channel_done_header),
    .t_empty_n(header_t_empty_n),
    .t_read(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready)
);

vdif_chain_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .return_r(entry_proc_U0_return_r),
    .epoch_dout(epoch_dout),
    .epoch_empty_n(epoch_empty_n),
    .epoch_read(entry_proc_U0_epoch_read),
    .epoch_num_data_valid(3'd0),
    .epoch_fifo_cap(3'd0),
    .epoch_c_din(entry_proc_U0_epoch_c_din),
    .epoch_c_full_n(epoch_c_full_n),
    .epoch_c_write(entry_proc_U0_epoch_c_write),
    .epoch_c_num_data_valid(epoch_c_num_data_valid),
    .epoch_c_fifo_cap(epoch_c_fifo_cap),
    .station_id_dout(station_id_dout),
    .station_id_empty_n(station_id_empty_n),
    .station_id_read(entry_proc_U0_station_id_read),
    .station_id_num_data_valid(3'd0),
    .station_id_fifo_cap(3'd0),
    .station_id_c_din(entry_proc_U0_station_id_c_din),
    .station_id_c_full_n(station_id_c_full_n),
    .station_id_c_write(entry_proc_U0_station_id_c_write),
    .station_id_c_num_data_valid(station_id_c_num_data_valid),
    .station_id_c_fifo_cap(station_id_c_fifo_cap),
    .thread_id_dout(thread_id_dout),
    .thread_id_empty_n(thread_id_empty_n),
    .thread_id_read(entry_proc_U0_thread_id_read),
    .thread_id_num_data_valid(3'd0),
    .thread_id_fifo_cap(3'd0),
    .thread_id_c_din(entry_proc_U0_thread_id_c_din),
    .thread_id_c_full_n(thread_id_c_full_n),
    .thread_id_c_write(entry_proc_U0_thread_id_c_write),
    .thread_id_c_num_data_valid(thread_id_c_num_data_valid),
    .thread_id_c_fifo_cap(thread_id_c_fifo_cap),
    .bits_per_sample_dout(bits_per_sample_dout),
    .bits_per_sample_empty_n(bits_per_sample_empty_n),
    .bits_per_sample_read(entry_proc_U0_bits_per_sample_read),
    .bits_per_sample_num_data_valid(3'd0),
    .bits_per_sample_fifo_cap(3'd0),
    .bits_per_sample_c_din(entry_proc_U0_bits_per_sample_c_din),
    .bits_per_sample_c_full_n(bits_per_sample_c_full_n),
    .bits_per_sample_c_write(entry_proc_U0_bits_per_sample_c_write),
    .bits_per_sample_c_num_data_valid(bits_per_sample_c_num_data_valid),
    .bits_per_sample_c_fifo_cap(bits_per_sample_c_fifo_cap),
    .complex_data_dout(complex_data_dout),
    .complex_data_empty_n(complex_data_empty_n),
    .complex_data_read(entry_proc_U0_complex_data_read),
    .complex_data_num_data_valid(3'd0),
    .complex_data_fifo_cap(3'd0),
    .complex_data_c_din(entry_proc_U0_complex_data_c_din),
    .complex_data_c_full_n(complex_data_c_full_n),
    .complex_data_c_write(entry_proc_U0_complex_data_c_write),
    .complex_data_c_num_data_valid(complex_data_c_num_data_valid),
    .complex_data_c_fifo_cap(complex_data_c_fifo_cap),
    .payload_words_dout(payload_words_dout),
    .payload_words_empty_n(payload_words_empty_n),
    .payload_words_read(entry_proc_U0_payload_words_read),
    .payload_words_num_data_valid(3'd0),
    .payload_words_fifo_cap(3'd0),
    .payload_words_c1_din(entry_proc_U0_payload_words_c1_din),
    .payload_words_c1_full_n(payload_words_c1_full_n),
    .payload_words_c1_write(entry_proc_U0_payload_words_c1_write),
    .payload_words_c1_num_data_valid(payload_words_c1_num_data_valid),
    .payload_words_c1_fifo_cap(payload_words_c1_fifo_cap)
);

vdif_chain_timestamp_engine timestamp_engine_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(timestamp_engine_U0_ap_start),
    .ap_done(timestamp_engine_U0_ap_done),
    .ap_continue(timestamp_engine_U0_ap_continue),
    .ap_idle(timestamp_engine_U0_ap_idle),
    .ap_ready(timestamp_engine_U0_ap_ready),
    .pps_dout(pps_dout),
    .pps_empty_n(pps_empty_n),
    .pps_read(timestamp_engine_U0_pps_read),
    .pps_num_data_valid(3'd0),
    .pps_fifo_cap(3'd0),
    .ap_return_0(timestamp_engine_U0_ap_return_0),
    .ap_return_1(timestamp_engine_U0_ap_return_1)
);

vdif_chain_packetizer_Block_entry_fsm_state_fb_proc packetizer_Block_entry_fsm_state_fb_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(packetizer_Block_entry_fsm_state_fb_proc_U0_ap_start),
    .ap_done(packetizer_Block_entry_fsm_state_fb_proc_U0_ap_done),
    .ap_continue(packetizer_Block_entry_fsm_state_fb_proc_U0_ap_continue),
    .ap_idle(packetizer_Block_entry_fsm_state_fb_proc_U0_ap_idle),
    .ap_ready(packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready)
);

vdif_chain_header_generator header_generator_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(header_generator_U0_ap_start),
    .ap_done(header_generator_U0_ap_done),
    .ap_continue(header_generator_U0_ap_continue),
    .ap_idle(header_generator_U0_ap_idle),
    .ap_ready(header_generator_U0_ap_ready),
    .p_read(seconds_from_epoch_dout),
    .p_read1(frame_no_dout),
    .epoch_dout(epoch_c_dout),
    .epoch_empty_n(epoch_c_empty_n),
    .epoch_read(header_generator_U0_epoch_read),
    .epoch_num_data_valid(epoch_c_num_data_valid),
    .epoch_fifo_cap(epoch_c_fifo_cap),
    .station_id_dout(station_id_c_dout),
    .station_id_empty_n(station_id_c_empty_n),
    .station_id_read(header_generator_U0_station_id_read),
    .station_id_num_data_valid(station_id_c_num_data_valid),
    .station_id_fifo_cap(station_id_c_fifo_cap),
    .thread_id_dout(thread_id_c_dout),
    .thread_id_empty_n(thread_id_c_empty_n),
    .thread_id_read(header_generator_U0_thread_id_read),
    .thread_id_num_data_valid(thread_id_c_num_data_valid),
    .thread_id_fifo_cap(thread_id_c_fifo_cap),
    .bits_per_sample_dout(bits_per_sample_c_dout),
    .bits_per_sample_empty_n(bits_per_sample_c_empty_n),
    .bits_per_sample_read(header_generator_U0_bits_per_sample_read),
    .bits_per_sample_num_data_valid(bits_per_sample_c_num_data_valid),
    .bits_per_sample_fifo_cap(bits_per_sample_c_fifo_cap),
    .complex_data_dout(complex_data_c_dout),
    .complex_data_empty_n(complex_data_c_empty_n),
    .complex_data_read(header_generator_U0_complex_data_read),
    .complex_data_num_data_valid(complex_data_c_num_data_valid),
    .complex_data_fifo_cap(complex_data_c_fifo_cap),
    .payload_words_dout(payload_words_c1_dout),
    .payload_words_empty_n(payload_words_c1_empty_n),
    .payload_words_read(header_generator_U0_payload_words_read),
    .payload_words_num_data_valid(payload_words_c1_num_data_valid),
    .payload_words_fifo_cap(payload_words_c1_fifo_cap),
    .header_address0(header_generator_U0_header_address0),
    .header_ce0(header_generator_U0_header_ce0),
    .header_we0(header_generator_U0_header_we0),
    .header_d0(header_generator_U0_header_d0),
    .header_address1(header_generator_U0_header_address1),
    .header_ce1(header_generator_U0_header_ce1),
    .header_we1(header_generator_U0_header_we1),
    .header_d1(header_generator_U0_header_d1),
    .ap_return(header_generator_U0_ap_return)
);

vdif_chain_read_payload read_payload_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_payload_U0_ap_start),
    .ap_done(read_payload_U0_ap_done),
    .ap_continue(read_payload_U0_ap_continue),
    .ap_idle(read_payload_U0_ap_idle),
    .ap_ready(read_payload_U0_ap_ready),
    .packetizer_in_dout(packetizer_in_dout),
    .packetizer_in_empty_n(packetizer_in_empty_n),
    .packetizer_in_read(read_payload_U0_packetizer_in_read),
    .packetizer_in_num_data_valid(12'd0),
    .packetizer_in_fifo_cap(12'd0),
    .fifo_din(read_payload_U0_fifo_din),
    .fifo_full_n(fifo_full_n),
    .fifo_write(read_payload_U0_fifo_write),
    .fifo_num_data_valid(read_payload_U0_fifo_num_data_valid),
    .fifo_fifo_cap(read_payload_U0_fifo_fifo_cap),
    .payload_words(p_channel_dout)
);

vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_start),
    .ap_done(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_done),
    .ap_continue(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_continue),
    .ap_idle(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_idle),
    .ap_ready(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready),
    .header_address0(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_address0),
    .header_ce0(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_header_ce0),
    .header_q0(header_t_q0),
    .out_stream_TDATA(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TDATA),
    .out_stream_TVALID(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TVALID),
    .out_stream_TREADY(out_stream_TREADY),
    .out_stream_TKEEP(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TKEEP),
    .out_stream_TSTRB(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TSTRB),
    .out_stream_TLAST(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TLAST),
    .fifo_dout(fifo_dout),
    .fifo_empty_n(fifo_empty_n),
    .fifo_read(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_fifo_read),
    .fifo_num_data_valid(fifo_num_data_valid),
    .fifo_fifo_cap(fifo_fifo_cap),
    .p_read(payload_words_c_channel_dout)
);

vdif_chain_fifo_w16_d2_S p_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_return_r),
    .if_full_n(p_channel_full_n),
    .if_write(entry_proc_U0_ap_done),
    .if_dout(p_channel_dout),
    .if_empty_n(p_channel_empty_n),
    .if_read(read_payload_U0_ap_ready),
    .if_num_data_valid(p_channel_num_data_valid),
    .if_fifo_cap(p_channel_fifo_cap)
);

vdif_chain_fifo_w6_d3_S epoch_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_epoch_c_din),
    .if_full_n(epoch_c_full_n),
    .if_write(entry_proc_U0_epoch_c_write),
    .if_dout(epoch_c_dout),
    .if_empty_n(epoch_c_empty_n),
    .if_read(header_generator_U0_epoch_read),
    .if_num_data_valid(epoch_c_num_data_valid),
    .if_fifo_cap(epoch_c_fifo_cap)
);

vdif_chain_fifo_w16_d3_S station_id_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_station_id_c_din),
    .if_full_n(station_id_c_full_n),
    .if_write(entry_proc_U0_station_id_c_write),
    .if_dout(station_id_c_dout),
    .if_empty_n(station_id_c_empty_n),
    .if_read(header_generator_U0_station_id_read),
    .if_num_data_valid(station_id_c_num_data_valid),
    .if_fifo_cap(station_id_c_fifo_cap)
);

vdif_chain_fifo_w10_d3_S thread_id_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_thread_id_c_din),
    .if_full_n(thread_id_c_full_n),
    .if_write(entry_proc_U0_thread_id_c_write),
    .if_dout(thread_id_c_dout),
    .if_empty_n(thread_id_c_empty_n),
    .if_read(header_generator_U0_thread_id_read),
    .if_num_data_valid(thread_id_c_num_data_valid),
    .if_fifo_cap(thread_id_c_fifo_cap)
);

vdif_chain_fifo_w5_d3_S bits_per_sample_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_bits_per_sample_c_din),
    .if_full_n(bits_per_sample_c_full_n),
    .if_write(entry_proc_U0_bits_per_sample_c_write),
    .if_dout(bits_per_sample_c_dout),
    .if_empty_n(bits_per_sample_c_empty_n),
    .if_read(header_generator_U0_bits_per_sample_read),
    .if_num_data_valid(bits_per_sample_c_num_data_valid),
    .if_fifo_cap(bits_per_sample_c_fifo_cap)
);

vdif_chain_fifo_w1_d3_S complex_data_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_complex_data_c_din),
    .if_full_n(complex_data_c_full_n),
    .if_write(entry_proc_U0_complex_data_c_write),
    .if_dout(complex_data_c_dout),
    .if_empty_n(complex_data_c_empty_n),
    .if_read(header_generator_U0_complex_data_read),
    .if_num_data_valid(complex_data_c_num_data_valid),
    .if_fifo_cap(complex_data_c_fifo_cap)
);

vdif_chain_fifo_w16_d3_S payload_words_c1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_payload_words_c1_din),
    .if_full_n(payload_words_c1_full_n),
    .if_write(entry_proc_U0_payload_words_c1_write),
    .if_dout(payload_words_c1_dout),
    .if_empty_n(payload_words_c1_empty_n),
    .if_read(header_generator_U0_payload_words_read),
    .if_num_data_valid(payload_words_c1_num_data_valid),
    .if_fifo_cap(payload_words_c1_fifo_cap)
);

vdif_chain_fifo_w30_d2_S seconds_from_epoch_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(timestamp_engine_U0_ap_return_0),
    .if_full_n(seconds_from_epoch_full_n),
    .if_write(ap_channel_done_frame_no),
    .if_dout(seconds_from_epoch_dout),
    .if_empty_n(seconds_from_epoch_empty_n),
    .if_read(header_generator_U0_ap_ready),
    .if_num_data_valid(seconds_from_epoch_num_data_valid),
    .if_fifo_cap(seconds_from_epoch_fifo_cap)
);

vdif_chain_fifo_w24_d2_S frame_no_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(timestamp_engine_U0_ap_return_1),
    .if_full_n(frame_no_full_n),
    .if_write(ap_channel_done_frame_no),
    .if_dout(frame_no_dout),
    .if_empty_n(frame_no_empty_n),
    .if_read(header_generator_U0_ap_ready),
    .if_num_data_valid(frame_no_num_data_valid),
    .if_fifo_cap(frame_no_fifo_cap)
);

vdif_chain_fifo_w16_d2_S payload_words_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(header_generator_U0_ap_return),
    .if_full_n(payload_words_c_channel_full_n),
    .if_write(ap_channel_done_payload_words_c_channel),
    .if_dout(payload_words_c_channel_dout),
    .if_empty_n(payload_words_c_channel_empty_n),
    .if_read(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_ready),
    .if_num_data_valid(payload_words_c_channel_num_data_valid),
    .if_fifo_cap(payload_words_c_channel_fifo_cap)
);

vdif_chain_fifo_w32_d8192_A fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_payload_U0_fifo_din),
    .if_full_n(fifo_full_n),
    .if_write(read_payload_U0_fifo_write),
    .if_dout(fifo_dout),
    .if_empty_n(fifo_empty_n),
    .if_read(packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_fifo_read),
    .if_num_data_valid(fifo_num_data_valid),
    .if_fifo_cap(fifo_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_frame_no <= 1'b0;
    end else begin
        if (((timestamp_engine_U0_ap_done & timestamp_engine_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_frame_no <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_frame_no <= ap_sync_channel_write_frame_no;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_header <= 1'b0;
    end else begin
        if (((header_generator_U0_ap_done & header_generator_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_header <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_header <= ap_sync_channel_write_header;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_payload_words_c_channel <= 1'b0;
    end else begin
        if (((header_generator_U0_ap_done & header_generator_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_payload_words_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_payload_words_c_channel <= ap_sync_channel_write_payload_words_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready <= ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_timestamp_engine_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_timestamp_engine_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_timestamp_engine_U0_ap_ready <= ap_sync_timestamp_engine_U0_ap_ready;
        end
    end
end

assign ap_channel_done_frame_no = (timestamp_engine_U0_ap_done & (ap_sync_reg_channel_write_frame_no ^ 1'b1));

assign ap_channel_done_header = (header_generator_U0_ap_done & (ap_sync_reg_channel_write_header ^ 1'b1));

assign ap_channel_done_payload_words_c_channel = (header_generator_U0_ap_done & (ap_sync_reg_channel_write_payload_words_c_channel ^ 1'b1));

assign ap_done = ap_sync_done;

assign ap_idle = (timestamp_engine_U0_ap_idle & read_payload_U0_ap_idle & packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_idle & packetizer_Block_entry_fsm_state_fb_proc_U0_ap_idle & header_generator_U0_ap_idle & (payload_words_c_channel_empty_n ^ 1'b1) & (seconds_from_epoch_empty_n ^ 1'b1) & (p_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_frame_no = ((frame_no_full_n & ap_channel_done_frame_no) | ap_sync_reg_channel_write_frame_no);

assign ap_sync_channel_write_header = ((header_generator_U0_header_full_n & ap_channel_done_header) | ap_sync_reg_channel_write_header);

assign ap_sync_channel_write_payload_words_c_channel = ((payload_words_c_channel_full_n & ap_channel_done_payload_words_c_channel) | ap_sync_reg_channel_write_payload_words_c_channel);

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_done & packetizer_Block_entry_fsm_state_fb_proc_U0_ap_done);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready = (packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready | ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_timestamp_engine_U0_ap_ready & ap_sync_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign ap_sync_timestamp_engine_U0_ap_ready = (timestamp_engine_U0_ap_ready | ap_sync_reg_timestamp_engine_U0_ap_ready);

assign bits_per_sample_read = entry_proc_U0_bits_per_sample_read;

assign complex_data_read = entry_proc_U0_complex_data_read;

assign entry_proc_U0_ap_continue = p_channel_full_n;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign epoch_read = entry_proc_U0_epoch_read;

assign header_generator_U0_ap_continue = ap_sync_channel_write_header;

assign header_generator_U0_ap_start = seconds_from_epoch_empty_n;

assign header_generator_U0_header_full_n = header_i_full_n;

assign out_stream_TDATA = packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TDATA;

assign out_stream_TKEEP = packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TKEEP;

assign out_stream_TLAST = packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TLAST;

assign out_stream_TSTRB = packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TSTRB;

assign out_stream_TVALID = packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_out_stream_TVALID;

assign packetizer_Block_entry_fsm_state_fb_proc_U0_ap_continue = ap_sync_continue;

assign packetizer_Block_entry_fsm_state_fb_proc_U0_ap_start = ((ap_sync_reg_packetizer_Block_entry_fsm_state_fb_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_continue = ap_sync_continue;

assign packetizer_Block_entry_out_stream_V_data_V_wr_proc_U0_ap_start = payload_words_c_channel_empty_n;

assign packetizer_in_read = read_payload_U0_packetizer_in_read;

assign payload_words_read = entry_proc_U0_payload_words_read;

assign pps_read = timestamp_engine_U0_pps_read;

assign read_payload_U0_ap_continue = 1'b1;

assign read_payload_U0_ap_start = p_channel_empty_n;

assign read_payload_U0_fifo_fifo_cap = fifo_fifo_cap;

assign read_payload_U0_fifo_num_data_valid = fifo_num_data_valid;

assign station_id_read = entry_proc_U0_station_id_read;

assign thread_id_read = entry_proc_U0_thread_id_read;

assign timestamp_engine_U0_ap_continue = ap_sync_channel_write_frame_no;

assign timestamp_engine_U0_ap_start = ((ap_sync_reg_timestamp_engine_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

endmodule //vdif_chain_packetizer
