// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_packet_fsm_2 (
        ap_ready,
        current_state,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [0:0] current_state;
output  [1:0] ap_return;
input   ap_rst;

wire   [1:0] next_state_write_assign_fu_22_p6;
wire   [1:0] next_state_write_assign_fu_22_p7;
wire   [1:0] next_state_write_assign_fu_22_p1;
wire   [1:0] next_state_write_assign_fu_22_p3;

(* dissolve_hierarchy = "yes" *) vdif_chain_sparsemux_5_2_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 2 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
sparsemux_5_2_2_1_1_U51(
    .din0(2'd0),
    .din1(2'd2),
    .def(2'd0),
    .sel(next_state_write_assign_fu_22_p6),
    .dout(next_state_write_assign_fu_22_p7)
);

assign ap_ready = 1'b1;

assign ap_return = next_state_write_assign_fu_22_p7;

assign next_state_write_assign_fu_22_p6 = current_state;

endmodule //vdif_chain_packet_fsm_2
