// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_Loop_VITIS_LOOP_71_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        payload_words,
        adc_in_TDATA,
        adc_in_TVALID,
        adc_in_TREADY,
        bits_per_sample,
        packetizer_in_din,
        packetizer_in_full_n,
        packetizer_in_write,
        packetizer_in_num_data_valid,
        packetizer_in_fifo_cap,
        bits_per_sample_c_din,
        bits_per_sample_c_full_n,
        bits_per_sample_c_write,
        bits_per_sample_c_num_data_valid,
        bits_per_sample_c_fifo_cap,
        payload_words_c_din,
        payload_words_c_full_n,
        payload_words_c_write,
        payload_words_c_num_data_valid,
        payload_words_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] payload_words;
input  [7:0] adc_in_TDATA;
input   adc_in_TVALID;
output   adc_in_TREADY;
input  [4:0] bits_per_sample;
output  [31:0] packetizer_in_din;
input   packetizer_in_full_n;
output   packetizer_in_write;
input  [11:0] packetizer_in_num_data_valid;
input  [11:0] packetizer_in_fifo_cap;
output  [4:0] bits_per_sample_c_din;
input   bits_per_sample_c_full_n;
output   bits_per_sample_c_write;
input  [2:0] bits_per_sample_c_num_data_valid;
input  [2:0] bits_per_sample_c_fifo_cap;
output  [15:0] payload_words_c_din;
input   payload_words_c_full_n;
output   payload_words_c_write;
input  [2:0] payload_words_c_num_data_valid;
input  [2:0] payload_words_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg packetizer_in_write;
reg bits_per_sample_c_write;
reg payload_words_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    packetizer_in_blk_n;
wire    ap_CS_fsm_state4;
reg    bits_per_sample_c_blk_n;
reg    payload_words_c_blk_n;
reg   [4:0] bits_per_sample_read_reg_166;
reg    ap_block_state1;
reg   [15:0] payload_words_read_reg_171;
wire    grp_sample_packer_fu_127_ap_start;
wire    grp_sample_packer_fu_127_ap_done;
wire    grp_sample_packer_fu_127_ap_idle;
wire    grp_sample_packer_fu_127_ap_ready;
wire    grp_sample_packer_fu_127_adc_in_TREADY;
wire   [31:0] grp_sample_packer_fu_127_packed_stream_din;
wire    grp_sample_packer_fu_127_packed_stream_write;
reg    grp_sample_packer_fu_127_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln71_fu_143_p2;
wire    ap_CS_fsm_state3;
wire    packed_stream_full_n;
reg    packed_stream_write;
reg   [15:0] i_fu_78;
wire   [15:0] i_11_fu_148_p2;
wire   [31:0] packed_stream_dout;
wire    packed_stream_empty_n;
reg    packed_stream_read;
reg    ap_block_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_adc_in_U_apdone_blk;
wire   [7:0] adc_in_TDATA_int_regslice;
wire    adc_in_TVALID_int_regslice;
reg    adc_in_TREADY_int_regslice;
wire    regslice_both_adc_in_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_sample_packer_fu_127_ap_start_reg = 1'b0;
#0 i_fu_78 = 16'd0;
end

vdif_chain_sample_packer grp_sample_packer_fu_127(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sample_packer_fu_127_ap_start),
    .ap_done(grp_sample_packer_fu_127_ap_done),
    .ap_idle(grp_sample_packer_fu_127_ap_idle),
    .ap_ready(grp_sample_packer_fu_127_ap_ready),
    .adc_in_TDATA(adc_in_TDATA_int_regslice),
    .adc_in_TVALID(adc_in_TVALID_int_regslice),
    .adc_in_TREADY(grp_sample_packer_fu_127_adc_in_TREADY),
    .packed_stream_din(grp_sample_packer_fu_127_packed_stream_din),
    .packed_stream_full_n(packed_stream_full_n),
    .packed_stream_write(grp_sample_packer_fu_127_packed_stream_write),
    .bits_per_sample(bits_per_sample_read_reg_166)
);

vdif_chain_fifo_w32_d2048_A packed_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_sample_packer_fu_127_packed_stream_din),
    .if_full_n(packed_stream_full_n),
    .if_write(packed_stream_write),
    .if_dout(packed_stream_dout),
    .if_empty_n(packed_stream_empty_n),
    .if_read(packed_stream_read)
);

vdif_chain_regslice_both #(
    .DataWidth( 8 ))
regslice_both_adc_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(adc_in_TDATA),
    .vld_in(adc_in_TVALID),
    .ack_in(regslice_both_adc_in_U_ack_in),
    .data_out(adc_in_TDATA_int_regslice),
    .vld_out(adc_in_TVALID_int_regslice),
    .ack_out(adc_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_adc_in_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln71_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sample_packer_fu_127_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln71_fu_143_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_sample_packer_fu_127_ap_start_reg <= 1'b1;
        end else if ((grp_sample_packer_fu_127_ap_ready == 1'b1)) begin
            grp_sample_packer_fu_127_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_78 <= 16'd0;
    end else if (((icmp_ln71_fu_143_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_78 <= i_11_fu_148_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bits_per_sample_read_reg_166 <= bits_per_sample;
        payload_words_read_reg_171 <= payload_words;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        adc_in_TREADY_int_regslice = grp_sample_packer_fu_127_adc_in_TREADY;
    end else begin
        adc_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_sample_packer_fu_127_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln71_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln71_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bits_per_sample_c_blk_n = bits_per_sample_c_full_n;
    end else begin
        bits_per_sample_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bits_per_sample_c_write = 1'b1;
    end else begin
        bits_per_sample_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        packed_stream_read = 1'b1;
    end else begin
        packed_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        packed_stream_write = grp_sample_packer_fu_127_packed_stream_write;
    end else begin
        packed_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        packetizer_in_blk_n = packetizer_in_full_n;
    end else begin
        packetizer_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        packetizer_in_write = 1'b1;
    end else begin
        packetizer_in_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        payload_words_c_blk_n = payload_words_c_full_n;
    end else begin
        payload_words_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        payload_words_c_write = 1'b1;
    end else begin
        payload_words_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln71_fu_143_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_sample_packer_fu_127_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign adc_in_TREADY = regslice_both_adc_in_U_ack_in;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (payload_words_c_full_n == 1'b0) | (bits_per_sample_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state4 = ((packetizer_in_full_n == 1'b0) | (packed_stream_empty_n == 1'b0));
end

assign bits_per_sample_c_din = bits_per_sample;

assign grp_sample_packer_fu_127_ap_start = grp_sample_packer_fu_127_ap_start_reg;

assign i_11_fu_148_p2 = (i_fu_78 + 16'd1);

assign icmp_ln71_fu_143_p2 = ((i_fu_78 == payload_words_read_reg_171) ? 1'b1 : 1'b0);

assign packetizer_in_din = packed_stream_dout;

assign payload_words_c_din = payload_words;

endmodule //vdif_chain_Loop_VITIS_LOOP_71_1_proc
