// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_sample_packer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        adc_in_TDATA,
        adc_in_TVALID,
        adc_in_TREADY,
        packed_stream_din,
        packed_stream_full_n,
        packed_stream_write,
        bits_per_sample
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] adc_in_TDATA;
input   adc_in_TVALID;
output   adc_in_TREADY;
output  [31:0] packed_stream_din;
input   packed_stream_full_n;
output   packed_stream_write;
input  [4:0] bits_per_sample;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg adc_in_TREADY;
reg[31:0] packed_stream_din;
reg packed_stream_write;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    packed_stream_blk_n;
wire    ap_CS_fsm_state3;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_idle;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_ready;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY;
wire   [31:0] grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out_ap_vld;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_idle;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_ready;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY;
wire   [31:0] grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out_ap_vld;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_idle;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_ready;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY;
wire   [31:0] grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out;
wire    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out_ap_vld;
reg    grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg;
reg    grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg = 1'b0;
#0 grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg = 1'b0;
#0 grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg = 1'b0;
end

vdif_chain_sample_packer_Pipeline_VITIS_LOOP_47_3 grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start),
    .ap_done(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done),
    .ap_idle(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_idle),
    .ap_ready(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_ready),
    .adc_in_TVALID(adc_in_TVALID),
    .adc_in_TDATA(adc_in_TDATA),
    .adc_in_TREADY(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY),
    .word_4_out(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out),
    .word_4_out_ap_vld(grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out_ap_vld)
);

vdif_chain_sample_packer_Pipeline_VITIS_LOOP_34_2 grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start),
    .ap_done(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done),
    .ap_idle(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_idle),
    .ap_ready(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_ready),
    .adc_in_TVALID(adc_in_TVALID),
    .adc_in_TDATA(adc_in_TDATA),
    .adc_in_TREADY(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY),
    .word_2_out(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out),
    .word_2_out_ap_vld(grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out_ap_vld)
);

vdif_chain_sample_packer_Pipeline_VITIS_LOOP_21_1 grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start),
    .ap_done(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done),
    .ap_idle(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_idle),
    .ap_ready(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_ready),
    .adc_in_TVALID(adc_in_TVALID),
    .adc_in_TDATA(adc_in_TDATA),
    .adc_in_TREADY(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY),
    .word_out(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out),
    .word_out_ap_vld(grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (bits_per_sample == 5'd2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg <= 1'b1;
        end else if ((grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_ready == 1'b1)) begin
            grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (bits_per_sample == 5'd4) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_ready == 1'b1)) begin
            grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (bits_per_sample == 5'd8) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg <= 1'b1;
        end else if ((grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_ready == 1'b1)) begin
            grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((bits_per_sample == 5'd2)) begin
            adc_in_TREADY = grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_adc_in_TREADY;
        end else if ((bits_per_sample == 5'd4)) begin
            adc_in_TREADY = grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_adc_in_TREADY;
        end else if ((bits_per_sample == 5'd8)) begin
            adc_in_TREADY = grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_adc_in_TREADY;
        end else begin
            adc_in_TREADY = 1'b0;
        end
    end else begin
        adc_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((bits_per_sample == 5'd8) & (1'b1 == ap_CS_fsm_state3)) | ((bits_per_sample == 5'd4) & (1'b1 == ap_CS_fsm_state3)) | ((bits_per_sample == 5'd2) & (1'b1 == ap_CS_fsm_state3)))) begin
        packed_stream_blk_n = packed_stream_full_n;
    end else begin
        packed_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
        if ((bits_per_sample == 5'd2)) begin
            packed_stream_din = grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_word_out;
        end else if ((bits_per_sample == 5'd4)) begin
            packed_stream_din = grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_word_2_out;
        end else if ((bits_per_sample == 5'd8)) begin
            packed_stream_din = grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_word_4_out;
        end else begin
            packed_stream_din = 'bx;
        end
    end else begin
        packed_stream_din = 'bx;
    end
end

always @ (*) begin
    if ((((bits_per_sample == 5'd8) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((bits_per_sample == 5'd4) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)) | ((bits_per_sample == 5'd2) & (1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3)))) begin
        packed_stream_write = 1'b1;
    end else begin
        packed_stream_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~(bits_per_sample == 5'd8) & ~(bits_per_sample == 5'd4) & ~(bits_per_sample == 5'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((bits_per_sample == 5'd2) | ((bits_per_sample == 5'd8) | (bits_per_sample == 5'd4))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done) & ((bits_per_sample == 5'd2) | ((bits_per_sample == 5'd8) | (bits_per_sample == 5'd4))))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2_on_subcall_done = (((grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_done == 1'b0) & (bits_per_sample == 5'd2)) | ((grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_done == 1'b0) & (bits_per_sample == 5'd4)) | ((grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_done == 1'b0) & (bits_per_sample == 5'd8)));
end

always @ (*) begin
    ap_block_state3 = (((bits_per_sample == 5'd8) & (packed_stream_full_n == 1'b0)) | ((bits_per_sample == 5'd4) & (packed_stream_full_n == 1'b0)) | ((bits_per_sample == 5'd2) & (packed_stream_full_n == 1'b0)));
end

assign grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start = grp_sample_packer_Pipeline_VITIS_LOOP_21_1_fu_81_ap_start_reg;

assign grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start = grp_sample_packer_Pipeline_VITIS_LOOP_34_2_fu_74_ap_start_reg;

assign grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start = grp_sample_packer_Pipeline_VITIS_LOOP_47_3_fu_67_ap_start_reg;

endmodule //vdif_chain_sample_packer
