// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_packet_fsm_1 (
        ap_ready,
        current_state,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [0:0] current_state;
output  [0:0] ap_return;
input   ap_rst;

wire   [1:0] next_state_write_assign_fu_24_p6;
wire   [0:0] next_state_write_assign_fu_24_p7;
wire   [1:0] next_state_write_assign_fu_24_p1;
wire   [1:0] next_state_write_assign_fu_24_p3;

(* dissolve_hierarchy = "yes" *) vdif_chain_sparsemux_5_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_5_2_1_1_1_U48(
    .din0(1'd1),
    .din1(1'd1),
    .def(1'd0),
    .sel(next_state_write_assign_fu_24_p6),
    .dout(next_state_write_assign_fu_24_p7)
);

assign ap_ready = 1'b1;

assign ap_return = next_state_write_assign_fu_24_p7;

assign next_state_write_assign_fu_24_p6 = current_state;

endmodule //vdif_chain_packet_fsm_1
