// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_timestamp_engine (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        pps_dout,
        pps_empty_n,
        pps_read,
        pps_num_data_valid,
        pps_fifo_cap,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] pps_dout;
input   pps_empty_n;
output   pps_read;
input  [2:0] pps_num_data_valid;
input  [2:0] pps_fifo_cap;
output  [29:0] ap_return_0;
output  [23:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pps_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [29:0] second_counter;
reg   [23:0] frame_counter;
reg    pps_blk_n;
reg    ap_block_state1;
wire   [29:0] add_ln16_fu_66_p2;
reg   [29:0] seconds_from_epoch_write_assign_reg_38;
wire   [0:0] pps_1_read_fu_32_p2;
reg   [23:0] frame_no_write_assign_reg_47;
wire   [23:0] add_ln23_fu_78_p2;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 second_counter = 30'd5000;
#0 frame_counter = 24'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((pps_1_read_fu_32_p2 == 1'd0)) begin
            frame_no_write_assign_reg_47 <= frame_counter;
        end else if ((pps_1_read_fu_32_p2 == 1'd1)) begin
            frame_no_write_assign_reg_47 <= 24'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((pps_1_read_fu_32_p2 == 1'd0)) begin
            seconds_from_epoch_write_assign_reg_38 <= second_counter;
        end else if ((pps_1_read_fu_32_p2 == 1'd1)) begin
            seconds_from_epoch_write_assign_reg_38 <= add_ln16_fu_66_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        frame_counter <= add_ln23_fu_78_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((pps_1_read_fu_32_p2 == 1'd1) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        second_counter <= add_ln16_fu_66_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        pps_blk_n = pps_empty_n;
    end else begin
        pps_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        pps_read = 1'b1;
    end else begin
        pps_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_fu_66_p2 = (second_counter + 30'd1);

assign add_ln23_fu_78_p2 = (frame_no_write_assign_reg_47 + 24'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (pps_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_return_0 = seconds_from_epoch_write_assign_reg_38;

assign ap_return_1 = frame_no_write_assign_reg_47;

assign pps_1_read_fu_32_p2 = pps_dout;

endmodule //vdif_chain_timestamp_engine
