// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_write_payload (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fifo_dout,
        fifo_empty_n,
        fifo_read,
        fifo_num_data_valid,
        fifo_fifo_cap,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        payload_words
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] fifo_dout;
input   fifo_empty_n;
output   fifo_read;
input  [13:0] fifo_num_data_valid;
input  [13:0] fifo_fifo_cap;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input  [15:0] payload_words;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] out_stream_TDATA;
reg[3:0] out_stream_TKEEP;
reg[3:0] out_stream_TSTRB;
reg[0:0] out_stream_TLAST;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [16:0] add_ln22_fu_65_p2;
reg   [16:0] add_ln22_reg_77;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_idle;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_ready;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_fifo_read;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TREADY;
wire   [31:0] grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA;
wire    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID;
wire   [3:0] grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP;
wire   [3:0] grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB;
wire   [0:0] grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST;
reg    grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [31:0] out_stream_TDATA_reg;
reg   [3:0] out_stream_TKEEP_reg;
reg   [3:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TLAST_reg;
wire   [16:0] zext_ln22_fu_61_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg = 1'b0;
end

vdif_chain_write_payload_Pipeline_VITIS_LOOP_16_1 grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start),
    .ap_done(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done),
    .ap_idle(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_idle),
    .ap_ready(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_ready),
    .fifo_dout(fifo_dout),
    .fifo_empty_n(fifo_empty_n),
    .fifo_read(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_fifo_read),
    .fifo_num_data_valid(14'd0),
    .fifo_fifo_cap(14'd0),
    .out_stream_TREADY(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TREADY),
    .payload_words(payload_words),
    .add_ln22(add_ln22_reg_77),
    .out_stream_TDATA(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA),
    .out_stream_TVALID(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID),
    .out_stream_TKEEP(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP),
    .out_stream_TSTRB(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB),
    .out_stream_TLAST(grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_ready == 1'b1)) begin
            grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln22_reg_77 <= add_ln22_fu_65_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TDATA_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA;
        out_stream_TKEEP_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP;
        out_stream_TLAST_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST;
        out_stream_TSTRB_reg <= grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TDATA = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TDATA;
    end else begin
        out_stream_TDATA = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TKEEP = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TLAST = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TLAST;
    end else begin
        out_stream_TLAST = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TSTRB = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln22_fu_65_p2 = ($signed(zext_ln22_fu_61_p1) + $signed(17'd131071));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign fifo_read = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_fifo_read;

assign grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_ap_start_reg;

assign grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TREADY = (out_stream_TREADY & ap_CS_fsm_state2);

assign out_stream_TVALID = grp_write_payload_Pipeline_VITIS_LOOP_16_1_fu_44_out_stream_TVALID;

assign zext_ln22_fu_61_p1 = payload_words;

endmodule //vdif_chain_write_payload
