// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        return_r,
        epoch_dout,
        epoch_empty_n,
        epoch_read,
        epoch_num_data_valid,
        epoch_fifo_cap,
        epoch_c_din,
        epoch_c_full_n,
        epoch_c_write,
        epoch_c_num_data_valid,
        epoch_c_fifo_cap,
        station_id_dout,
        station_id_empty_n,
        station_id_read,
        station_id_num_data_valid,
        station_id_fifo_cap,
        station_id_c_din,
        station_id_c_full_n,
        station_id_c_write,
        station_id_c_num_data_valid,
        station_id_c_fifo_cap,
        thread_id_dout,
        thread_id_empty_n,
        thread_id_read,
        thread_id_num_data_valid,
        thread_id_fifo_cap,
        thread_id_c_din,
        thread_id_c_full_n,
        thread_id_c_write,
        thread_id_c_num_data_valid,
        thread_id_c_fifo_cap,
        bits_per_sample_dout,
        bits_per_sample_empty_n,
        bits_per_sample_read,
        bits_per_sample_num_data_valid,
        bits_per_sample_fifo_cap,
        bits_per_sample_c_din,
        bits_per_sample_c_full_n,
        bits_per_sample_c_write,
        bits_per_sample_c_num_data_valid,
        bits_per_sample_c_fifo_cap,
        complex_data_dout,
        complex_data_empty_n,
        complex_data_read,
        complex_data_num_data_valid,
        complex_data_fifo_cap,
        complex_data_c_din,
        complex_data_c_full_n,
        complex_data_c_write,
        complex_data_c_num_data_valid,
        complex_data_c_fifo_cap,
        payload_words_dout,
        payload_words_empty_n,
        payload_words_read,
        payload_words_num_data_valid,
        payload_words_fifo_cap,
        payload_words_c1_din,
        payload_words_c1_full_n,
        payload_words_c1_write,
        payload_words_c1_num_data_valid,
        payload_words_c1_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [15:0] return_r;
input  [5:0] epoch_dout;
input   epoch_empty_n;
output   epoch_read;
input  [2:0] epoch_num_data_valid;
input  [2:0] epoch_fifo_cap;
output  [5:0] epoch_c_din;
input   epoch_c_full_n;
output   epoch_c_write;
input  [2:0] epoch_c_num_data_valid;
input  [2:0] epoch_c_fifo_cap;
input  [15:0] station_id_dout;
input   station_id_empty_n;
output   station_id_read;
input  [2:0] station_id_num_data_valid;
input  [2:0] station_id_fifo_cap;
output  [15:0] station_id_c_din;
input   station_id_c_full_n;
output   station_id_c_write;
input  [2:0] station_id_c_num_data_valid;
input  [2:0] station_id_c_fifo_cap;
input  [9:0] thread_id_dout;
input   thread_id_empty_n;
output   thread_id_read;
input  [2:0] thread_id_num_data_valid;
input  [2:0] thread_id_fifo_cap;
output  [9:0] thread_id_c_din;
input   thread_id_c_full_n;
output   thread_id_c_write;
input  [2:0] thread_id_c_num_data_valid;
input  [2:0] thread_id_c_fifo_cap;
input  [4:0] bits_per_sample_dout;
input   bits_per_sample_empty_n;
output   bits_per_sample_read;
input  [2:0] bits_per_sample_num_data_valid;
input  [2:0] bits_per_sample_fifo_cap;
output  [4:0] bits_per_sample_c_din;
input   bits_per_sample_c_full_n;
output   bits_per_sample_c_write;
input  [2:0] bits_per_sample_c_num_data_valid;
input  [2:0] bits_per_sample_c_fifo_cap;
input  [0:0] complex_data_dout;
input   complex_data_empty_n;
output   complex_data_read;
input  [2:0] complex_data_num_data_valid;
input  [2:0] complex_data_fifo_cap;
output  [0:0] complex_data_c_din;
input   complex_data_c_full_n;
output   complex_data_c_write;
input  [2:0] complex_data_c_num_data_valid;
input  [2:0] complex_data_c_fifo_cap;
input  [15:0] payload_words_dout;
input   payload_words_empty_n;
output   payload_words_read;
input  [2:0] payload_words_num_data_valid;
input  [2:0] payload_words_fifo_cap;
output  [15:0] payload_words_c1_din;
input   payload_words_c1_full_n;
output   payload_words_c1_write;
input  [2:0] payload_words_c1_num_data_valid;
input  [2:0] payload_words_c1_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] return_r;
reg epoch_read;
reg epoch_c_write;
reg station_id_read;
reg station_id_c_write;
reg thread_id_read;
reg thread_id_c_write;
reg bits_per_sample_read;
reg bits_per_sample_c_write;
reg complex_data_read;
reg complex_data_c_write;
reg payload_words_read;
reg payload_words_c1_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    epoch_blk_n;
reg    epoch_c_blk_n;
reg    station_id_blk_n;
reg    station_id_c_blk_n;
reg    thread_id_blk_n;
reg    thread_id_c_blk_n;
reg    bits_per_sample_blk_n;
reg    bits_per_sample_c_blk_n;
reg    complex_data_blk_n;
reg    complex_data_c_blk_n;
reg    payload_words_blk_n;
reg    payload_words_c1_blk_n;
reg    ap_block_state1;
reg   [15:0] return_r_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 return_r_preg = 16'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        return_r_preg <= 16'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            return_r_preg <= payload_words_dout;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bits_per_sample_blk_n = bits_per_sample_empty_n;
    end else begin
        bits_per_sample_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bits_per_sample_c_blk_n = bits_per_sample_c_full_n;
    end else begin
        bits_per_sample_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bits_per_sample_c_write = 1'b1;
    end else begin
        bits_per_sample_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bits_per_sample_read = 1'b1;
    end else begin
        bits_per_sample_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        complex_data_blk_n = complex_data_empty_n;
    end else begin
        complex_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        complex_data_c_blk_n = complex_data_c_full_n;
    end else begin
        complex_data_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        complex_data_c_write = 1'b1;
    end else begin
        complex_data_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        complex_data_read = 1'b1;
    end else begin
        complex_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        epoch_blk_n = epoch_empty_n;
    end else begin
        epoch_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        epoch_c_blk_n = epoch_c_full_n;
    end else begin
        epoch_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        epoch_c_write = 1'b1;
    end else begin
        epoch_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        epoch_read = 1'b1;
    end else begin
        epoch_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        payload_words_blk_n = payload_words_empty_n;
    end else begin
        payload_words_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        payload_words_c1_blk_n = payload_words_c1_full_n;
    end else begin
        payload_words_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        payload_words_c1_write = 1'b1;
    end else begin
        payload_words_c1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        payload_words_read = 1'b1;
    end else begin
        payload_words_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        return_r = payload_words_dout;
    end else begin
        return_r = return_r_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        station_id_blk_n = station_id_empty_n;
    end else begin
        station_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        station_id_c_blk_n = station_id_c_full_n;
    end else begin
        station_id_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        station_id_c_write = 1'b1;
    end else begin
        station_id_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        station_id_read = 1'b1;
    end else begin
        station_id_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        thread_id_blk_n = thread_id_empty_n;
    end else begin
        thread_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        thread_id_c_blk_n = thread_id_c_full_n;
    end else begin
        thread_id_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        thread_id_c_write = 1'b1;
    end else begin
        thread_id_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        thread_id_read = 1'b1;
    end else begin
        thread_id_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((payload_words_c1_full_n == 1'b0) | (payload_words_empty_n == 1'b0) | (complex_data_c_full_n == 1'b0) | (complex_data_empty_n == 1'b0) | (ap_start == 1'b0) | (bits_per_sample_c_full_n == 1'b0) | (bits_per_sample_empty_n == 1'b0) | (thread_id_c_full_n == 1'b0) | (thread_id_empty_n == 1'b0) | (station_id_c_full_n == 1'b0) | (station_id_empty_n == 1'b0) | (epoch_c_full_n == 1'b0) | (epoch_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign bits_per_sample_c_din = bits_per_sample_dout;

assign complex_data_c_din = complex_data_dout;

assign epoch_c_din = epoch_dout;

assign payload_words_c1_din = payload_words_dout;

assign station_id_c_din = station_id_dout;

assign thread_id_c_din = thread_id_dout;

endmodule //vdif_chain_entry_proc
