// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_header_generator (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        epoch_dout,
        epoch_empty_n,
        epoch_read,
        epoch_num_data_valid,
        epoch_fifo_cap,
        station_id_dout,
        station_id_empty_n,
        station_id_read,
        station_id_num_data_valid,
        station_id_fifo_cap,
        thread_id_dout,
        thread_id_empty_n,
        thread_id_read,
        thread_id_num_data_valid,
        thread_id_fifo_cap,
        bits_per_sample_dout,
        bits_per_sample_empty_n,
        bits_per_sample_read,
        bits_per_sample_num_data_valid,
        bits_per_sample_fifo_cap,
        complex_data_dout,
        complex_data_empty_n,
        complex_data_read,
        complex_data_num_data_valid,
        complex_data_fifo_cap,
        payload_words_dout,
        payload_words_empty_n,
        payload_words_read,
        payload_words_num_data_valid,
        payload_words_fifo_cap,
        header_address0,
        header_ce0,
        header_we0,
        header_d0,
        header_address1,
        header_ce1,
        header_we1,
        header_d1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [29:0] p_read;
input  [23:0] p_read1;
input  [5:0] epoch_dout;
input   epoch_empty_n;
output   epoch_read;
input  [2:0] epoch_num_data_valid;
input  [2:0] epoch_fifo_cap;
input  [15:0] station_id_dout;
input   station_id_empty_n;
output   station_id_read;
input  [2:0] station_id_num_data_valid;
input  [2:0] station_id_fifo_cap;
input  [9:0] thread_id_dout;
input   thread_id_empty_n;
output   thread_id_read;
input  [2:0] thread_id_num_data_valid;
input  [2:0] thread_id_fifo_cap;
input  [4:0] bits_per_sample_dout;
input   bits_per_sample_empty_n;
output   bits_per_sample_read;
input  [2:0] bits_per_sample_num_data_valid;
input  [2:0] bits_per_sample_fifo_cap;
input  [0:0] complex_data_dout;
input   complex_data_empty_n;
output   complex_data_read;
input  [2:0] complex_data_num_data_valid;
input  [2:0] complex_data_fifo_cap;
input  [15:0] payload_words_dout;
input   payload_words_empty_n;
output   payload_words_read;
input  [2:0] payload_words_num_data_valid;
input  [2:0] payload_words_fifo_cap;
output  [2:0] header_address0;
output   header_ce0;
output   header_we0;
output  [31:0] header_d0;
output  [2:0] header_address1;
output   header_ce1;
output   header_we1;
output  [31:0] header_d1;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg epoch_read;
reg station_id_read;
reg thread_id_read;
reg bits_per_sample_read;
reg complex_data_read;
reg payload_words_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    epoch_blk_n;
reg    station_id_blk_n;
reg    thread_id_blk_n;
reg    bits_per_sample_blk_n;
reg    complex_data_blk_n;
reg    payload_words_blk_n;
reg   [15:0] payload_words_1_reg_336;
reg    ap_block_state1;
reg   [0:0] complex_data_1_reg_340;
reg   [4:0] bits_per_sample_1_reg_345;
reg   [9:0] thread_id_1_reg_350;
reg   [15:0] station_id_1_reg_355;
reg   [14:0] lshr_ln_reg_360;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    header_we1_local;
reg   [31:0] header_d1_local;
wire   [31:0] zext_ln21_fu_233_p1;
reg    header_ce1_local;
reg   [2:0] header_address1_local;
reg    header_we0_local;
reg   [31:0] header_d0_local;
wire   [31:0] zext_ln24_fu_246_p1;
reg    header_ce0_local;
reg   [2:0] header_address0_local;
wire   [31:0] zext_ln30_fu_282_p1;
wire   [31:0] or_ln37_fu_329_p2;
wire   [29:0] tmp_fu_238_p3;
wire   [15:0] zext_ln28_fu_261_p1;
wire   [15:0] frame_length_fu_264_p2;
wire   [28:0] zext_ln31_fu_270_p1;
wire   [29:0] zext_ln30_cast_fu_274_p3;
wire   [30:0] shl_ln3_fu_294_p3;
wire   [31:0] zext_ln37_fu_301_p1;
wire   [31:0] add_ln37_fu_305_p2;
wire   [5:0] tmp_1_fu_311_p4;
wire   [31:0] or_ln37_1_fu_321_p4;
wire   [31:0] shl_ln_fu_287_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bits_per_sample_1_reg_345 <= bits_per_sample_dout;
        complex_data_1_reg_340 <= complex_data_dout;
        lshr_ln_reg_360 <= {{payload_words_dout[15:1]}};
        payload_words_1_reg_336 <= payload_words_dout;
        station_id_1_reg_355 <= station_id_dout;
        thread_id_1_reg_350 <= thread_id_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bits_per_sample_blk_n = bits_per_sample_empty_n;
    end else begin
        bits_per_sample_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bits_per_sample_read = 1'b1;
    end else begin
        bits_per_sample_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        complex_data_blk_n = complex_data_empty_n;
    end else begin
        complex_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        complex_data_read = 1'b1;
    end else begin
        complex_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        epoch_blk_n = epoch_empty_n;
    end else begin
        epoch_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        epoch_read = 1'b1;
    end else begin
        epoch_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        header_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        header_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        header_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        header_address0_local = 64'd1;
    end else begin
        header_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        header_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        header_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        header_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        header_address1_local = 64'd0;
    end else begin
        header_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        header_ce0_local = 1'b1;
    end else begin
        header_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        header_ce1_local = 1'b1;
    end else begin
        header_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        header_d0_local = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        header_d0_local = 32'd2896953069;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        header_d0_local = or_ln37_fu_329_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        header_d0_local = zext_ln24_fu_246_p1;
    end else begin
        header_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        header_d1_local = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        header_d1_local = 32'd16777216;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        header_d1_local = zext_ln30_fu_282_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        header_d1_local = zext_ln21_fu_233_p1;
    end else begin
        header_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        header_we0_local = 1'b1;
    end else begin
        header_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        header_we1_local = 1'b1;
    end else begin
        header_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        payload_words_blk_n = payload_words_empty_n;
    end else begin
        payload_words_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        payload_words_read = 1'b1;
    end else begin
        payload_words_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        station_id_blk_n = station_id_empty_n;
    end else begin
        station_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        station_id_read = 1'b1;
    end else begin
        station_id_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        thread_id_blk_n = thread_id_empty_n;
    end else begin
        thread_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        thread_id_read = 1'b1;
    end else begin
        thread_id_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_fu_305_p2 = ($signed(zext_ln37_fu_301_p1) + $signed(32'd4227858432));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (payload_words_empty_n == 1'b0) | (complex_data_empty_n == 1'b0) | (bits_per_sample_empty_n == 1'b0) | (thread_id_empty_n == 1'b0) | (station_id_empty_n == 1'b0) | (epoch_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_return = payload_words_1_reg_336;

assign frame_length_fu_264_p2 = (zext_ln28_fu_261_p1 + 16'd4);

assign header_address0 = header_address0_local;

assign header_address1 = header_address1_local;

assign header_ce0 = header_ce0_local;

assign header_ce1 = header_ce1_local;

assign header_d0 = header_d0_local;

assign header_d1 = header_d1_local;

assign header_we0 = header_we0_local;

assign header_we1 = header_we1_local;

assign or_ln37_1_fu_321_p4 = {{{tmp_1_fu_311_p4}, {thread_id_1_reg_350}}, {station_id_1_reg_355}};

assign or_ln37_fu_329_p2 = (shl_ln_fu_287_p3 | or_ln37_1_fu_321_p4);

assign shl_ln3_fu_294_p3 = {{bits_per_sample_1_reg_345}, {26'd0}};

assign shl_ln_fu_287_p3 = {{complex_data_1_reg_340}, {31'd0}};

assign tmp_1_fu_311_p4 = {{add_ln37_fu_305_p2[31:26]}};

assign tmp_fu_238_p3 = {{epoch_dout}, {p_read1}};

assign zext_ln21_fu_233_p1 = p_read;

assign zext_ln24_fu_246_p1 = tmp_fu_238_p3;

assign zext_ln28_fu_261_p1 = lshr_ln_reg_360;

assign zext_ln30_cast_fu_274_p3 = {{1'd1}, {zext_ln31_fu_270_p1}};

assign zext_ln30_fu_282_p1 = zext_ln30_cast_fu_274_p3;

assign zext_ln31_fu_270_p1 = frame_length_fu_264_p2;

assign zext_ln37_fu_301_p1 = shl_ln3_fu_294_p3;

endmodule //vdif_chain_header_generator
