// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        header_address0,
        header_ce0,
        header_q0,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        fifo_dout,
        fifo_empty_n,
        fifo_read,
        fifo_num_data_valid,
        fifo_fifo_cap,
        p_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [2:0] header_address0;
output   header_ce0;
input  [31:0] header_q0;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input  [31:0] fifo_dout;
input   fifo_empty_n;
output   fifo_read;
input  [13:0] fifo_num_data_valid;
input  [13:0] fifo_fifo_cap;
input  [15:0] p_read;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] p_read_1_reg_79;
wire    ap_CS_fsm_state2;
wire    grp_write_header_fu_50_ap_done;
wire    grp_write_header_fu_50_ap_start;
wire    grp_write_header_fu_50_ap_idle;
wire    grp_write_header_fu_50_ap_ready;
wire    grp_write_header_fu_50_out_stream_TREADY;
wire   [2:0] grp_write_header_fu_50_header_address0;
wire    grp_write_header_fu_50_header_ce0;
wire   [31:0] grp_write_header_fu_50_out_stream_TDATA;
wire    grp_write_header_fu_50_out_stream_TVALID;
wire   [3:0] grp_write_header_fu_50_out_stream_TKEEP;
wire   [3:0] grp_write_header_fu_50_out_stream_TSTRB;
wire   [0:0] grp_write_header_fu_50_out_stream_TLAST;
wire    grp_write_payload_fu_64_ap_start;
wire    grp_write_payload_fu_64_ap_done;
wire    grp_write_payload_fu_64_ap_idle;
wire    grp_write_payload_fu_64_ap_ready;
wire    grp_write_payload_fu_64_fifo_read;
wire   [31:0] grp_write_payload_fu_64_out_stream_TDATA;
wire    grp_write_payload_fu_64_out_stream_TVALID;
wire    grp_write_payload_fu_64_out_stream_TREADY;
wire   [3:0] grp_write_payload_fu_64_out_stream_TKEEP;
wire   [3:0] grp_write_payload_fu_64_out_stream_TSTRB;
wire   [0:0] grp_write_payload_fu_64_out_stream_TLAST;
reg    grp_write_header_fu_50_ap_start_reg;
reg    ap_block_state1_ignore_call5;
reg   [31:0] out_stream_TDATA_reg;
reg   [3:0] out_stream_TKEEP_reg;
reg   [3:0] out_stream_TSTRB_reg;
reg   [0:0] out_stream_TLAST_reg;
reg    grp_write_payload_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
reg   [3:0] out_stream_TKEEP_int_regslice;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
reg   [3:0] out_stream_TSTRB_int_regslice;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
reg   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_write_header_fu_50_ap_start_reg = 1'b0;
#0 grp_write_payload_fu_64_ap_start_reg = 1'b0;
end

vdif_chain_write_header grp_write_header_fu_50(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_header_fu_50_ap_start),
    .ap_done(grp_write_header_fu_50_ap_done),
    .ap_idle(grp_write_header_fu_50_ap_idle),
    .ap_ready(grp_write_header_fu_50_ap_ready),
    .out_stream_TREADY(grp_write_header_fu_50_out_stream_TREADY),
    .header_address0(grp_write_header_fu_50_header_address0),
    .header_ce0(grp_write_header_fu_50_header_ce0),
    .header_q0(header_q0),
    .out_stream_TDATA(grp_write_header_fu_50_out_stream_TDATA),
    .out_stream_TVALID(grp_write_header_fu_50_out_stream_TVALID),
    .out_stream_TKEEP(grp_write_header_fu_50_out_stream_TKEEP),
    .out_stream_TSTRB(grp_write_header_fu_50_out_stream_TSTRB),
    .out_stream_TLAST(grp_write_header_fu_50_out_stream_TLAST)
);

vdif_chain_write_payload grp_write_payload_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_payload_fu_64_ap_start),
    .ap_done(grp_write_payload_fu_64_ap_done),
    .ap_idle(grp_write_payload_fu_64_ap_idle),
    .ap_ready(grp_write_payload_fu_64_ap_ready),
    .fifo_dout(fifo_dout),
    .fifo_empty_n(fifo_empty_n),
    .fifo_read(grp_write_payload_fu_64_fifo_read),
    .fifo_num_data_valid(14'd0),
    .fifo_fifo_cap(14'd0),
    .out_stream_TDATA(grp_write_payload_fu_64_out_stream_TDATA),
    .out_stream_TVALID(grp_write_payload_fu_64_out_stream_TVALID),
    .out_stream_TREADY(grp_write_payload_fu_64_out_stream_TREADY),
    .out_stream_TKEEP(grp_write_payload_fu_64_out_stream_TKEEP),
    .out_stream_TSTRB(grp_write_payload_fu_64_out_stream_TSTRB),
    .out_stream_TLAST(grp_write_payload_fu_64_out_stream_TLAST),
    .payload_words(p_read_1_reg_79)
);

vdif_chain_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

vdif_chain_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_stream_TKEEP_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

vdif_chain_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_stream_TSTRB_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

vdif_chain_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_header_fu_50_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call5) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_write_header_fu_50_ap_start_reg <= 1'b1;
        end else if ((grp_write_header_fu_50_ap_ready == 1'b1)) begin
            grp_write_header_fu_50_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_payload_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_write_payload_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_write_payload_fu_64_ap_ready == 1'b1)) begin
            grp_write_payload_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TDATA_reg <= grp_write_payload_fu_64_out_stream_TDATA;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TDATA_reg <= grp_write_header_fu_50_out_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TKEEP_reg <= grp_write_payload_fu_64_out_stream_TKEEP;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TKEEP_reg <= grp_write_header_fu_50_out_stream_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TLAST_reg <= grp_write_payload_fu_64_out_stream_TLAST;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TLAST_reg <= grp_write_header_fu_50_out_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TSTRB_reg <= grp_write_payload_fu_64_out_stream_TSTRB;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TSTRB_reg <= grp_write_header_fu_50_out_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_write_header_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_read_1_reg_79 <= p_read;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_write_header_fu_50_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_write_payload_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TDATA_int_regslice = grp_write_payload_fu_64_out_stream_TDATA;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TDATA_int_regslice = grp_write_header_fu_50_out_stream_TDATA;
    end else begin
        out_stream_TDATA_int_regslice = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TKEEP_int_regslice = grp_write_payload_fu_64_out_stream_TKEEP;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TKEEP_int_regslice = grp_write_header_fu_50_out_stream_TKEEP;
    end else begin
        out_stream_TKEEP_int_regslice = out_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TLAST_int_regslice = grp_write_payload_fu_64_out_stream_TLAST;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TLAST_int_regslice = grp_write_header_fu_50_out_stream_TLAST;
    end else begin
        out_stream_TLAST_int_regslice = out_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_write_payload_fu_64_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_stream_TSTRB_int_regslice = grp_write_payload_fu_64_out_stream_TSTRB;
    end else if (((grp_write_header_fu_50_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_stream_TSTRB_int_regslice = grp_write_header_fu_50_out_stream_TSTRB;
    end else begin
        out_stream_TSTRB_int_regslice = out_stream_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_stream_TVALID_int_regslice = grp_write_payload_fu_64_out_stream_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_stream_TVALID_int_regslice = grp_write_header_fu_50_out_stream_TVALID;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_write_header_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_write_payload_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call5 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign fifo_read = grp_write_payload_fu_64_fifo_read;

assign grp_write_header_fu_50_ap_start = grp_write_header_fu_50_ap_start_reg;

assign grp_write_header_fu_50_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state2);

assign grp_write_payload_fu_64_ap_start = grp_write_payload_fu_64_ap_start_reg;

assign grp_write_payload_fu_64_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state4);

assign header_address0 = grp_write_header_fu_50_header_address0;

assign header_ce0 = grp_write_header_fu_50_header_ce0;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

endmodule //vdif_chain_packetizer_Block_entry_out_stream_V_data_V_wr_proc
