// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vdif_chain_vdif_chain,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12t-cpg238-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.406000,HLS_SYN_LAT=589807,HLS_SYN_TPT=589808,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=2859,HLS_SYN_LUT=3230,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain (
        adc_in_TDATA,
        out_stream_TDATA,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        epoch,
        station_id,
        thread_id,
        bits_per_sample,
        complex_data,
        pps,
        payload_words,
        ap_clk,
        ap_rst_n,
        ap_start,
        adc_in_TVALID,
        adc_in_TREADY,
        out_stream_TVALID,
        out_stream_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] adc_in_TDATA;
output  [31:0] out_stream_TDATA;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input  [5:0] epoch;
input  [15:0] station_id;
input  [9:0] thread_id;
input  [4:0] bits_per_sample;
input  [0:0] complex_data;
input  [0:0] pps;
input  [15:0] payload_words;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
input   adc_in_TVALID;
output   adc_in_TREADY;
output   out_stream_TVALID;
input   out_stream_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    entry_proc7_U0_ap_start;
wire    entry_proc7_U0_ap_done;
wire    entry_proc7_U0_ap_continue;
wire    entry_proc7_U0_ap_idle;
wire    entry_proc7_U0_ap_ready;
wire    entry_proc7_U0_start_out;
wire    entry_proc7_U0_start_write;
wire   [5:0] entry_proc7_U0_epoch_c_din;
wire    entry_proc7_U0_epoch_c_write;
wire   [15:0] entry_proc7_U0_station_id_c_din;
wire    entry_proc7_U0_station_id_c_write;
wire   [9:0] entry_proc7_U0_thread_id_c_din;
wire    entry_proc7_U0_thread_id_c_write;
wire   [0:0] entry_proc7_U0_complex_data_c_din;
wire    entry_proc7_U0_complex_data_c_write;
wire   [0:0] entry_proc7_U0_pps_c_din;
wire    entry_proc7_U0_pps_c_write;
wire    Loop_VITIS_LOOP_71_1_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_71_1_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_71_1_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_71_1_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_71_1_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_71_1_proc_U0_adc_in_TREADY;
wire   [31:0] Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_din;
wire    Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_write;
wire   [4:0] Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_din;
wire    Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_write;
wire   [15:0] Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_din;
wire    Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_write;
wire    packetizer_U0_packetizer_in_read;
wire   [31:0] packetizer_U0_out_stream_TDATA;
wire   [3:0] packetizer_U0_out_stream_TKEEP;
wire   [3:0] packetizer_U0_out_stream_TSTRB;
wire   [0:0] packetizer_U0_out_stream_TLAST;
wire    packetizer_U0_epoch_read;
wire    packetizer_U0_station_id_read;
wire    packetizer_U0_thread_id_read;
wire    packetizer_U0_bits_per_sample_read;
wire    packetizer_U0_complex_data_read;
wire    packetizer_U0_pps_read;
wire    packetizer_U0_payload_words_read;
wire    packetizer_U0_ap_start;
wire    packetizer_U0_ap_done;
wire    packetizer_U0_out_stream_TVALID;
wire    packetizer_U0_ap_ready;
wire    packetizer_U0_ap_idle;
wire    packetizer_U0_ap_continue;
wire    epoch_c_full_n;
wire   [5:0] epoch_c_dout;
wire    epoch_c_empty_n;
wire   [2:0] epoch_c_num_data_valid;
wire   [2:0] epoch_c_fifo_cap;
wire    station_id_c_full_n;
wire   [15:0] station_id_c_dout;
wire    station_id_c_empty_n;
wire   [2:0] station_id_c_num_data_valid;
wire   [2:0] station_id_c_fifo_cap;
wire    thread_id_c_full_n;
wire   [9:0] thread_id_c_dout;
wire    thread_id_c_empty_n;
wire   [2:0] thread_id_c_num_data_valid;
wire   [2:0] thread_id_c_fifo_cap;
wire    complex_data_c_full_n;
wire   [0:0] complex_data_c_dout;
wire    complex_data_c_empty_n;
wire   [2:0] complex_data_c_num_data_valid;
wire   [2:0] complex_data_c_fifo_cap;
wire    pps_c_full_n;
wire   [0:0] pps_c_dout;
wire    pps_c_empty_n;
wire   [2:0] pps_c_num_data_valid;
wire   [2:0] pps_c_fifo_cap;
wire    packetizer_in_full_n;
wire   [31:0] packetizer_in_dout;
wire    packetizer_in_empty_n;
wire   [11:0] packetizer_in_num_data_valid;
wire   [11:0] packetizer_in_fifo_cap;
wire    bits_per_sample_c_full_n;
wire   [4:0] bits_per_sample_c_dout;
wire    bits_per_sample_c_empty_n;
wire   [2:0] bits_per_sample_c_num_data_valid;
wire   [2:0] bits_per_sample_c_fifo_cap;
wire    payload_words_c_full_n;
wire   [15:0] payload_words_c_dout;
wire    payload_words_c_empty_n;
wire   [2:0] payload_words_c_num_data_valid;
wire   [2:0] payload_words_c_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc7_U0_ap_ready;
wire    ap_sync_entry_proc7_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready;
wire   [0:0] start_for_packetizer_U0_din;
wire    start_for_packetizer_U0_full_n;
wire   [0:0] start_for_packetizer_U0_dout;
wire    start_for_packetizer_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc7_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready = 1'b0;
end

vdif_chain_entry_proc7 entry_proc7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc7_U0_ap_start),
    .start_full_n(start_for_packetizer_U0_full_n),
    .ap_done(entry_proc7_U0_ap_done),
    .ap_continue(entry_proc7_U0_ap_continue),
    .ap_idle(entry_proc7_U0_ap_idle),
    .ap_ready(entry_proc7_U0_ap_ready),
    .start_out(entry_proc7_U0_start_out),
    .start_write(entry_proc7_U0_start_write),
    .epoch(epoch),
    .epoch_c_din(entry_proc7_U0_epoch_c_din),
    .epoch_c_full_n(epoch_c_full_n),
    .epoch_c_write(entry_proc7_U0_epoch_c_write),
    .epoch_c_num_data_valid(epoch_c_num_data_valid),
    .epoch_c_fifo_cap(epoch_c_fifo_cap),
    .station_id(station_id),
    .station_id_c_din(entry_proc7_U0_station_id_c_din),
    .station_id_c_full_n(station_id_c_full_n),
    .station_id_c_write(entry_proc7_U0_station_id_c_write),
    .station_id_c_num_data_valid(station_id_c_num_data_valid),
    .station_id_c_fifo_cap(station_id_c_fifo_cap),
    .thread_id(thread_id),
    .thread_id_c_din(entry_proc7_U0_thread_id_c_din),
    .thread_id_c_full_n(thread_id_c_full_n),
    .thread_id_c_write(entry_proc7_U0_thread_id_c_write),
    .thread_id_c_num_data_valid(thread_id_c_num_data_valid),
    .thread_id_c_fifo_cap(thread_id_c_fifo_cap),
    .complex_data(complex_data),
    .complex_data_c_din(entry_proc7_U0_complex_data_c_din),
    .complex_data_c_full_n(complex_data_c_full_n),
    .complex_data_c_write(entry_proc7_U0_complex_data_c_write),
    .complex_data_c_num_data_valid(complex_data_c_num_data_valid),
    .complex_data_c_fifo_cap(complex_data_c_fifo_cap),
    .pps(pps),
    .pps_c_din(entry_proc7_U0_pps_c_din),
    .pps_c_full_n(pps_c_full_n),
    .pps_c_write(entry_proc7_U0_pps_c_write),
    .pps_c_num_data_valid(pps_c_num_data_valid),
    .pps_c_fifo_cap(pps_c_fifo_cap)
);

vdif_chain_Loop_VITIS_LOOP_71_1_proc Loop_VITIS_LOOP_71_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_71_1_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_71_1_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_71_1_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_71_1_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_71_1_proc_U0_ap_ready),
    .payload_words(payload_words),
    .adc_in_TDATA(adc_in_TDATA),
    .adc_in_TVALID(adc_in_TVALID),
    .adc_in_TREADY(Loop_VITIS_LOOP_71_1_proc_U0_adc_in_TREADY),
    .bits_per_sample(bits_per_sample),
    .packetizer_in_din(Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_din),
    .packetizer_in_full_n(packetizer_in_full_n),
    .packetizer_in_write(Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_write),
    .packetizer_in_num_data_valid(packetizer_in_num_data_valid),
    .packetizer_in_fifo_cap(packetizer_in_fifo_cap),
    .bits_per_sample_c_din(Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_din),
    .bits_per_sample_c_full_n(bits_per_sample_c_full_n),
    .bits_per_sample_c_write(Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_write),
    .bits_per_sample_c_num_data_valid(bits_per_sample_c_num_data_valid),
    .bits_per_sample_c_fifo_cap(bits_per_sample_c_fifo_cap),
    .payload_words_c_din(Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_din),
    .payload_words_c_full_n(payload_words_c_full_n),
    .payload_words_c_write(Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_write),
    .payload_words_c_num_data_valid(payload_words_c_num_data_valid),
    .payload_words_c_fifo_cap(payload_words_c_fifo_cap)
);

vdif_chain_packetizer packetizer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .packetizer_in_dout(packetizer_in_dout),
    .packetizer_in_empty_n(packetizer_in_empty_n),
    .packetizer_in_read(packetizer_U0_packetizer_in_read),
    .out_stream_TDATA(packetizer_U0_out_stream_TDATA),
    .out_stream_TKEEP(packetizer_U0_out_stream_TKEEP),
    .out_stream_TSTRB(packetizer_U0_out_stream_TSTRB),
    .out_stream_TLAST(packetizer_U0_out_stream_TLAST),
    .epoch_dout(epoch_c_dout),
    .epoch_empty_n(epoch_c_empty_n),
    .epoch_read(packetizer_U0_epoch_read),
    .station_id_dout(station_id_c_dout),
    .station_id_empty_n(station_id_c_empty_n),
    .station_id_read(packetizer_U0_station_id_read),
    .thread_id_dout(thread_id_c_dout),
    .thread_id_empty_n(thread_id_c_empty_n),
    .thread_id_read(packetizer_U0_thread_id_read),
    .bits_per_sample_dout(bits_per_sample_c_dout),
    .bits_per_sample_empty_n(bits_per_sample_c_empty_n),
    .bits_per_sample_read(packetizer_U0_bits_per_sample_read),
    .complex_data_dout(complex_data_c_dout),
    .complex_data_empty_n(complex_data_c_empty_n),
    .complex_data_read(packetizer_U0_complex_data_read),
    .pps_dout(pps_c_dout),
    .pps_empty_n(pps_c_empty_n),
    .pps_read(packetizer_U0_pps_read),
    .payload_words_dout(payload_words_c_dout),
    .payload_words_empty_n(payload_words_c_empty_n),
    .payload_words_read(packetizer_U0_payload_words_read),
    .ap_start(packetizer_U0_ap_start),
    .ap_done(packetizer_U0_ap_done),
    .out_stream_TVALID(packetizer_U0_out_stream_TVALID),
    .out_stream_TREADY(out_stream_TREADY),
    .ap_ready(packetizer_U0_ap_ready),
    .ap_idle(packetizer_U0_ap_idle),
    .ap_continue(packetizer_U0_ap_continue)
);

vdif_chain_fifo_w6_d3_S_x epoch_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_epoch_c_din),
    .if_full_n(epoch_c_full_n),
    .if_write(entry_proc7_U0_epoch_c_write),
    .if_dout(epoch_c_dout),
    .if_empty_n(epoch_c_empty_n),
    .if_read(packetizer_U0_epoch_read),
    .if_num_data_valid(epoch_c_num_data_valid),
    .if_fifo_cap(epoch_c_fifo_cap)
);

vdif_chain_fifo_w16_d3_S_x station_id_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_station_id_c_din),
    .if_full_n(station_id_c_full_n),
    .if_write(entry_proc7_U0_station_id_c_write),
    .if_dout(station_id_c_dout),
    .if_empty_n(station_id_c_empty_n),
    .if_read(packetizer_U0_station_id_read),
    .if_num_data_valid(station_id_c_num_data_valid),
    .if_fifo_cap(station_id_c_fifo_cap)
);

vdif_chain_fifo_w10_d3_S_x thread_id_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_thread_id_c_din),
    .if_full_n(thread_id_c_full_n),
    .if_write(entry_proc7_U0_thread_id_c_write),
    .if_dout(thread_id_c_dout),
    .if_empty_n(thread_id_c_empty_n),
    .if_read(packetizer_U0_thread_id_read),
    .if_num_data_valid(thread_id_c_num_data_valid),
    .if_fifo_cap(thread_id_c_fifo_cap)
);

vdif_chain_fifo_w1_d3_S_x complex_data_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_complex_data_c_din),
    .if_full_n(complex_data_c_full_n),
    .if_write(entry_proc7_U0_complex_data_c_write),
    .if_dout(complex_data_c_dout),
    .if_empty_n(complex_data_c_empty_n),
    .if_read(packetizer_U0_complex_data_read),
    .if_num_data_valid(complex_data_c_num_data_valid),
    .if_fifo_cap(complex_data_c_fifo_cap)
);

vdif_chain_fifo_w1_d3_S_x pps_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_pps_c_din),
    .if_full_n(pps_c_full_n),
    .if_write(entry_proc7_U0_pps_c_write),
    .if_dout(pps_c_dout),
    .if_empty_n(pps_c_empty_n),
    .if_read(packetizer_U0_pps_read),
    .if_num_data_valid(pps_c_num_data_valid),
    .if_fifo_cap(pps_c_fifo_cap)
);

vdif_chain_fifo_w32_d2048_A_x packetizer_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_din),
    .if_full_n(packetizer_in_full_n),
    .if_write(Loop_VITIS_LOOP_71_1_proc_U0_packetizer_in_write),
    .if_dout(packetizer_in_dout),
    .if_empty_n(packetizer_in_empty_n),
    .if_read(packetizer_U0_packetizer_in_read),
    .if_num_data_valid(packetizer_in_num_data_valid),
    .if_fifo_cap(packetizer_in_fifo_cap)
);

vdif_chain_fifo_w5_d2_S bits_per_sample_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_din),
    .if_full_n(bits_per_sample_c_full_n),
    .if_write(Loop_VITIS_LOOP_71_1_proc_U0_bits_per_sample_c_write),
    .if_dout(bits_per_sample_c_dout),
    .if_empty_n(bits_per_sample_c_empty_n),
    .if_read(packetizer_U0_bits_per_sample_read),
    .if_num_data_valid(bits_per_sample_c_num_data_valid),
    .if_fifo_cap(bits_per_sample_c_fifo_cap)
);

vdif_chain_fifo_w16_d2_S_x payload_words_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_din),
    .if_full_n(payload_words_c_full_n),
    .if_write(Loop_VITIS_LOOP_71_1_proc_U0_payload_words_c_write),
    .if_dout(payload_words_c_dout),
    .if_empty_n(payload_words_c_empty_n),
    .if_read(packetizer_U0_payload_words_read),
    .if_num_data_valid(payload_words_c_num_data_valid),
    .if_fifo_cap(payload_words_c_fifo_cap)
);

vdif_chain_start_for_packetizer_U0 start_for_packetizer_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_packetizer_U0_din),
    .if_full_n(start_for_packetizer_U0_full_n),
    .if_write(entry_proc7_U0_start_write),
    .if_dout(start_for_packetizer_U0_dout),
    .if_empty_n(start_for_packetizer_U0_empty_n),
    .if_read(packetizer_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc7_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc7_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc7_U0_ap_ready <= ap_sync_entry_proc7_U0_ap_ready;
        end
    end
end

assign Loop_VITIS_LOOP_71_1_proc_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_71_1_proc_U0_ap_start = ((ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign adc_in_TREADY = Loop_VITIS_LOOP_71_1_proc_U0_adc_in_TREADY;

assign ap_done = packetizer_U0_ap_done;

assign ap_idle = (packetizer_U0_ap_idle & entry_proc7_U0_ap_idle & Loop_VITIS_LOOP_71_1_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready | Loop_VITIS_LOOP_71_1_proc_U0_ap_ready);

assign ap_sync_entry_proc7_U0_ap_ready = (entry_proc7_U0_ap_ready | ap_sync_reg_entry_proc7_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc7_U0_ap_ready & ap_sync_Loop_VITIS_LOOP_71_1_proc_U0_ap_ready);

assign entry_proc7_U0_ap_continue = 1'b1;

assign entry_proc7_U0_ap_start = ((ap_sync_reg_entry_proc7_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign out_stream_TDATA = packetizer_U0_out_stream_TDATA;

assign out_stream_TKEEP = packetizer_U0_out_stream_TKEEP;

assign out_stream_TLAST = packetizer_U0_out_stream_TLAST;

assign out_stream_TSTRB = packetizer_U0_out_stream_TSTRB;

assign out_stream_TVALID = packetizer_U0_out_stream_TVALID;

assign packetizer_U0_ap_continue = 1'b1;

assign packetizer_U0_ap_start = start_for_packetizer_U0_empty_n;

assign start_for_packetizer_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "vdif_chain_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "vdif_chain_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //vdif_chain

