// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vdif_chain_packetizer_Block_entry_fsm_state_fb_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] fsm_state;
wire    next_state_assign_4_packet_fsm_1_fu_18_ap_ready;
wire   [0:0] next_state_assign_4_packet_fsm_1_fu_18_ap_return;
wire    next_state_assign_3_packet_fsm_2_fu_23_ap_ready;
wire   [1:0] next_state_assign_3_packet_fsm_2_fu_23_ap_return;
wire    next_state_assign_2_packet_fsm_fu_29_ap_ready;
wire   [0:0] next_state_assign_2_packet_fsm_fu_29_ap_return;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 fsm_state = 1'd0;
end

vdif_chain_packet_fsm_1 next_state_assign_4_packet_fsm_1_fu_18(
    .ap_ready(next_state_assign_4_packet_fsm_1_fu_18_ap_ready),
    .current_state(fsm_state),
    .ap_return(next_state_assign_4_packet_fsm_1_fu_18_ap_return),
    .ap_rst(ap_rst)
);

vdif_chain_packet_fsm_2 next_state_assign_3_packet_fsm_2_fu_23(
    .ap_ready(next_state_assign_3_packet_fsm_2_fu_23_ap_ready),
    .current_state(next_state_assign_4_packet_fsm_1_fu_18_ap_return),
    .ap_return(next_state_assign_3_packet_fsm_2_fu_23_ap_return),
    .ap_rst(ap_rst)
);

vdif_chain_packet_fsm next_state_assign_2_packet_fsm_fu_29(
    .ap_ready(next_state_assign_2_packet_fsm_fu_29_ap_ready),
    .current_state(next_state_assign_3_packet_fsm_2_fu_23_ap_return),
    .ap_return(next_state_assign_2_packet_fsm_fu_29_ap_return),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        fsm_state <= next_state_assign_2_packet_fsm_fu_29_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

endmodule //vdif_chain_packetizer_Block_entry_fsm_state_fb_proc
